### ISSUE TITLE
Unacceptable file type, only regular file is allowed

### ISSUE THREAD

**Issue by Treverr** [WDaan/VueTorrent#10]
Hello,

I followed the instructions for this which are pretty straightforward, but once I pointed QB to it, I get the error of 

```
Unacceptable file type, only regular file is allowed
```
I am on v4.2.1, which had some fixes in it regarding the public/index.html but I still get the same error

I saw previously in issue #5 that it was a separate app, is this still the case? The instructions just have you point the alt webui in qb, but that didn't work here.

Thanks!

**Comment by WDaan** [comment]
Hi! Thank you for taking an interest!

Issue #5 is no longer the case, it IS an alternative webui now.

I've started rewriting it literally yesterday, so it's still in it's very early stages.

When you unzip it you'll get a vuetorrent folder, you should point it to this folder.

If that still doesn't work, I'll look into it in the morning.

**Comment by Treverr** [comment]
Hi @WDaan! Thanks for the reply, yeah pointing to the vuetorrent/ doesn't seem to work with v4.2.5 I've posted on their site too to see if maybe this is an issue with them

**Comment by WDaan** [comment]
I just tested it with v4.2.5 and it works fine

**Comment by Treverr** [comment]
Hmm interesting.

So I have it set up like this:
```
trever@server:~/Volumes/Storage/Web/VueTorrent$ ls -l
total 508
-rwxrwxrwx  1 nobody nogroup  35149 May 20 11:22 LICENSE
-rwxrwxrwx  1 nobody nogroup   1256 May 20 11:22 package.json
-rwxrwxrwx  1 nobody nogroup 458756 May 20 11:22 package-lock.json
drwxrwxrwx  2 nobody nogroup   4096 May 21 13:40 public
-rwxrwxrwx  1 nobody nogroup   1772 May 20 11:22 README.md
drwxrwxrwx 10 nobody nogroup   4096 May 20 11:22 src
-rwxrwxrwx  1 nobody nogroup    235 May 21 13:15 vue.config.js
```

And then my qb config:
```
WebUI\AlternativeUIEnabled=true
WebUI\RootFolder=/Volumes/Storage/Web/VueTorrent/
```

Is there something I'm missing or misunderstanding?

**Comment by WDaan** [comment]
I don' t know if your using docker or not but I just tested it in a docker container.
- placed vuetorrent folder in mounted /config directory.
- set alternate webui location to /config/vuetorrent (by using the settings menu)

In the qBittorrent.conf I get:
```
WebUI\AlternativeUIEnabled=true
WebUI\RootFolder=/config/vuetorrent
```

I don't know what you're doing wrong 😅

**Comment by Treverr** [comment]
I think that was the main issue here. I just realized as you posted that about the docker, dumb oversight.

What is the devServer on port 8000? Is that something I can change? I have Splunk running on port 8000.

**Comment by WDaan** [comment]
Something you shouldn't need to worry about at all!

During development I access the webui on port 8000, but is proxy's the requests to port 8080 (which my qbitorrent uses).

You shouldn't be changing any port settings! 
When I tested it in a docker-container, I randomly set it's webui to port 8083 and it worked fine.

**Comment by Treverr** [comment]
Gotcha- hmm okay. I got a little further but I'm just getting a blank page after moving it to the config folder. Looks like the JS isn't building the page for some reason.

**Comment by Treverr** [comment]
Its breaking here

```[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (%3C%=%20BASE_URL%20%%3Efavicon.ico, line 0)
```
Shouldn't BASE_URL be declared somewhere?

**Comment by WDaan** [comment]
If it's a service-worker error, I got that one too... shouldn't affect it.
Otherwise I have no clue! 

The BASE_URL shouldn't need to be set, unless you're using a reverse-proxy but even then.

Mind you, this is very very much in it's early stages. 
I haven't even made a stable release yet.
I'm working on everything, right now! :)

**Comment by FranciscoPombal** [comment]
@Treverr 

> Hmm interesting.
> 
> So I have it set up like this:
> 
> ```
> drwxrwxrwx  5 nobody nogroup       4096 May 21 13:15 VueTorrent
> ```
> 
> And the files in the directory:
> 
> ```
> trever@server:/Volumes/Storage/Web/VueTorrent$ ls -l
> total 508
> -rwxrwxrwx  1 nobody nogroup  35149 May 20 11:22 LICENSE
> -rwxrwxrwx  1 nobody nogroup   1256 May 20 11:22 package.json
> -rwxrwxrwx  1 nobody nogroup 458756 May 20 11:22 package-lock.json
> drwxrwxrwx  2 nobody nogroup   4096 May 21 13:40 public
> -rwxrwxrwx  1 nobody nogroup   1772 May 20 11:22 README.md
> drwxrwxrwx 10 nobody nogroup   4096 May 20 11:22 src
> -rwxrwxrwx  1 nobody nogroup    235 May 21 13:15 vue.config.js
> ```
> 
> And then my qb config:
> 
> ```
> WebUI\AlternativeUIEnabled=true
> WebUI\RootFolder=/Volumes/Storage/Web/VueTorrent/
> ```
> 
> I also tried
> 
> ```
> WebUI\AlternativeUIEnabled=true
> WebUI\RootFolder=/Volumes/Storage/Web/VueTorrent/public
> ```
> 
> Is there something I'm missing or misunderstanding?

You need to actually "build" it first, or download a pre-packaged release from the releases page. What you are doing right now is akin to cloning the qBittorrent repo and trying to run the `.cpp` files, instead of compiling them into an executable. That's why it's not working.

@WDaan you could probably make this clear in the readme. Right now it kind of makes it seem that one can just `git clone` the repo, point qBittorrent at that.

**Comment by WDaan** [comment]
@FranciscoPombal 

I'm sorry, I thought it was pretty clear 😅
I hope it's less confusing now.

**Comment by Treverr** [comment]
Ah yeah that was it!

**Comment by Urvdmih** [comment]
I have this problem too.
I downloaded latest realese and unzip this in \etc\qBittorrent_entware\config\
![image](https://user-images.githubusercontent.com/9265883/111024646-f7571080-83f0-11eb-8fce-de86b452bdfb.png)
My config
WebUI\AlternativeUIEnabled=true
WebUI\AuthSubnetWhitelist=@Invalid()
WebUI\AuthSubnetWhitelistEnabled=false
WebUI\CSRFProtection=true
WebUI\ClickjackingProtection=true
WebUI\HTTPS\Enabled=false
WebUI\HostHeaderValidation=true
WebUI\LocalHostAuth=true
WebUI\Password_ha1=
WebUI\Port=9080
WebUI\RootFolder=/etc/qBittorrent_entware/config/vuetorrent

That's wrong?

**Comment by TTPhoeny** [comment]
I have qbittorrent-nox 4.1.7 running on a ubuntu 20.04.2 vm

i extracted the zipfile to /home/qbittorrent-nox/vuetorrent and set that path in webui. 

As long as i do not log out it works beautifully, but every browser which isn't logged in gets "Unacceptable file type, only regular file is allowed."

**Comment by Rerbun** [comment]
> I have qbittorrent-nox 4.1.7 running on a ubuntu 20.04.2 vm
> 
> i extracted the zipfile to /home/qbittorrent-nox/vuetorrent and set that path in webui.
> 
> As long as i do not log out it works beautifully, but every browser which isn't logged in gets "Unacceptable file type, only regular file is allowed."

Same here with Qbittorrent-nox 4.1.5

**Comment by lakimakromedia** [comment]
Same for me 4.4.3.1 on unraid :/
And I fallowed ibracorp tut on YT

**Comment by leni8ec** [comment]
In my case, the solution was to change the path from:

`/etc/qBittorrent_entware/themes/vuetorrent`

To:

`/opt/etc/qBittorrent_entware/themes/vuetorrent`

**Comment by stephenshutters** [comment]
> @Treverr
> 
> > Hmm interesting.
> > So I have it set up like this:
> > ```
> > drwxrwxrwx  5 nobody nogroup       4096 May 21 13:15 VueTorrent
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And the files in the directory:
> > ```
> > trever@server:/Volumes/Storage/Web/VueTorrent$ ls -l
> > total 508
> > -rwxrwxrwx  1 nobody nogroup  35149 May 20 11:22 LICENSE
> > -rwxrwxrwx  1 nobody nogroup   1256 May 20 11:22 package.json
> > -rwxrwxrwx  1 nobody nogroup 458756 May 20 11:22 package-lock.json
> > drwxrwxrwx  2 nobody nogroup   4096 May 21 13:40 public
> > -rwxrwxrwx  1 nobody nogroup   1772 May 20 11:22 README.md
> > drwxrwxrwx 10 nobody nogroup   4096 May 20 11:22 src
> > -rwxrwxrwx  1 nobody nogroup    235 May 21 13:15 vue.config.js
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And then my qb config:
> > ```
> > WebUI\AlternativeUIEnabled=true
> > WebUI\RootFolder=/Volumes/Storage/Web/VueTorrent/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I also tried
> > ```
> > WebUI\AlternativeUIEnabled=true
> > WebUI\RootFolder=/Volumes/Storage/Web/VueTorrent/public
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is there something I'm missing or misunderstanding?
> 
> You need to actually "build" it first, or download a pre-packaged release from the releases page. What you are doing right now is akin to cloning the qBittorrent repo and trying to run the `.cpp` files, instead of compiling them into an executable. That's why it's not working.
> 
> @WDaan you could probably make this clear in the readme. Right now, for someone unfamiliar with the VueJS/JavaScript world it kind of makes it seem that one can just `git clone` the repo and point qBittorrent at that.

I'm having this exact same issue. How does one go about "building" it?

**Comment by Larsluph** [comment]
Follow the installation section of the readme You don't need to build it, just clone the release branch and you'll be good to go
