### ISSUE TITLE
Possible UI tweaks

### ISSUE THREAD

**Issue by agneevX** [WDaan/VueTorrent#100]
I think the following should be implemented specifically so that navigation and usability on mobile devices is improved:

- `Added On` removed
- `Torrent title`/`Done` label text removed
- `Seeds` and `Peers` side-by-side
- show entire torrent name 
- adjust text spacing...
  - less space between text label and text
- Auto dark mode (w/ header color)

**Comment by WDaan** [comment]
I'm actually working out a whole redesign with @coreyvidal to specifically adres this issue specifically.

You seem to be someone interested in designing as well, maybe we can work something out together.

**Comment by agneevX** [comment]
I am interested, however I'm not a frontend dev 😅

**Comment by WDaan** [comment]
Neither is he, it's mostly ideas about how it should look & function + feedback.
Implementing will  probably be done by me, unless someone else volunteers to help :sweat_smile:

**Comment by agneevX** [comment]
Well in that case, I'm happy to help :)

**Comment by WDaan** [comment]
current iteration, I'm just winging it 😅 feel free to suggest changes

![image](https://user-images.githubusercontent.com/25707052/105510053-7de35180-5cce-11eb-809a-f38c4606b2ba.png)

**Comment by agneevX** [comment]
Whoa! Kudos this is great work.

**Comment by agneevX** [comment]
I have suggestions:

- some space between torrents
- `Dashboard` text in bold
- Colored labels slightly more height and text centered
- slightly more compact items (so more fit)...

**Comment by WDaan** [comment]
What do you mean with 'status beside filter box'??

**Comment by agneevX** [comment]
Actually scratch that. I think the sidebar should be reworked. 

E.g. total upload/download speeds should be in the main view.

The drop down for `Status` should be removed, with options directly listed, so they can be easily navigated.

(Possible bug in current release where `Status` resets to All upon PWA relaunch, tested on mobile.)

Also, in the sidebar, maybe rename `Session Status` to `Session Stats`??

**Comment by agneevX** [comment]
I'd also suggest increasing the corner radii to something like 6 or 8px, achieving a rather modern look.

**Comment by WDaan** [comment]
yo, none of these have anything to do with 'UI tweaks for mobile' 😅

> Actually scratch that. I think the sidebar should be reworked.
> E.g. total upload/download speeds should be in the main view.

 => just the speed in numbers... I guess, I could put that somewhere
> The drop down for `Status` should be removed, with options directly listed, so they can be easily navigated.

=> I think this takes up way to much space & makes it look cluttered
> (Possible bug in current release where `Status` resets to All upon PWA relaunch, tested on mobile.)

=> is now fixed
> Also, in the sidebar, maybe rename `Session Status` to `Session Stats`??

=> ok

**Comment by agneevX** [comment]
> yo, none of these have anything to do with 'UI tweaks for mobile' 😅

😅

> I think this takes up way to much space & makes it look cluttered

What about a more functional dropdown like how `qb-web` does it in the sidebar??

<img width="305" alt="image" src="https://user-images.githubusercontent.com/19761269/105575944-6e7b0b80-5d95-11eb-9a35-01554d5d862c.png">

**Comment by WDaan** [comment]
@CoreyVidal what do you think?

**Comment by agneevX** [comment]
Love the new update...

<img src="https://user-images.githubusercontent.com/19761269/105576885-ff54e580-5d9b-11eb-9160-5e743ba3bb12.png" width="200">

Couple of notes

- Torrent title should not be truncated and instead should overflow to a second line
- Old `Select mode` icon made it easier to identify its function
- Upload speed overflows to a second line - sidebar
- A separator between session upload and download should be added 
- An increase in `Dashboard` text font size 
- `State` and `Categories` in sidebar should have a label and be positioned above `Session Stats`
- `Current Speed` unit font weight would look better if it was slightly increased
- Alt speed indicator color seems to be broken in this release

Dark mode looks absolutely gorgeous. 

(Apologies if I came off as condescending, absolutely not my intention.)

**Comment by WDaan** [comment]
Thanks for testing!
I knew this update would cause a LOT of small issues because there have been many changes behind the scenes.
It's hard for me to keep track of every single thing 😅
I'll get on it

**Comment by agneevX** [comment]
Much appreciated. Also it seems that auto dark mode is not functional.

**Comment by agneevX** [comment]
Just tried v0.5.1. 

> Torrent title should not be truncated and instead should overflow to a second line

Can the line spacing be decreased slightly? Thanks.

**Comment by IevgenSobko** [comment]
Great work with mobile ui torrents list.
It is awesome.
Are you planning to redesing torrent modal popup? In particular I mean content tab.
Now it looks broken.

**Comment by WDaan** [comment]
The Torrent Detail modal has been bothering me since the start, it feels buggy. 
Unfortunately I haven't yet found a decent way to solve this.
If you're just talking about how it looks, I just used the built-in component of the framework. I haven't yet found another decent package out there that I like.

Feel free to suggest something, but I think this is going to be a difficult one. Unless some other code wizard decides to show himself 😝

**Comment by agneevX** [comment]
Re: 0.5.2

<img src="https://user-images.githubusercontent.com/19761269/105627924-b1a1b100-5e5f-11eb-98ff-1ae9e57d65db.png" width="380">

- Torrent title text is obfuscated on the right, and can the font size be decreased slightly?
- Current DL/UL speeds would look better in bold
- Revert to using the earlier separator (`•`) instead of `-`
- Before the redesign, the left/right padding looked ideal to me. Can you revert to that?
- A space after the percentage would look better
- `•` separator between `seeds` and `peers`
- A slightly rounded progress bar with a bit more width, aligned with the rest of the text can look better


Can you draw inspiration from the nzb360 app?

<img src="https://user-images.githubusercontent.com/19761269/105628158-435dee00-5e61-11eb-950e-4b9de5f595dd.png" width="380">

**Comment by WDaan** [comment]
I did, I just hate designing 😅

**Comment by agneevX** [comment]
The thing about design is that you'll always think something is wrong even if it's perfect to someone else.

**Comment by agneevX** [comment]
What do you think about this as an icon?

![IMG_0018 Edited](https://user-images.githubusercontent.com/19761269/105630759-fd108b00-5e70-11eb-9a55-364c8f61c2df.png)

**Comment by WDaan** [comment]
I like it 😀

Don't know if other people like it as well

**Comment by WDaan** [comment]
@agneevX 

![image](https://user-images.githubusercontent.com/25707052/105631978-52d53b00-5e51-11eb-8181-a99e4e087bb4.png)

like this??

**Comment by agneevX** [comment]
Very close. Progress bar looks very appealing :)

- Font should be slightly larger than the surrounding font
- The separator should be in the secondary text color
- Please increase the padding above the torrent title so it matches the space below seeds/peers
- Text labels would need to be aligned more (e.g. `2.59 GB`)
- increase width of the color strip on the left?
- align ETA to the right like nzb360 and remove the label?
- remove `Ratio` label?
- a bit more vertical padding on the colored labels?
- What do you think about moving the State to below seeds/peers like nzb360?

As for the icon, I think it needs to be a variant of the original qBittorrent logo combined with the green-ness of Vuejs.

**Comment by WDaan** [comment]
Damnit 😅 I get more & more remarks with every iteration

**Comment by CoreyVidal** [comment]
Playing around with the CURRENT SPEED module/surface in the top-left corner, I came up with this:

![Untitled-1](https://user-images.githubusercontent.com/20746389/105637232-57dac000-5e3a-11eb-9024-a4cd6f1ab9de.png)

I feel like it can help the jumpiness of the _B/s moving around too much.

**Comment by agneevX** [comment]
@WDaan 

> I think ratio looks weird without a label, it would just be a random number

If its positioned in an appropriate location, it can look like a ratio without the need for a superfluous label. 

> if ETA goes on the right, where does percentage go?

Next to the `downloaded size / total size`. Would make more sense as they're directly related. 

> I don't think I can put state next to seeds/peer, takes up to much space

Are you sure? There's a lot of free space beside it.

**Comment by WDaan** [comment]
Not if both download and upload speed are there

**Comment by agneevX** [comment]
True. In that case, I guess you can hide less important details like peers, for e.g. peers.

**Comment by agneevX** [comment]
On a side note, can the values in bytes in Torrent Detail be converted to an appropriate unit?

**Comment by WDaan** [comment]
@agneevX Yes! Mustve forgotten about it in 0.5.0...did a refactor for performance

**Comment by Antonet99** [comment]
Hi @WDaan, first of all thank your for this great webUI!
But I have a question: Am I unable to see it, or there's not an option to download the torrents in sequential order like in the "standard" UI? Maybe I'm missing it, but I would love to have that! For example, first download Season 1, then Season 2 etc etc...
<img width="229" alt="Schermata 2021-01-27 alle 10 48 59" src="https://user-images.githubusercontent.com/50658637/105973784-6ff64d80-608d-11eb-8f69-69deadfb53e6.png">

**Comment by WDaan** [comment]
Seems like most of these are solved, I will close this to keep the issues organised
Please create a new issue with appropriate [tag]

**Comment by agneevX** [comment]
Can the overflow menu be reordered?

Preferably, this is 

- [ ] Select mode
- [ ] Sort
- [ ] Add
- [ ] Resume
- [ ] Pause
- [ ] Remove
- [ ] Torrent search
- [ ] Settings

### Remove torrent modal

- Word wrap torrent title
- Set <kbd>Delete with files</kbd> color to red
- Set <kbd>Cancel</kbd> color to teal

### Desktop

- Increase spacing between rows
- Slightly decrease upper and lower padding of torrent items

**Comment by agneevX** [comment]
Would be nice of course, if select/sort get their own place, since their function is different from other items.

Do you think you can add these two beside the overflow menu in a mobile view along with a combined play/pause button? Why? Pausing a torrent takes as much as 6 taps on mobile :(

**Comment by WDaan** [comment]
@CoreyVidal suggested that the searchfilter textfield should expand/hide when tapping the filter icon
This way there's space to put Select & Sort next to it

**Comment by agneevX** [comment]
Yup, that would make a ton of sense. That icon serves no purpose and should be removed. 

Also consider changing the placeholder to `Search` from `filter`.

**Comment by agneevX** [comment]
Also, please center the `XX torrents` text such that its at the center of the `Dashboard` text.

**Comment by agneevX** [comment]
Would be nice if you could round percentage downloaded to one decimal place.

**Comment by agneevX** [comment]
Also, you could reduce the height of the search bar, so the items beside don't look out of place.

**Comment by agneevX** [comment]
Re: 0.5.5

### Dashboard

<img src="https://user-images.githubusercontent.com/19761269/106353513-29188a00-6311-11eb-8c17-0a6897c1fee0.png" width="300">

- Reduce the height and width of the search bar so the items fit beside it
- Search bar should persist, so please remove the filter button,
- In place of that, please add a pause/resume button (`mdi-play-pause`) so its easier on phones
- Align search bar to the text above
- Please change the black border of the search to a lighter color
- On the right, if torrent = 1, `torrent`, not `torrents`

<img src="https://user-images.githubusercontent.com/19761269/106353646-0470e200-6312-11eb-96a3-be6fa99bbe03.png" width="400">

- Text cuts off at the right side/extends too much towards the "safe area", which should be the same as the width from which the text starts, on the left 
- Please decrease the padding on both sides on mobile so more text is able to fit
- The padding at the bottom of the item (`seeds peers`) seems a bit more than on the top, would be nice if you could add some on the top

### Sidebar

- Sidebar `Current Speed`, please revert to using the earlier font
- Reduce UL/DL speeds box padding which looks unnecessary
- `Session Stats` → please round units in `MB` to 1 decimal place, below that to 0
- `Session Stats` tooltip is redundant, because that's what it means??

**Comment by WDaan** [comment]
@agneevX Please stop spamming issues & bossing me around, thanks

**Comment by agneevX** [comment]
Oh I'm sorry, I was only trying to help. I didn't realize you didn't value suggestions anymore.

**Comment by WDaan** [comment]
My apologies for the bold reaction. You're not spamming, it's a thread after all...

You have made some great suggestions in the past. I just don't like the nitpicking on every single thing I do. Makes it look like everything I do is wrong 😅

**Comment by agneevX** [comment]
@WDaan not sure what I did for this behavior, but it's great to get a middle finger after I've helped improve this project.
