### ISSUE TITLE
Unacceptable file type, only regular file is allowed.

### ISSUE THREAD

**Issue by JoeyStrandnes** [WDaan/VueTorrent#101]
#### I really do like your custom UI and would like to continue to use it :)

**Comment by CoreyVidal** [comment]
(Go to the bottom for the answer.)

Hey,

So I'm also running qBittorrent-nox on FreeNAS. Are you using the official qBittorrent "plugin" (which creates a jail), or did you make your own jail from scratch and then inside of FreeBSD install qBittorrent-nox? (I found the 2nd option much better).

I first reccomend switching form the "Quarterly"  FreeBSD packages, to the "Latest". To do that, enter your jail with Shell as root, and then run this (anywhere)

`pkg update`

`pkg upgrade`

`pkg install nano`

`nano /etc/pkg/FreeBSD.conf`

Change `quarterly` to `latest`

Save and exit.

Now back in the command line, run:

`pkg update`

`pkg upgrade`

You now have the latest packages for FreeBSD.

To install/update qBittorrent-nox, you should run both of these commands

`pkg install jq`

`pkg install qbittorrent-nox`

---

The main qBittorrent location is here:

/var/db/qbittorrent/

And the config file is:

/var/db/qbittorrent/conf/qBittorrent/config/qBittorrent.conf

I hope that helps!

**Comment by JoeyStrandnes** [comment]
@CoreyVidal  Thanks for the response!

I unfortunately installed the qBittorrent through the plugin system...

Tried changing the build to `latest` rather than `quarterly` but it didn’t seem to change anything. 
Used `pkg update` & `pkg upgrade`
So i tried the "force" option.

Running `pkg install jq` (anything really) returns the no packages available error. I assume this has to do with the fact that it is a plugin install and not a manual install.

Lastly anything beyond `/var/db/qbittorrent/` is just empty folders. 

I’m a noob when it comes to high level systems so pleas bear with me!

![Change](https://user-images.githubusercontent.com/26739868/104348432-03fadd80-5502-11eb-87d6-836d417e5aea.png)
![pkg](https://user-images.githubusercontent.com/26739868/104348468-0e1cdc00-5502-11eb-80bf-66c18b026861.png)

**Comment by WDaan** [comment]
I don't want to sound rude but I suggest you choose another method of installing QBitorrent. I can't support every possible variant of Qbittorrent, please try to use the most mainstream and up-to-date version.
