### ISSUE TITLE
search torrents by keyword: losts of irrelevant results returned

### ISSUE THREAD

**Issue by tainewoo** [WDaan/VueTorrent#1018]
The search result is incorrect if you try to search the torrents by keywords.

Step:
1. input the keyword "ace" to search the torrents in the torrent list page.
2. some of the returned results contains "ace", also lots of the torrents which don't contain the keyword "ace" are listed.

Notes:
This issue is not existed with the qBittorrent original web ui.
Tried with release 1.5.12 and 1.6.1, both failed.

The captured screenshot is attached as below.
![search_error](https://github.com/WDaan/VueTorrent/assets/13391232/e6c8da91-8a41-43e2-84d9-cbae124003e9)

**Comment by Larsluph** [comment]
That's because we use the `quick-score` library to search torrents. It calculates a score for each torrent and we display them from most to least relevant.
It uses a fuzzy-matching method so small "distance" between two words will also match, that's why you see torrents not matching exactly your query.

**Comment by Larsluph** [comment]
The search method may change in the Vue 3 migration

**Comment by tainewoo** [comment]
> The search method may change in the Vue 3 migration

Cool, that would be great!

Further, will we support the search using multiple keywords at that time?
Such as, if we input the search as: 
ace blu
Then the web ui will show torrent tasks which contains both "ace" and "blu", such as xxxaceyyy.zzbluaaa

**Comment by Larsluph** [comment]
> Further, will we support the search using multiple keywords at that time?

If we drop the `quick-score` lib, we may opt for that solution instead.

**Comment by tainewoo** [comment]
> > Further, will we support the search using multiple keywords at that time?
> 
> If we drop the `quick-score` lib, we may opt for that solution instead.

Thank you for your explain.
For current 'quick-score' method, if we specify a short keyword, there might be many irrelevant results returned.
But if we specifies long keyword or more keywords, the search result can be accurate.

for the problemI described in this issue, I think it might because the keyword I used is too short.
I will try to use more keywords or longer keyword to search.
