### ISSUE TITLE
[Feature Request] Add autocompletion to new torrent location

### ISSUE THREAD

**Issue by IevgenSobko** [WDaan/VueTorrent#102]
It would be great to have autocompletion for the new torrent location.
When you click add new torrent and form appear filed with destination folder should have some auto-completion functionality.
Either based on your previously entered locations or you just parse a list of all torrents and build a set of unique locations.
This going to help if you need to add a torrent to one of the already selected locations and remove unnecessary steps by opening the file browser and searching the full path to the destination directory over and over again.
See attached screenshot of original web UI functionality.
![2021-01-13__00-41-56](https://user-images.githubusercontent.com/14232100/104383716-f280f800-5538-11eb-8435-331ab8bf15a6.png)

**Comment by IevgenSobko** [comment]
@WDaan how to activate this autocompletion?
I updated to 0.5.1 but it seems doesn't have any autocompletion on torrent add for download location.

**Comment by WDaan** [comment]
![image](https://user-images.githubusercontent.com/25707052/105612426-71d5bd80-5dbc-11eb-8a96-6ae2930e4108.png)

by using it, your browser saves what you've previously entered. 
I think that's how the default one works as well
It's not 'smart' autocomplete or anything like that (yet)

**Comment by IevgenSobko** [comment]
Oh, now I see.
Thank you for explanation.
