### ISSUE TITLE
Do not remember "Also delete files from storage"

### ISSUE THREAD

**Issue by herrenP** [WDaan/VueTorrent#1020]
I am fairly sure that the original UI for qBittorrent do not remember if the user has checked "Also delete files from storage". At least I cannot remember ever having the issue that I have accidentally deleted the files on disk when I delete a torrent from the list. So, either VueTorrent remember the checkbox being checked from last time I checked it or I could remember incorrectly and the original UI does the same but instead the issue I'm having is #1010 (that it's not apparent enough to the user that this checkbox is checked or not).

Lost a few days of downloads and I unfortunately didn't even notice this after I had deleted like 5-10 torrents, so now I don't even remember what they were. It's a nice UI otherwise, but this was a bit painful.

Using version 1.6.1 by the way.

**Comment by herrenP** [comment]
It seems the UI remember the choice even when no action was taken. I.e. I can click "Delete" on a torrent and check the checkbox to delete files on disk, then click "Cancel" and again click "Delete". The checkbox will now have whatever state I put it in last time before clicking cancel. Seems like a weird behavior to me.

**Comment by Larsluph** [comment]
Well, it's not weird, it's just that we bound the checkbox to your local storage so that it is remembered.
Personally, I rely A LOT on this and I think most users do as well, so I won't change the current behavior.
Also, the color of the button already clearly indicates that the action is destructive as mentioned in the other issue.

**Comment by herrenP** [comment]
Ah, I see. Thanks for letting me know!
