### ISSUE TITLE
Tab freeze upon opening torrent info

### ISSUE THREAD

**Issue by oplexz** [WDaan/VueTorrent#1023]
Only affects torrents that have a lot of files. Tested on multiple torrents, each one had 5k+ files.
As soon as `api/v2/torrents/files` returns the files, the tab freezes.
Some pagination or "load more" button would definitely help eliminate the issue.

**Comment by Larsluph** [comment]
The canvas is causing this freeze. You also have one while generating the torrent content file tree but only when you open the content tab.

**Comment by oplexz** [comment]
> The canvas is causing this freeze. You also have one while generating the torrent content file tree but only when you open the content tab.

@Larsluph sounds about right
Is there any way to tone down the canvas, so it doesn't freeze the tab?

**Comment by Larsluph** [comment]
Actually I thought having already fixed that issue when working on the overview tab 😅
I don't remember why I dropped it but, it can be fixed really quickly
