### ISSUE TITLE
WebUI not displayed after exiting

### ISSUE THREAD

**Issue by DuBass858** [WDaan/VueTorrent#104]
Good day!
Your WebUI is awesome!
I set up path to vuetorrent and that's work great. After logout i try to log in and can see only mistake:
![image](https://user-images.githubusercontent.com/77126974/104836899-1d18db00-58c2-11eb-8e40-e410d106900d.png)

When i change config to reuse alternative webui again everything works until the log out

What i do incorrect? what information to provide for error analysis?

Linux raspberrypi 5.4.83-v7l+
qBittorrent-nox v4.1.5
VueTorrent v0.4.9

qBittorrent.conf:
[AutoRun]
enabled=true
program=/home/qbittorrent/.config/qBittorrent/external/savecategory+\"%D\"+\"%I\"+\"%N\"

[BitTorrent]
Session\Categories="@Variant(\0\0\0\b\0\0\0\x1\0\0\0\f\x4$\x4\x38\x4;\x4L\x4<\x4K\0\0\0\n\0\0\0\"\0/\0m\0n\0t\0/\0m\0\x65\0\x64\0i\0\x61\0/\0\x46\0i\0l\0m\0s\0/)"
Session\CreateTorrentSubfolder=true
Session\DisableAutoTMMByDefault=false
Session\DisableAutoTMMTriggers\CategoryChanged=false
Session\DisableAutoTMMTriggers\CategorySavePathChanged=false
Session\DisableAutoTMMTriggers\DefaultSavePathChanged=false
Session\SlowTorrentsDownloadRate=5
Session\SlowTorrentsUploadRate=5

[Core]
AutoDeleteAddedTorrentFile=IfAdded

[Preferences]
Bittorrent\AddTrackers=false
Bittorrent\MaxConnecs=2500
Bittorrent\MaxConnecsPerTorrent=500
Bittorrent\MaxRatioAction=0
Bittorrent\PeX=true
Bittorrent\uTP_rate_limited=false
Connection\GlobalDLLimit=102400
Connection\GlobalDLLimitAlt=100
Connection\GlobalUPLimit=102400
Connection\GlobalUPLimitAlt=102400
Connection\PortRangeMin=51414
Connection\alt_speeds_on=false
Downloads\PreAllocation=true
Downloads\SavePath=/mnt/media/download/
Downloads\ScanDirsV2=@Variant(\0\0\0\x1c\0\0\0\x2\0\0\0\x32\0/\0m\0n\0t\0/\0m\0\x65\0\x64\0i\0\x61\0/\0T\0o\0r\0r\0\x65\0n\0t\0s\0/\0w\0\x61\0t\0\x63\0h\0\0\0\x2\0\0\0\x1\0\0\0\x32\0/\0m\0n\0t\0/\0m\0\x65\0\x64\0i\0\x61\0/\0T\0o\0r\0r\0$
Downloads\StartInPause=false
Downloads\TempPath=/mnt/media/Torrents/incomplete/
Downloads\TempPathEnabled=true
DynDNS\DomainName=changeme.dyndns.org
DynDNS\Enabled=false
DynDNS\Password=
DynDNS\Service=0
DynDNS\Username=
General\Locale=ru_RU
General\UseRandomPort=false
MailNotification\email=
MailNotification\enabled=false
MailNotification\password=
MailNotification\req_auth=true
MailNotification\req_ssl=false
MailNotification\sender=qBittorrent_notification@example.com
MailNotification\smtp_server=smtp.changeme.com
MailNotification\username=
Queueing\IgnoreSlowTorrents=true
Scheduler\days=0
Scheduler\end_time=@Variant(\0\0\0\xf\x4J\xa2\0)
Scheduler\start_time=@Variant(\0\0\0\xf\x1\xb7t\0)
WebUI\Address=*
WebUI\AlternativeUIEnabled=true
WebUI\AuthSubnetWhitelist=@Invalid()
WebUI\AuthSubnetWhitelistEnabled=false
WebUI\CSRFProtection=true
WebUI\ClickjackingProtection=true
WebUI\HTTPS\Enabled=false
WebUI\HostHeaderValidation=true
WebUI\LocalHostAuth=false
WebUI\Password_ha1=@ByteArray(830c28c0d63c537bbf1c7cbf416f7ede)
WebUI\Port=8080
WebUI\RootFolder=/home/pi/WebUI/vuetorrent
WebUI\ServerDomains=*
WebUI\UseUPnP=true
WebUI\Username=admin

[SearchEngines]
disabledEngines=@Invalid()

**Comment by DuBass858** [comment]
I have just fix it.
Because i have user qbittorrent so i have to put files VueTorrent to home directory of this user and set permissions.

**Comment by WDaan** [comment]
I am glad you could fix it 🙂

Feel free to close if you no longer have problems regarding this issue
