### ISSUE TITLE
[Bug] Speedometer flicker with larger refresh interval

### ISSUE THREAD

**Issue by flashlab** [WDaan/VueTorrent#1050]
If I change the refresh interval setting from 2000ms to 4000ms, the speedometer drop to ZERO periodly.
![Before](https://github.com/WDaan/VueTorrent/assets/4102853/423f8b02-580b-494e-b98e-deeb8cec71e1)
↑↑↑√↑↑↑  ↓↓↓×↓↓↓
![After](https://github.com/WDaan/VueTorrent/assets/4102853/52f055c0-aa70-49fa-a448-05adcf432284)

**Comment by Larsluph** [comment]
#1002 introduced a bug. You can reload your page to clear any leftovers when switching intervals, it should solve the issue temporarily.
