### ISSUE TITLE
Filter by tracker "(Not Working)" gives no result

### ISSUE THREAD

**Issue by maxiwheat** [WDaan/VueTorrent#1051]
A private tracker I'm using is currently down, and it shows in the torrents details:

![image](https://github.com/WDaan/VueTorrent/assets/1927334/e6e6ca3a-10e5-4244-b886-c2973d61d602)

If I use the sidebar to filter torrents with tracker "(Not Working)", I expect to have the list of torrents affected by the situation, but it returns no results at all:

![image](https://github.com/WDaan/VueTorrent/assets/1927334/c9a6ffac-fa08-4dd4-9694-ee5b63d91120)

![image](https://github.com/WDaan/VueTorrent/assets/1927334/fd458d6c-7625-4212-97ce-7a30e89fe0f2)

**Comment by Larsluph** [comment]
Outdated, switch to v2
