### ISSUE TITLE
Settings: There is a text box below 'Register Magnet Links'

### ISSUE THREAD

**Issue by tmknight** [WDaan/VueTorrent#1053]
Found it completely by mistake on Android via Chrome by errant touch in that space.

![image](https://github.com/WDaan/VueTorrent/assets/548588/0055eac6-f9f9-4390-ba5e-328cda8ca13d)

**Comment by Larsluph** [comment]
That's normal, it is used to import / export your settings

**Comment by tmknight** [comment]
Doh; yes, I see now.
