### ISSUE TITLE
Magnet URI scheme is broken when passed to VueTorrent

### ISSUE THREAD

**Issue by jducaud** [WDaan/VueTorrent#1054]
With `VueTorrent 1.7.1`, any magnet URI classically starting with `magnet:?xt=urn:btih:` is modified into `magnet%3A%3Fxt%3Durn%3Abtih%3A` when passed to the window `Add a New Torrent` in the field `URL` of `VueTorrent 1.7.1`

Same behavior with `Firefox`, `Edge`, `Chrome`.

So I downgraded `VueTorrent` to `1.7.0` and the problem went away.

It seems that all the punctuation characters are translated into their UTF-8 encoding.

With `VueTorrent 1.7.1` I still can copy the magnet URI and paste it into the `URL` field of the `Add a New Torrent` window in `VueTorrent`. But The luxury of just clicking on the magnet and having all the copy-paste thing automatically done is something I would definitively lack.

**Comment by jagadam97** [comment]
@jducaud only PR between 1.7.0 and 1.7.1 , which handles torrent magnet is mine - https://github.com/WDaan/VueTorrent/pull/1041
Can you please describe the the steps to reproduce the issue you were having. This help me in better debugging the issue.
Thanks a Lot

**Comment by jagadam97** [comment]
Sorry for introducing this issue and breaking something this critical.
here is the fix - https://github.com/WDaan/VueTorrent/pull/1056
@Larsluph @WDaan

**Comment by jducaud** [comment]
Thank you very much for your responsiveness @jagadam97. A regression introduced by a pull-request happens, even to the best. You have nothing to apologize for.

I'm very grateful to @WDaan and all his contributors for this wonderful WebUI.

**Comment by Larsluph** [comment]
> Sorry for introducing this issue and breaking something this critical.

Haha no worries!

And btw, I noticed that you don't use magic keywords in your PR, you might want to check that out!
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by jagadam97** [comment]
Yeah. 
I always worked in comapanies using JIRA eco-systems. where whole tracking happens through branches, and never knew something like this exists.. Will follow this for future PRs.
Thanks for the Info
