### ISSUE TITLE
qbittorrent 4.3.3 breaks vuetorrent

### ISSUE THREAD

**Issue by colthreepv** [WDaan/VueTorrent#106]
There must be several API differences between 4.3.2 (the one I am using corrently) and 4.3.3

I can not find a changelog of that, if I find it, I could compile a PR to make both versions compatible

**Comment by WDaan** [comment]
Thank you for letting me know!

**Comment by colthreepv** [comment]
You are right 😮 SORRY!
It's not a problem of VueTorrent, just changing version makes my app completely torrent-empty

Tests have been done with linuxserver/qbittorrent docker image
`linuxserver/qbittorrent:version-14.3.3.99202101191832-7248-da0b276d5ubuntu18.04.1`
and
`linuxserver/qbittorrent:version-14.3.2.99202101080148-7233-0cbd15890ubuntu18.04.1`

**Comment by Asgardsurfer** [comment]
Not seeing any problems either on my end, just chiming in. ￼

**Comment by d0x7** [comment]
My list is also completely empty, while without VueTorrent I have several torrents. Nothing in the dev console and network tab shows successful requests to ```/api/v2/torrents/info``` with data, but nothing is showing nor does anything happen when I add a torrent. Happens both on 0.15.3 and .3. QBit is 4.2.5.
