### ISSUE TITLE
ThemePark Installation

### ISSUE THREAD

**Issue by loyalsnoopdoge** [WDaan/VueTorrent#1068]
I am running VueTorrent in the binhex-qBittorrentVPN docker container on unRAID 6.12.3

I want to add a theme from ThemePark but I cannot find where to add it on VueTorrent. Can someone help?

**Comment by WDaan** [comment]
Doesn't that clash with Vuetorrent's css?

Vuetorrent is a theme in itself, I'm not sure what you're trying to accomplish here and if this is something that we should look into?

**Comment by Larsluph** [comment]
Unfortunately, ThemePark themes are only available for the native qBittorrent's WebUI.
