### ISSUE TITLE
Download path is null

### ISSUE THREAD

**Issue by yuguansu** [WDaan/VueTorrent#1073]
In the latest version of qBittorrent v4.5.4 Web UI (64-bit)   &  qBittorrent Enhanced Edition v4.5.4.10 Web UI (64-bit) , download path is null. 
All installed with docker.

error img
https://img1.imgtp.com/2023/08/30/wU5oZPu6.png

real path
https://img1.imgtp.com/2023/08/30/a18QIFLe.png

**Comment by Larsluph** [comment]
"Download Path" & "Save Path" are two different fields, check out Vuetorrent settings to change this in the torrent card.

**Comment by yuguansu** [comment]
tks, i confused
