### ISSUE TITLE
Wrong date in log file

### ISSUE THREAD

**Issue by Tobiyashi** [WDaan/VueTorrent#1075]
Hi,

the date in the "qBittorrent Logs" is wrong.

For Example:

In the normal log-file in the file system it reads:
"(N) 2023-08-31T09:10:37 - Web UI: Now listening on IP: *, port: 8080
 (N) 2023-08-31T09:10:37 - Options saved."

in the log viewer it shows the following:
"579    NORMAL     Options saved.                                              55633-10-18 03:10:43
 578    NORMAL     Web UI: Now listening on IP: *, port: 8080    55633-10-18 03:10:42"

I am running VueTorrent on Lubuntu 22.04.3 LTS

**Comment by Tobiyashi** [comment]
I am using the latest VueTorrent 1.7.2 and qBVittorrent 4.4.1

**Comment by Larsluph** [comment]
After some discovery, timestamp format changed in qbit 4.5.0.
Please update your qBittorrent instance to fix the issue
