### ISSUE TITLE
Set category for multiple torrents at once

### ISSUE THREAD

**Issue by Darkflicker** [WDaan/VueTorrent#108]
Hi, is there any way to assign a category to multiple torrents at once? Nice WebUI btw.
Thanks.

**Comment by WDaan** [comment]
Thanks! 
No, you cant do that at the moment. :/

**Comment by WDaan** [comment]
How would this be implemented in a user-friendly manner?
What do you propose?
Does the default WebUI have this?

**Comment by Darkflicker** [comment]
Multiple torrents can be selected and the desired category can be set by right-click context menu in the default WebUI. Maybe something similar could be implented here.
