### ISSUE TITLE
Advanced settings tab disappeared

### ISSUE THREAD

**Issue by jbonet** [WDaan/VueTorrent#1081]
Hello,

I upgraded from version 1.5.x to latest 1.7.3 and the advanced settings tab has disappeared, I can't find a setting to turn it on.

**Comment by Larsluph** [comment]
Can you show us the settings page, it works perfectly fine on my instance 🤔

**Comment by jbonet** [comment]
This is how it looks like,

![image](https://github.com/WDaan/VueTorrent/assets/17141983/b8dccef7-b6d1-4f4d-9158-fa7b1817d6d1)

Before updating, I could see the ADVANCED tab, but now it's missing, I might have to enable it somewhere?
