### ISSUE TITLE
Can't rename torrent content files / directory

### ISSUE THREAD

**Issue by flos06** [WDaan/VueTorrent#1090]
Hi Im using qbittorrent 4.2.5 (this is the only qbittorrent that works for me on rpi the later ones from testing/unstable repo are not working unfortunately)

the rename content does not work I get an error: Unable to rename.

I think in 4.2.5 folder renaming wasnt possible yet but files should work?
Maybe I can use an older vuetorrent? Any clues which one I need?

**Comment by Larsluph** [comment]
Unfortunately, we haven't been tracking qBittorrent versions. We only assumed that the WebUI would work in the latest version.

Try looking at the history of the `qbit.ts` file, you should see when the request contract changed.
