### ISSUE TITLE
Remove options from sort by

### ISSUE THREAD

**Issue by flos06** [WDaan/VueTorrent#1091]
Maybe  I'm blind and this is already possible, but I've looked everywhere I feel like.
Is it possible to remove some options from sort by? I usually sort by a few things, but now its such a long list. I'd rather only have the sort by options that I regularly use. I.e. I never sort by hash so would not need that option

**Comment by Larsluph** [comment]
You're not blind, this feature isn't *yet* available. Thanks for the suggestion!

**Comment by WDaan** [comment]
Vue3 rewrite handles this I believe
