### ISSUE TITLE
Display theme issue on initial load 

### ISSUE THREAD

**Issue by rgallo** [WDaan/VueTorrent#1093]
I'm having an issue where the theme seems to not load correctly when I first start/refresh the page, where I get a bright blue side bar and no borders around my torrent entries.  Toggling dark mode off/on seems to fix it.

Before toggling:
![ScreenHint - 9:8:23, 11:13:26 AM](https://github.com/WDaan/VueTorrent/assets/2091352/906d44f9-e8b9-498d-a3ae-0253cfed4bec)

After:
![ScreenHint - 9:8:23, 11:14:07 AM](https://github.com/WDaan/VueTorrent/assets/2091352/ef350a4b-b769-4199-a9fd-8544f34f8185)

**Comment by rgallo** [comment]
Yep, this was somehow getting caused by a credit card recommendation extension.  Thanks!

**Comment by Larsluph** [comment]
Whew, never saw that one coming 😆
