### ISSUE TITLE
"Import Settings" Error: Invalid JSON

### ISSUE THREAD

**Issue by moracha** [WDaan/VueTorrent#1098]
Trying to import settings on a new PC, receiving an error "Invalid JSON! Check console for details" when I try to do so. Latest release v1.7.3.

![8C32LBh](https://github.com/WDaan/VueTorrent/assets/24765601/2f34e78a-887e-4316-8c40-da3dfbb006c3)

**Comment by Larsluph** [comment]
What does the console tell you?
You can see it by pressing F12 on your keyboard
