### ISSUE TITLE
Free space is shown only for a system drive

### ISSUE THREAD

**Issue by kazik56** [WDaan/VueTorrent#11]
Free space is shown only for a system drive. It doesn't mean that I have torrents on system drive, thus this stat is completely irrevelant in my case.

**Comment by WDaan** [comment]
I assumed the stat the api returned was for the drive that is set as the download location, apparently it is not. 
There is not much I can do about it though. (I think)
Add an option to the settings modal to optionally show it?

**Comment by kazik56** [comment]
Yes, that would be a quite elegant solution.

**Comment by Itay1787** [comment]
What's up with that? Because I don't see an option to change it

**Comment by Larsluph** [comment]
Since 5 years now, qBittorrent is calculating free disk space based on the "Default Save Path" settings. You can change this value according to your particular setup to use the correct disk.

https://github.com/qbittorrent/qBittorrent/commit/2aea235e343f3c1b3d00273872d5944b25ed6f1e
