### ISSUE TITLE
Tag filtering not working

### ISSUE THREAD

**Issue by chrisbenincasa** [WDaan/VueTorrent#1105]
Hello, I just installed v1.7.3 and it's great. However, I noticed that filtering by Tag isn't working. When I select a Tag, the torrent list remains unchanged. Filtering by status or category works as expected.

**Comment by chrisbenincasa** [comment]
Digging a little more...this might be an issue with the qBittorrent API itself. I see the tag filter passed as expected in the network tab, but the API is returning non-matching torrents.t

**Comment by chrisbenincasa** [comment]
My version of qbittorrent is one version behind on the relevant webui version -- closing this out, sorry for the noise!

**Comment by Larsluph** [comment]
No probs!
