### ISSUE TITLE
[Feature Request] - Add Download Speed Average to properties to show

### ISSUE THREAD

**Issue by Rouzax** [WDaan/VueTorrent#1106]
Just started using your great theme and am really impressed.
Would it be possible to add `Download Speed Average` to the properties to show?
![image](https://github.com/WDaan/VueTorrent/assets/4103090/5d4b22fa-cd93-44f1-a5cb-3cd4cbd0f190)

**Comment by Larsluph** [comment]
That could be a potential workaround indeed!

**Comment by Rouzax** [comment]
> That could be a potential workaround indeed!

Not sure if that would not still be a to much additional load generation

**Comment by Larsluph** [comment]
Because it doesn't require additional API calls and it's only a basic math computation, so it's negligible 😄

**Comment by Rouzax** [comment]
Great, will test asap
