### ISSUE TITLE
Speed limit incorrectly set

### ISSUE THREAD

**Issue by kondratovbr** [WDaan/VueTorrent#1109]
I've noticed that while speed limit numbers work correctly in the stock WebUI, speed gets limited to a complete crawl for the same number set in VueTorrent. I suspect that the number is incorrectly divided somewhere before providing it to qBittorrent.

**Comment by Larsluph** [comment]
Can you tell us more about the problem here?
Is it happening when saving qbit preferences? If so, can you tell us what is sent (through the "Network" tab of your browser's DevTools) and what should have been sent?

**Comment by highfredo** [comment]
![image](https://github.com/WDaan/VueTorrent/assets/5951524/5e30fdeb-72c2-464a-9728-67c4294224d1)

This PR https://github.com/WDaan/VueTorrent/pull/1082 changes the unit from bytes to KiBps which is fine but forgot to change Alternative Rate Limits

**Comment by Larsluph** [comment]
Ok so only alternative speed limits are using B/s but displaying unit as kB/s, thanks for the feedback!

**Comment by WDaan** [comment]
Solved with vue3 rewrite?
