### ISSUE TITLE
[Feature Request] register and work with magnet link handler

### ISSUE THREAD

**Issue by rix1337** [WDaan/VueTorrent#111]
The original web UI has a function to automatically register mailto links to qBittorrent.

Once registered, your browser will try to redirect to qbittorrent appending `/#/download/` + the URL encoded magnet link:
![grafik](https://user-images.githubusercontent.com/9930448/105580256-96657180-5d8b-11eb-9145-ffc441b62708.png)

![grafik](https://user-images.githubusercontent.com/9930448/105580287-c6ad1000-5d8b-11eb-8849-7d003c054628.png)

Feature Request:
* Allow vuetorrent to work with the qbittorrent magnet link handler
* Offer a button in vuetorrent to register the current UI for the magnet link handler

Should be straightforward and is the only major flaw with this web interface! 😁

**Comment by rix1337** [comment]
Nice!

Only thing missing is the ability to register magnet links for qBittorent (which is available in the original web UI)
@WDaan

**Comment by WDaan** [comment]
I don't know how it works, so if you don't mind me asking....
Don't you need to press that button once, and only once to enable it?  
If that's the case, I rather not add it because I don't really know where to put it 😅

**Comment by rix1337** [comment]
Please consider doint this. The register Function ist straigthforward:
https://github.com/qbittorrent/qBittorrent/blob/4259b4571ceb962a778a0bdce803c6e7600e726c/src/webui/www/private/scripts/client.js#L1156

Since the original WebUI is not working on mobile clients (none of my mobile browser work properly without using a third party WebUI like VueTorrent, there is no way for me to register the link handler on mobile.

You should be able to copy/paste the registerMagnetHandler() Block and the button could easily placed somewhere here:
![grafik](https://user-images.githubusercontent.com/9930448/106390481-fa6de280-63e8-11eb-97f3-2a65f00c2f8a.png)

**Comment by m4ximuel** [comment]
It works successfully in my personal test build. I will add it in a future build.

**Comment by mattdillon100** [comment]
I've been trying to find this feature in the latest build. Was this ever released?

**Comment by WDaan** [comment]
Not sure on the status of this. Would have to test this out.

Don't think that latest fix ever made it in.

**Comment by reyqn** [comment]
Does this mean on android when using vuetorrent as a pwa magnets could be opened by default in vuetorrent?

**Comment by t9999clint** [comment]
It handles the magnet links just fine. I just have to turn off vuetorrent, register the qbittorrent webui as the magnet handler and turn vuetorrent back on.
All that's missing is the button for it so I don't have to switch between the two themes.

**Comment by VCTGomes** [comment]
I can't use it. Unfortunately I'm getting "Unable to register handler, context isn't secured!" error.

I'm using reverse proxy to open it with a valid certificate

**Comment by Larsluph** [comment]
In that case, that's not a VueTorrent issue. The secure context is a security requirement enforced by your browser. We don't have any control on this.

https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#when_is_a_context_considered_secure
