### ISSUE TITLE
Add new torrent select categories displays indexes instead names

### ISSUE THREAD

**Issue by IevgenSobko** [WDaan/VueTorrent#113]
Add new torrent select categories displays indexes instead names
![2021-01-23__18-01-29](https://user-images.githubusercontent.com/14232100/105607035-3976b500-5da5-11eb-8045-d6df7aa45249.png)

**Comment by Kira9204** [comment]
+1 I noticed this as well in 0.5.1. The index number will be the category (a number) if you pick one.
If works fine to assign categories to already existing torrents tho.
