### ISSUE TITLE
Ability to view seeders details

### ISSUE THREAD

**Issue by hl2guide** [WDaan/VueTorrent#1132]
Please add the ability to view seeders details.

**Comment by WDaan** [comment]
Any details you're missing? Please check the vue3 version.

**Comment by hl2guide** [comment]
> Any details you're missing? Please check the vue3 version.

Where do I find the vue3 version?

**Comment by Larsluph** [comment]
#1129

**Comment by Larsluph** [comment]
Outdated, switch to v2
