### ISSUE TITLE
Unable to login with a password manager from a mobile device

### ISSUE THREAD

**Issue by Hukuma1** [WDaan/VueTorrent#1134]
There's a related (maybe) issue here: https://github.com/WDaan/VueTorrent/issues/474

When logging in using a desktop browser, using my password manager (Bitwarden) it works fine.

When using iOS Chrome on my iPhone, it populates the fields (login and password) but then tells me the login is incorrect. I have to manually click on the populated password field again and let Bitwarden fill it in again. Then it will allow me to login as normal.

This is with the Chrome browser on iOS. Using Safari it does not work, period. I would have to re-type both the username and password it seems.

iOS 15.4.1 if it matters.

**Comment by Hukuma1** [comment]
I use the Hotio Docker Container (cr.hotio.dev/hotio/qbittorrent:latest). Any way to inject the vue3 branch into there for testing this? Not too advanced with Docker.

Or can I simply try mapping the `/app/vuetorrent/public` in that container to a local folder with a downloaded copy of the vue3 branch? (Sorry, not too advanced with Docker Compose yet hah)

**Comment by Hukuma1** [comment]
Nm figured it out. Just mapped it.

Vue3 branch Bitwarden on iOS only inputs in the username and the password field is blank

**Comment by WDaan** [comment]
Works fine on iOS with keychain fyi.

It does not always login however, sometimes you still need to push the login button

**Comment by Hukuma1** [comment]
Weird. I have a bunch of username/password webUIs I login to and VueTorrent is the only one having this issue with Bitwarden it seems. I do not use keychain, as I want it to pull my login info from my own private server instead of being on-device.

Let me know if there's any other log or info I can submit to help further debug this?

**Comment by Hukuma1** [comment]
Seems Safari does work just fine with Bitwarden. So it's probably some weird Chrome on iOS issue. I'll close this out unless someone wanted to poke around with it.
