### ISSUE TITLE
Alternative rate limits displayed in bytes instead of KiB

### ISSUE THREAD

**Issue by maxiwheat** [WDaan/VueTorrent#1144]
I have my alternative speeds set to 2048 KiB / 30720 KiB, but it is displayed in bytes instead (2097152 / 31457280)

Global rate limits are displayed correctly

![image](https://github.com/WDaan/VueTorrent/assets/1927334/95a436f6-065d-4c56-999a-b4a784dfc3d9)

**Comment by WDaan** [comment]
Related #1109?

**Comment by maxiwheat** [comment]
> Related #1109?

Yup, I searched the opened issues before posting, but since this is closed I didn't find it. Is it fixed somewhere ? I have installed 1.8.0 and this is still happening.

**Comment by WDaan** [comment]
Resolved in the vue3 version. You can install it from the dedicated nightly branch. Find more info in discussion.

We will switch over soon, still some small things to work out. 

We're kind of in a weird in between state right now
