### ISSUE TITLE
[Bug] Math.floor instead of Math.round for availability

### ISSUE THREAD

**Issue by eliasbenb** [WDaan/VueTorrent#1150]
My torrent has been stuck on 99.9% for a few days now, which sucks. I looked at the torrent's info, though, and saw that it had an availability of 1. So what gives? Well, after checking the availability directly from qBittorrent's API I found that the actual availability is 0.9990237216278103, but VueTorrent rounds the value to 1.

Instead of rounding the availability up/down, I propose always rounding down to get a more accurate reading.

So, [this line of code](https://github.com/WDaan/VueTorrent/blob/b81670d80c4709664c302b4fabcb55761d776aed/src/models/Torrent.ts#L72) would become: `this.availability = Math.floor(data.availability * 100) / 100`

The method of rounding only really matters in the case I mentioned above, where the availability is in the range (0.995, 1], so it would be equally as good to write a special case for that range and not change the rounding method.

**Comment by Larsluph** [comment]
Thanks for the feedback ! If you want to see the change, you'll have to switch to the vue3 rewrite.
You can install it from the dedicated nightly branch. More info [here](https://github.com/WDaan/VueTorrent/discussions/1129)
