### ISSUE TITLE
[nightly-release-vue3] No possibility to configure the torrent card on mobile phone

### ISSUE THREAD

**Issue by simonbcn** [WDaan/VueTorrent#1154]
No possibility to configure the torrent card on mobile phone.
There are only the options to change the desktop ones.

**Comment by simonbcn** [comment]
I think this is not the problem. I think the problem is the literal one in the `torrent card` section: `.... on desktop`.
From what I have tested it seems that in Vue3 the mobile and desktop settings are different, is this the case?

**Comment by Larsluph** [comment]
Both are controlled by the same data because we assume that one instance on always used on the same type of device. Wording is only a minor issue, will fix that ASAP but the behavior should be correct...
