### ISSUE TITLE
RSS Rules "Save to" field is not populated with categorie's default location

### ISSUE THREAD

**Issue by mks-h** [WDaan/VueTorrent#1172]
Unlike in the "Add a new torrent" window, in the "Create new rule" (RSS) window, after assigning it a category, the "Save to" field is not populated with the default download directory from the specified category.

**Comment by Larsluph** [comment]
Yeah that's normal, it's because when not specified, qbit will use the category location. If you specify something and change the category's location, it won't be reflected in the rule.

**Comment by mks-h** [comment]
> use the category location (or the default save path when no category is specified)

It doesn't. There is no category specified by default, so the path stays empty. Once I do specify the category (but not even touch the path), the path is still empy.

**Comment by Larsluph** [comment]
Yes I know that's how rules work (you can try with the default UI). The field is blank but when the rule is executed, the category's path is used.

**Comment by mks-h** [comment]
I see, that's a little confusing. How would I put a subfolder to that category's path then?

**Comment by Larsluph** [comment]
You will have to override the value manually. This kind of feature is qBittorrent's fault, we're only a WebUI sitting on top of a predefined behaviour. We don't have any control over qbit's flow of events.

**Comment by mks-h** [comment]
Alrighty, thanks then
