### ISSUE TITLE
[Feature Request] Torrent Content: bulk edit to check/uncheck files

### ISSUE THREAD

**Issue by tainewoo** [WDaan/VueTorrent#1175]
[Feature Request] Torrent Content: bulk edit to check/uncheck files
Currently all the files are all listed there. And if we only want to download some of the files, we have to check/uncheck the files one by one.
Multiple choose and Bulk edit would help a lot.

If we can filter them by name and size https://github.com/WDaan/VueTorrent/issues/1173,  sort them by name and size https://github.com/WDaan/VueTorrent/issues/1174, and then bulk edit to check/uncheck, that would be more easier for users to organize the downloading/uploading.

**Comment by WDaan** [comment]
Same as https://github.com/WDaan/VueTorrent/issues/894?

**Comment by tainewoo** [comment]
Oh that might be the same request.
Normally on desktop, we can use left click and then shift + left click to select multiple items before perform actions.
