### ISSUE TITLE
[UI] Show "Downloaded / Size" instead of just "Size"

### ISSUE THREAD

**Issue by Darkflicker** [WDaan/VueTorrent#118]
Hi, the WebUI looks amazing after the last update. I have a request; the torrent description should show both downloaded and the total size like it shows on mobile devices.

![Screenshot 2021-01-25 172958](https://user-images.githubusercontent.com/26320874/105704835-6528a500-5f35-11eb-8f50-283ebba5c0e2.jpg)

![Screenshot_20210125-172709_Bromite](https://user-images.githubusercontent.com/26320874/105704889-7671b180-5f35-11eb-8007-917b86edfc32.png)

Also, the font for Category and Status in the sidebar is a tad too big and it cuts off.

![Screenshot 2021-01-25 174014](https://user-images.githubusercontent.com/26320874/105704981-930de980-5f35-11eb-9c4b-9cf837a8240a.jpg)

Thanks.

**Comment by WDaan** [comment]
Hi! Thanks for the kind words!

The cutoff has been fixed :)

I will make another property for the amount allready downloaded.
The properties are configurable, so you can arrange & disable/enable them however you like.

**Comment by IevgenSobko** [comment]
@WDaan are you sure it got pushed into 0.5.4 release?
I don't see the downloaded property in torrents table nor in the configuration section

**Comment by WDaan** [comment]
It is there! It's just a caching issue...if you clear the data for VueTorrent & refresh...it should be there.

**Comment by IevgenSobko** [comment]
Isn't it going also to remove saved locations when adding torrent?
I would like to avoid this because have a long list of folders already saved which saves some time for me.

**Comment by WDaan** [comment]
![image](https://user-images.githubusercontent.com/25707052/105995668-9a560400-60a9-11eb-8aef-4e01ce8b4ab7.png)

This is what you need to clear, it doesn't affect the save locations :wink: 

VueTorrent uses localstorage for saving settings, but is has some issues with mutating objects.
I should convert it to use Web SQL at some point, but haven't gotten to it yet.

**Comment by IevgenSobko** [comment]
Managed to see new properties in the incognito mode. But cleaning local storage didn't help me for some reason. Going to investigate this.
Thank you.

**Comment by WDaan** [comment]
You need to be very fast, because it's rewritten very frequently.
Clear & immediatly refresh, it's a bit tricky... took me a few tries as well.

I will put a localstorage refactor on the To-Do list

**Comment by IevgenSobko** [comment]
I think disabling JavaScript removing and then enabling might help to clear local storage
https://developers.google.com/web/tools/chrome-devtools/javascript/disable
