### ISSUE TITLE
The sidebar cannot be hidden/closed after opening it

### ISSUE THREAD

**Issue by kazik56** [WDaan/VueTorrent#12]
The sidebar cannot be hidden after entering it - only reloading a page helps (hides it). Clicking anywhere doesn't help either.

**Comment by kazik56** [comment]
Noticed that the issue only exists on devices with bigger viewport.

**Comment by WDaan** [comment]
Yes, I've noticed. It appeared when upgrading from Vuetify 1 to 2.
Haven't found a clean way to fix it yet.

**Comment by WDaan** [comment]
Fixed! They buttons will now stay shown... I've also disabled auto showing/hiding on resize, so it will stay the way you wanted it too.
