### ISSUE TITLE
Unnecessary mutations in vuex state propagated to localStorage

### ISSUE THREAD

**Issue by colthreepv** [WDaan/VueTorrent#120]
I noticed this kind of weird behaviour on Vuex
![vuetorrent_sort_bug](https://user-images.githubusercontent.com/2657230/105790472-bad86e00-5f84-11eb-950e-11a7b86fccf1.gif)

It mutates twice every call to `/api/v2/torrents/info`  
It does not provoke any bug for me, but I found it weird, so I am posting this 😃

**Comment by WDaan** [comment]
Thanks for letting me know!
However, I can't seem to reproduce this.
You think it might be relatd to #121? Some cached code somwhere?
Or I might have accidentally fixed it without noticing 😅

**Comment by colthreepv** [comment]
I have been extra careful about cache exactly because I have the aforementioned issue

You are right about reproducing the problematic, I am not sure how to achieve that. as this is a running instance of qbittorrent.
Will report back if I find a way to create reproducible container

**Comment by WDaan** [comment]
I would like to close this for now, as I haven't seen it occur... nor has anyone else mentioned this issue before
