### ISSUE TITLE
Editing Per-Torrent Share Limit Returns HTTP 400 on qBittorrent 4.6.0

### ISSUE THREAD

**Issue by Xewdy444** [WDaan/VueTorrent#1204]
## Environment
- qBittorrent Version: 4.6.0
- VueTorrent Version: 1.8.0

---

Right clicking on a torrent and going to `Set limit` > `Share` and clicking save fails on qBittorrent 4.6.0 due to the request missing a new parameter called `inactiveSeedingTimeLimit`. 

![image](https://github.com/WDaan/VueTorrent/assets/95155966/65caf553-d57e-4b9d-9e27-0e783f5ccbc7)

Current request payload:
![image](https://github.com/WDaan/VueTorrent/assets/95155966/d2ed6d7e-e52a-41ba-8658-4b8b4f7e75e3)

New request payload in qBittorrent 4.6.0:
![image](https://github.com/WDaan/VueTorrent/assets/95155966/056716ba-484e-412e-9cc0-eebe844c414f)

**Comment by WDaan** [comment]
Hmmm I think we can just add the property, I think it's just ignored by older qbit version anyway.

**Comment by Peuuuur-Noel** [comment]
This error is following a new feature ([Add option to stop seeding when torrent has been inactive](https://github.com/qbittorrent/qBittorrent/pull/19294)) in qBittorrent 4.6.0.
Related commit https://github.com/qbittorrent/qBittorrent/commit/35e18498d9bde2292f4c0be793f0870385e54770.

**Comment by mjolnir870** [comment]
I'm sorry if I'm missing something obvious, but in Vue3, where is this menu? I don't see a way to change share limits anymore in VueTorrent 2.0.1.

**Comment by mjolnir870** [comment]
Actuall, I just checked my version and I had updated after the notification of 2.1.0, but it seems like the release failed and I'm still on 2.0.0
https://github.com/WDaan/VueTorrent/actions/runs/6768332057/job/18392938179

**Comment by Larsluph** [comment]
Yeah CI is kinda messed up. Switch to nightly if you want to test it out right now. You can change the share limit in the right click menu.

**Comment by Peuuuur-Noel** [comment]
@Larsluph thx for this update.
Please, can you also add this to the global seeding limits in settings?
Like in the qBittorrent WebUI: https://user-images.githubusercontent.com/5301279/252171346-bdbd5301-491b-453d-8984-ec4d3404dd67.png

**Comment by Larsluph** [comment]
Will look into that when everything's working again 🚀

**Comment by steakhutzeee** [comment]
To see these changes, if not using git the only solution is to wait for a new release to be published here for download?

**Comment by Larsluph** [comment]
2.1.0 contains the share limit dialog, global settings still isn't available
