### ISSUE TITLE
Make RSS article ID clickable

### ISSUE THREAD

**Issue by h31p** [WDaan/VueTorrent#1232]
![brave_2023-11-04_14-23-13](https://github.com/WDaan/VueTorrent/assets/40469877/6572c29a-eae1-45e8-aed8-88b4f930d99c)

regarding RSS articles list, can you please make ID column clickable - with the same href, in a new target window?
it usually contains link to original torrent release (with descriptions, screenshots, samples etc.), and for now it's neither clickable, nor even copyable.
thanks in advance!

**Comment by Larsluph** [comment]
Outdated, switch to v2
