### ISSUE TITLE
There is no Russian localization.

### ISSUE THREAD

**Issue by bulletproof2k** [WDaan/VueTorrent#1234]
There is no Russian localization in this version.

**Comment by Larsluph** [comment]
Yeah, in fact, we don't speak russian at all. We are working on a solution to allow users to translate the app easily but it's still a WIP.
You can still contribute the old way for now, everything is detailed in the README.

**Comment by bulletproof2k** [comment]
> Yeah, in fact, we don't speak russian at all. We are working on a solution to allow users to translate the app easily but it's still a WIP. You can still contribute the old way for now, everything is detailed in the README.

Do not delete the previous version from the releases, I put it back for a known reason.
