### ISSUE TITLE
Big Gay Text

### ISSUE THREAD

**Issue by hereCOMESlappy** [WDaan/VueTorrent#1236]
Hello, I just updated to v2 and it is using tyhis really big gay font that is making my torrent cards have big gay writing.

Here is an example:

![image](https://github.com/WDaan/VueTorrent/assets/44932282/341e4914-4fc2-400d-b648-5b83924a4efd)

I circled it in red because I was worried that you might miss it.......

Is it possible to change the font or at least reduce the size of this to something less gay?

Thank you

**Comment by WDaan** [comment]
I won't even consider issues unless posed in a profesionnal and respectfull manner.
