### ISSUE TITLE
Speed text still wraps

### ISSUE THREAD

**Issue by IevgenSobko** [WDaan/VueTorrent#124]
Speed text still wraps
Also unit names too small for laptop screen I suggest to increase them to values of Total Download/Upload fields.
Maybe it is good idea to use not light version of font for units.
![2021-01-26__12-19-59](https://user-images.githubusercontent.com/14232100/106102995-e99f4180-6148-11eb-9123-2b375f52c03b.png)

**Comment by WDaan** [comment]
Someone suggested I use light version, I'll try with regular.

As for font size, I can't increase it any more because it cant fit in the space...so @CoreyVidal's design would need a little re-thinking

**Comment by agneevX** [comment]
I think the earlier design was better, and that version should be worked upon. 

The chevrons should be aligned with the text.

**Comment by WDaan** [comment]
Sure, but I cant increase the font without it cutting off 😅

**Comment by IevgenSobko** [comment]
I also prefer the previous design. For me, it felt much better.
I have 2 ideas.
* How about trying to do this the same way as Sessions Stats with 2 rows.
* Or make 2 circles with top row icon, middle speed, and bottom units.

**Comment by agneevX** [comment]
I'm not entirely sure why a redesign was necessary. It's perfectly fine for me the unit and the chevron to move around. 

You can revert to the earlier version, round to 0 decimal places for unit in `B/s`, `KiB/s`, 2 decimal places for `MiB/s` and over.
