### ISSUE TITLE
[Bug] Torrent card settings reset after reload

### ISSUE THREAD

**Issue by SinTan1729** [WDaan/VueTorrent#1244]
As is mentioned in the title, any changed made to the torrent card is reset on reload. It just goes back to the default settings. I have VueTorrent 2.0.0 running with qBittorrent 4.6.0 on a AlmaLinux 9.2 machine running on 5.14.0-284.30.1.el9_2.x86_64 kernel.

**Comment by maxiwheat** [comment]
I experience the same with qBT 4.5.5, going back to 1.8.0 in the meantime

**Comment by Resserene** [comment]
Facing the same issue. VueTorrent 2.0.0 qBittorrent 4.6.0 running in unRAID.
