### ISSUE TITLE
[Bug] General Settings “Current Version” display incorrectly 

### ISSUE THREAD

**Issue by bolucat** [WDaan/VueTorrent#1247]
One hour ago, I switched to the latest release [v2.0.1](https://github.com/WDaan/VueTorrent/releases/tag/v2.0.1), but after I cleared the browser cache, the “Current Version” in general settings still shows “2.0.0”. I opened a private window to make sure I don't use the stale browser cache, but nothing changes. 

So I searched the string “2.0.1” around all the files in “public” directory, but there's nothing. So I searched the string “2.0.0” and found it exits in `public/assets/Settings-8f4a6f00.js`
```bash
......
g=Vt(()=>t.value?"2.0.0":s.value?"DEV":null)
......
```
So maybe there's a bug that the version value in `package.json` didn't pass correctly to the final JS files

**Comment by Larsluph** [comment]
That seems to be a CI issue. By checking the logs it's releasing the commit just before the version bump.
