### ISSUE TITLE
Big blury gay text

### ISSUE THREAD

**Issue by hereCOMESlappy** [WDaan/VueTorrent#1249]
Hello

Ever since updating to 2.0, there is big gay blury text on my torrent card. It seems like the font is of poor quality? It's really big andf blury. All the other text is sharp but not this massive big gay text, I have circled it in red.

Any chance we can select another font that isn't completely gay? and can we control the size of it? There is just no need for it to be so big.

![image](https://github.com/WDaan/VueTorrent/assets/44932282/d1ba6920-b267-4bc1-82c9-1aec55677632)

**Comment by WDaan** [comment]
I won't even consider an issue if not posed in a professional and respectfull way.
This is the second time you've opened this, first time I just deleted it.
