### ISSUE TITLE
Sock5 proxy with vue 

### ISSUE THREAD

**Issue by Dautrip** [WDaan/VueTorrent#1260]
Hey Hi,

Starting today, when I use vue UI, sock5 proxy is no longer used.

**Comment by Larsluph** [comment]
I'm not sure what you mean. Can you be more specific about the problem?

**Comment by Dautrip** [comment]
Thanks for answering so quickly.

as soon as I choose web UI vue, it’s like my setting regarding sock5 proxy are not registered. According to torrent leak test my real IP address is showing.
Hope this is specific enough.

**Comment by Larsluph** [comment]
VueTorrent is only a WebUI for qBittorrent, if something isn't working inside the app, we can't do anything unfortunately.

Is the proxy not working because VueTorrent didn't send the request correctly to qbit ? Or is it a qbit issue ?
Are you already on the latest version?
