### ISSUE TITLE
Auto dark/light based on OS

### ISSUE THREAD

**Issue by bilogic** [WDaan/VueTorrent#1261]
Can have a setting to make the theme auto adjust based on the OS settings?

**Comment by 2fst4u** [comment]
This is already there isn't it?

![Screenshot_20231106_175545_Firefox.jpg](https://github.com/WDaan/VueTorrent/assets/15257926/7e8d084b-94fa-4309-bcfc-05f9638dafea)

Maybe a V2 addition though.

**Comment by bilogic** [comment]
thanks let me check, i'm using it via homeassistant add on.
