### ISSUE TITLE
Sidebar automatically opening on load on V2 

### ISSUE THREAD

**Issue by 2fst4u** [WDaan/VueTorrent#1263]
On Firefox mobile the side menu bar is automatically opening when loading the web app.

(Sorry for the issue spam. I really like the UI and just want to highlight the bugs for tracking)

**Comment by Larsluph** [comment]
Don't worry about opening issues, that's great!
If you check in the settings, you should find a checkbox to disable the sidebar opening on startup.

**Comment by 2fst4u** [comment]
Awkward because of #1262 haha

**Comment by Larsluph** [comment]
Why is that?

**Comment by 2fst4u** [comment]
Because changing the setting wouldn't get saved, therefore it wouldn't solve it haha.

All good though if that's fixed too cheers.
