### ISSUE TITLE
Tweak State colors for light and dark mode

### ISSUE THREAD

**Issue by agneevX** [WDaan/VueTorrent#127]
I think the state colors should be looked at closely and tweaked.

E.g. `Paused` has a hex color of #CFD8DC (![](https://dummyimage.com/30x10/CFD8DC&amp;text=+)) which is very illegible under the milky white background. 

Light mode and dark mode should each have a separate set of colors, in the interest of [accessibility](https://material.io/design/color/dark-theme.html#ui-application).

@WDaan if you can list the colors' hex, we can come up with a solution to this!

---

From below:

| State | Current | Light (new)  | Dark (new)
|---|---|---|---|
| `done` | `#3cd1c2` (![](https://dummyimage.com/30x10/3cd1c2&amp;text=+))  |   |   |
| `downloading` | `#5bb974` (![](https://dummyimage.com/30x10/5bb974&amp;text=+)) |   |   |
| `failed`  | `#f83e70` (![](https://dummyimage.com/30x10/f83e70&amp;text=+)) |   |   |
| `paused`  | `#cfd8dc` (![](https://dummyimage.com/30x10/cfd8dc&amp;text=+)) |   |   |
| `queued`  | `#2e5eaa` (![](https://dummyimage.com/30x10/2e5eaa&amp;text=+)) |   |   |
| `seeding`  |  `#4ecde6` (![](https://dummyimage.com/30x10/4ecde6&amp;text=+))|   |   |
| `checking`  | `#ff7043` (![](https://dummyimage.com/30x10/ff7043&amp;text=+)) |   |   |
| `stalled`  | `#4ADE80` (![](https://dummyimage.com/30x10/4ADE80&amp;text=+)) |   |   |
| `metadata`  | `#7e57c2` (![](https://dummyimage.com/30x10/7e57c2&amp;text=+)) |   |   |
| `moving`  | `#ffaa2c` (![](https://dummyimage.com/30x10/ffaa2c&amp;text=+)) |   |   |

**Comment by WDaan** [comment]
these are the currently used colors in (src/styles/colors.scss)

```
$torrent-done: #3cd1c2;
$torrent-downloading: #5bb974;
$torrent-fail: #f83e70;
$torrent-paused: #cfd8dc;
$torrent-queued: #2e5eaa;
$torrent-seeding: #4ecde6;
$torrent-checking: #ff7043;
$torrent-stalled: #4ADE80;
$torrent-metadata: #7e57c2;
$torrent-moving: #ffaa2c;
```
@CoreyVidal and I have allready talked about this, our solution was to use the colors that the Google messages app uses... these are the same for both light and darkmode

**Comment by agneevX** [comment]
> I would prefer it if the colors for both light & darkmode stay the same

Colors do not look the same as over a light background, on a dark background. Not only that, its far easier to _grasp_. More info here: https://material.io/design/color/dark-theme.html#ui-application

If you feel very strongly about this, we could change some of the colors like `paused`, so its legible.
