### ISSUE TITLE
Progress bars flicker

### ISSUE THREAD

**Issue by gordonjb** [WDaan/VueTorrent#1278]
Upgraded to `latest-release`, I see flickering of the progress bars.

Browser is Firefox on Win 11.

https://github.com/WDaan/VueTorrent/assets/2196521/dc1df23c-247a-4e60-8bed-3c18b28a65cd

**Comment by Larsluph** [comment]
Is it only happening when the progress bars are stripped?

**Comment by gordonjb** [comment]
It definitely seems more pronounced when there are striped bars on display, but I do also see it on pages with no bars. I tried to screen record this, but oddly it's not visible in the recording

**Comment by Larsluph** [comment]
Do you have extensions that can mess with the pages' elements?

**Comment by johnyb0y** [comment]
Firefox 119.01 on Win11, vueTorrent 2.0.0 and now 2.0.1 - I cannot reproduce this. No flickering for me.

**Comment by gordonjb** [comment]
> Do you have extensions that can mess with the pages' elements?
```
Bitwarden - Free Password Manager
GNOME Shell integration
Honey
Indie Wiki Buddy
Privacy Badger	extension
Reddit Enhancement Suite
SponsorBlock for YouTube - Skip Sponsorships
Tampermonkey
TinEye Reverse Image Search
Torrent Control
uBlock Origin
YouTube Screenshot
Amazon Assistant
Better TweetDeck
DownThemAll!
Firefox Translations
```

tried an incognito window and it's gone, with just some animation loop issues. don't see it in Chrome at all

Tried disabling all my extensions, still see it 🤷

May just be a me issue at this point

**Comment by gordonjb** [comment]
Disabled hardware acceleration in Firefox and the issue is gone.
