### ISSUE TITLE
Priority order incorrect

### ISSUE THREAD

**Issue by Darkflicker** [WDaan/VueTorrent#128]
Set Priority does not work in 0.5.4.

**Comment by WDaan** [comment]
It does work! (I compared it with default WebUI side-by-side)
But the QBit api doesn't return them in the correct order for some reason.

**Comment by Darkflicker** [comment]
It worked flawlessly in the previous versions. I even cleared the cache and tried different browsers but it does nothing for some reason. I tried to change priorities with qbit native UI side-by-side but it's the same.

**Comment by WDaan** [comment]
For me it does work, but it keeps allready downloaded torrents always at the top for some reason.
I'm having a hard time figuring out what's wrong 😅

**Comment by WDaan** [comment]
Solved by setting priority as the sort option
