### ISSUE TITLE
Log view is stuck on logID sort

### ISSUE THREAD

**Issue by vRobM** [WDaan/VueTorrent#1282]
Unable to change to any other option, makes it hard to find recent logs to troubleshoot.

**Comment by Larsluph** [comment]
Global sorting system is currently being reworked. This one is bound to nothing for now. By default, they are sorted in ascending order by ID, so you might find recent logs starting from the last page.

**Comment by vRobM** [comment]
Please adjust the default sort order so recent logs are on the first page.
