### ISSUE TITLE
[Bug] "Show info" not functional on mobile

### ISSUE THREAD

**Issue by moracha** [WDaan/VueTorrent#1284]
Using latest update 2.1.0, I'm not able to access the "Show info" link on my Android mobile using Firefox 119.1.0. Check to see if you can reproduce this.

![Screenshot_20231108_173002_Firefox](https://github.com/WDaan/VueTorrent/assets/24765601/0f6b4407-7626-4c9b-a092-aa6e638cc368)

**Comment by WDaan** [comment]
#1277

Please comment there
