### ISSUE TITLE
Torrent name/title size

### ISSUE THREAD

**Issue by nickelslol** [WDaan/VueTorrent#1288]
I just got round to updating from 1.8 to latest

is there anyway that I’m missing to change the size of torrent names? 
some of mine are taking up 3 lines on mobile, it’s horrible. 
also tags, categories and state are far too big in my opinion

sorry if this is mentioned before I did search

**Comment by Octopus1348** [comment]
There was an issue about this before but it got deleted, and umm...


![Image_20231105_142558](https://github.com/WDaan/VueTorrent/assets/105970916/bdb65692-abc6-4926-85c9-0ba37836b5b8)

**Comment by nickelslol** [comment]
I’m not surprised it was deleted and didn’t do a search for something so silly

hopefully mine will be received better and considered

**Comment by SinTan1729** [comment]
I agree. The older layout was better for mobiles. I guess if the font size could be adjusted, and if the tag/category were hidden (at least on mobile) when none are chosen, it'd take up less space.

**Comment by nickelslol** [comment]
My ideal world the problem would be solved with the ability for the user to choose the size of the font and tag/category size
