### ISSUE TITLE
Building from source

### ISSUE THREAD

**Issue by skozharinov** [WDaan/VueTorrent#1289]
Builds from source are no longer possible ( = unusable) due to a lack of actual locale files in the repository

**Comment by Larsluph** [comment]
Translation workflow is being reworked. We'll soon be able to receive translation updates from Tolgee directly. In the meantime, you can find the latest and nightly release which contains respectively the latest release and the latest commit built with the locales data.

**Comment by WDaan** [comment]
Could we keep the English one in the repo so local dev is not impacted? 🤔

Translations file resolving should also be dynamic as newly added languages will still not be picked up dynamically.

**Comment by Larsluph** [comment]
We can as a reference but it may be outdated since Tolgee is the new trust source.

**Comment by WDaan** [comment]
Yes, it's not ideal. I'm just trying to get local dev back up without a hassle. I don't think we change the actual keys that often? So just saving an export every once in a while is fine.

Alternatively we can commit the exported locales? 🤔

**Comment by Larsluph** [comment]
Yes I'm thinking of committing translation updates to the repo but I still need to figure out how to integrate that into the current CI.

**Comment by WDaan** [comment]
Probably just the auto commit action, if you don't provide a PAT it won't trigger subsequent actions.

**Comment by Larsluph** [comment]
That might be a way to do it indeed.
