### ISSUE TITLE
Mobile View -Holding down on the options of one torrent affects all torrents on the client.

### ISSUE THREAD

**Issue by ckallungal** [WDaan/VueTorrent#1290]
Hello

When I hold down on a torrent to pause or recheck it starts the selected process on all torrents. I ran into this issue by accident when I tried to recheck one specific torrent which started the rechecking process on all 2000+ torrents on my client.  
![Vue2 1 0](https://github.com/WDaan/VueTorrent/assets/46407945/f057e40d-011a-457c-9984-1a45e5904064)

I installed 1.8.0 on another client and tested it and it only makes the change on the selected torrent. 
![Vue1 8 0](https://github.com/WDaan/VueTorrent/assets/46407945/6758b239-81ee-49c4-a888-aa10a2f3bbdd)

Not sure if this is by design due to the major update to 2.*, but are you guys able to change the functionality back to how it was in vue 1.8.0? 

Thank You

**Comment by Larsluph** [comment]
This is obviously not intended. I already noticed some weird things happening with the right click menu, we still need to investigate the exact issue.

**Comment by Larsluph** [comment]
Are you using a PWA or just a classic browser tab?
