### ISSUE TITLE
Can the magnet dialog open automatically?

### ISSUE THREAD

**Issue by bilogic** [WDaan/VueTorrent#1292]
## Magnet dialog not opened
![image](https://github.com/WDaan/VueTorrent/assets/946010/967fe4f4-c659-4f43-82b4-f40feab8b8bf)

## Magnet dialog opened
![image](https://github.com/WDaan/VueTorrent/assets/946010/09e62d66-0db5-48b4-8d33-82298d36e850)

The magnet dialog used to open by default, it now stays hidden at the bottom and is quite easy to miss. Can it open by default?

**Comment by Larsluph** [comment]
Do you mean that it doesn't open by default using the magnet handler?

**Comment by bilogic** [comment]
> Do you mean that it doesn't open by default using the magnet handler?

Yes. It used to open automatically, now it only shows `1 torrent awaiting upload`, I need to click on the carot to the right to expand it.
