### ISSUE TITLE
[Bug?] Torrent Content: Checkable boxes not present

### ISSUE THREAD

**Issue by moracha** [WDaan/VueTorrent#1297]
Hi again guys,

Y'all have been great and quickly on top of feedback with the new release so major kudos for that. So I'm not sure if I'm being an idiot or not here but I can't seem to find the checkboxes to customize which parts of a torrent I want to download before starting the torrent. Like in this case I'm trying to download season 5 but I don't see the checkboxes that were normally present to select the parts I need. This is with desktop Firefox.

![2023-11-11_14-02-27](https://github.com/WDaan/VueTorrent/assets/24765601/070d456c-a3cb-48f5-adcb-26e04859a905)

**Comment by Larsluph** [comment]
Checkboxes have been removed in prevision of a future update to handle multi-selection further. You can just click on any file to edit the selection.

**Comment by Larsluph** [comment]
However, folders can't be selected, I think it is a vuetify bug. We still haven't taken the time to look into that. In the mean time, you'll have to deselect every file one by one. Sorry for the inconvenience 😅

**Comment by moracha** [comment]
Ah I see now clicking on it unselects it and shows [ Unwanted ]. It's annoying but at least it's a solution for now.😁
