### ISSUE TITLE
[Improvement] How about opening torrents info on double click

### ISSUE THREAD

**Issue by IevgenSobko** [WDaan/VueTorrent#130]
It irritates me that when I just browsing(scrolling) and clicking on a torrent card it opens the info modal.
How about opening torrents info on double click?
I tested it on my local fork and I like how it works.
Now I would like to hear other's opinions on that.

**Comment by WDaan** [comment]
Funny thing is...long ago, it worked like that.
But iirc it was changed in favor of selecting torrent....but there's a dedicated select mode now
