### ISSUE TITLE
Variables using name instead of value in interface

### ISSUE THREAD

**Issue by InconspicuousAtom** [WDaan/VueTorrent#1300]
After updating, VueTorrent is using lengthy strings to describe most things on the interface.
![image](https://github.com/WDaan/VueTorrent/assets/142955871/bda23e26-7139-4447-b373-fa8fd4109235)

VueTorrent Version: 2.1.1
Device: Chrome, Brave, Safari, everything I've checked
qbittorrent is installed in a docker container, and the theme is applied using `DOCKER_MODS=ghcr.io/gabe565/linuxserver-mod-vuetorrent` on the container, which has worked wonderfully in the past.

**Comment by InconspicuousAtom** [comment]
I am a silly goose. After browsing the wiki, I found the recommended docker mod is `DOCKER_MODS=arafatamim/linuxserver-io-mod-vuetorrent` which looks great. Apologies for any trouble!

**Comment by gabe565** [comment]
@InconspicuousAtom My Docker mod is newer than arafatamim's (see [here](https://github.com/gabe565/linuxserver-mod-vuetorrent/#linuxserverio-vuetorrent-mod) for the differences). Either one should work, but it seems like a recent update to VueTorrent broke something in my mod. I'll release a fix! 🙂

**Comment by gabe565** [comment]
@InconspicuousAtom This has been fixed in my mod! See gabe565/linuxserver-mod-vuetorrent#36 for more details.
