### ISSUE TITLE
Have you considered producing an app

### ISSUE THREAD

**Issue by github-ayio** [WDaan/VueTorrent#1302]
Hello author,  I want to know that have you considered producing an app plan? ios and android, it will provide a better experience, i think.

This project is amazing，You've been working hard！🌹

**Comment by brezinajn** [comment]
VueTorrent is already a PWA. You could, of course, wrap VueTorrent in a web view, but there would be no benefit to the user experience. You're correct that a native application could agruably provide a better experience. There are already some native solutions you can try.
https://play.google.com/store/apps/details?id=dev.yashgarg.qbit
https://play.google.com/store/apps/details?id=me.fengmlo.qbRemoteFree&hl=en&gl=US
