### ISSUE TITLE
Queued torrent cards use "torrent.properties.empty_tracker_domain" as Tracker

### ISSUE THREAD

**Issue by ryanpohlner** [WDaan/VueTorrent#1313]
If the Tracker property is enabled for cards, queued torrent cards will show "torrent.properties.empty_tracker_domain" as their tracker. If the torrent details are viewed, "(Untracked)" is shown instead. 

![tracker-card-bug](https://github.com/WDaan/VueTorrent/assets/26654233/a94d52d0-d454-4b72-bc36-122a01f400e3)

![tracker-detail](https://github.com/WDaan/VueTorrent/assets/26654233/1a9d4c0b-fe84-4cd6-ad8e-271002d14f9b)

Expected: Use "(Untracked)" or an empty value. This will help keep cards small in cases where a long tracker name causes other properties to spill over onto a second line.

**Comment by WDaan** [comment]
Probably a translation misalignment

**Comment by Larsluph** [comment]
Not sure how that happened as this string doesn't exists anywhere in the repo 🤔

**Comment by Larsluph** [comment]
I randomly stumbled upon the code that generates it and that string doesn't exist because it is a generic one 🤦. I added the missing key to Tolgee.
