### ISSUE TITLE
Chrome autocomplete download path doesn't work after 2.x.x

### ISSUE THREAD

**Issue by Antonio36996** [WDaan/VueTorrent#1327]
In previous versions I was able to autocomplete the download path with the values that chrome stores as form answers, now doesn't suggests written paths, I think it's because some attribute has changed in the html, and now chrome doesn't detect the field as something that has to be remembered, please fix it, as chrome syncs that data with all my devices, it is really useful when interacting with the web from a phone, because I don't remember the exact paths of everything.
¡Thank you!
![image](https://github.com/WDaan/VueTorrent/assets/66578721/47f7f360-dd9f-4fab-9548-45ec673d961b)

**Comment by Antonio36996** [comment]
Hi, I still can't autocomplete in the save path form, thanks!

**Comment by Larsluph** [comment]
2.3.0 added a custom history field to circumvent that issue on download path and save path
