### ISSUE TITLE
After setting the language to Chinese, the left status bar did not translate properly into Chinese

### ISSUE THREAD

**Issue by qa19971109** [WDaan/VueTorrent#1347]
After setting the language to Chinese, the left status bar did not translate properly into Chinese
![1](https://github.com/WDaan/VueTorrent/assets/36771198/d30fa08b-9b63-4184-a572-d2e5efefdea6)

**Comment by Larsluph** [comment]
Some parts of the UI are still hardcoded values, we need to do a checkup on every fields to add them to Tolgee. Moreover some keys are just not translated at all and we fall back to english if that's the case.
For the latter, you can go to our discord to help us translate the app as stated in the README!
