### ISSUE TITLE
If we want to have availability in percent we need to multiply the current value by 100

### ISSUE THREAD

**Issue by IevgenSobko** [WDaan/VueTorrent#135]
If we want to have availability in percent we need to multiply the current value by 100.
Availability 1 means that torrent is 100% available.
Availability 5 means that at least 5 seeders have it 100% available so we get 500%.
If we don't want percent we can use just numbers we currently have without a % sign.

**Comment by WDaan** [comment]
Oh I'm sorry, I did not know that's how it worked!
The API said ``Percentage of file pieces currently available``, so I assumed it was allright.

What would you suggest?

**Comment by IevgenSobko** [comment]
I guess it is ok to leave it as it is and just remove the percentage on a torrent card.
If I remember correctly all torrent clients do the same.
