### ISSUE TITLE
[Bug] Wrong port is announced to tracker after web ui is started

### ISSUE THREAD

**Issue by tainewoo** [WDaan/VueTorrent#1352]
### qBittorrent & operating system versions

qBittorrent-nox: 4.6.1 x64
Qt: 6
libtorrent: 2.0.9
OS: Linux (Synology DSM 7.2.1)

### What is the problem?

qBittorrent port setting:
port used for incoming connections: 63219
web ui port: 58085

qBittorrent announced port 63219 for some torrents, while it will announce port 58085 to some other torrents.
We can found the peer lists listed from the trackers, both 58085 and 63219 are listed, seeding different torrents.

This issue didn't occur on qBittorrent 4.5.5 with libtorrent v1.

### Steps to reproduce

1. seed some torrents for different trackers.
2. upgrade the qBittorrent to 4.6.1
3. start the qB.
4. Wait for some minutes, until the announce is completed.
5. Check the peer status for your account on the trackers. The tracker may list the peer listening on port 63219, this is the correct behavior.
6. start the web ui
7. Wait for some minutes, let some of the torrents announce again to trackers.
8. Check the peer status for your account on the trackers. You may found some torrents are listed as listening on 63219, while some others 58085.
9. Wait for some more minutes, until all the torrents are announced again after the web UI is started.
10. Check the peer status for your account on the trackers again
11. All the torrents listed as listening on port 58085 (actually this is the web ui port).

Notes: this issue occurs on 7 trackers I have, while 2 trackers I have will only list port 63219 in the record (maybe because these 2 trackers do not renew the value).
Notes: I have no idea if this issue is caused by qbittorrent or libtorrent or web ui, so I reported this issue again here.
Previously I reported it on qBittorrent here:
https://github.com/qbittorrent/qBittorrent/issues/20006

### Additional context

Tracker records:
![tracker_ports](https://github.com/qbittorrent/qBittorrent/assets/13391232/54cb82ce-2c7f-4924-9487-4bfaab825274)

Logs:
![qb_ports](https://github.com/qbittorrent/qBittorrent/assets/13391232/d3abf762-f9c7-4fc6-91bc-604a15351ac1)

**Comment by tainewoo** [comment]
I think it should not be VueTorrent's bug, because this issue can be reproduced with the original web UI.

**Comment by Larsluph** [comment]
haha yes i was just about to say that 😄
