### ISSUE TITLE
[Featuer Request] Hide category / tag chips when not set

### ISSUE THREAD

**Issue by github-ayio** [WDaan/VueTorrent#1358]
When there are not  set category and label, can we not display them?

**Comment by Larsluph** [comment]
If you talk about the filters, yes you can filter torrents having no categories and/or tags. Just use the "Uncategorized" and "Untagged" options.

**Comment by github-ayio** [comment]
> 如果您谈论过滤器，是的，您可以过滤没有类别和/或标签的种子。只需使用“未分类”和“未标记”选项即可。
I'm referring to this...
![Snipaste_2023-11-26_20-53-12](https://github.com/WDaan/VueTorrent/assets/23180747/d5a5e393-d4dc-48cd-8b71-8ad6e8e7f365)

**Comment by github-ayio** [comment]
> If you talk about the filters, yes you can filter torrents having no categories and/or tags. Just use the "Uncategorized" and "Untagged" options.

I'm referring to this...
![Snipaste_2023-11-26_20-53-12](https://github.com/WDaan/VueTorrent/assets/23180747/d5a5e393-d4dc-48cd-8b71-8ad6e8e7f365)

**Comment by Larsluph** [comment]
So you want to hide them if they aren't set to anything

**Comment by github-ayio** [comment]
> So you want to hide them if they aren't set to anything

bingo bingo!
