### ISSUE TITLE
[UI] Now that Torrent Info is opened on double click should single click select the torrent?

### ISSUE THREAD

**Issue by LukePrior** [WDaan/VueTorrent#136]
This is more of a suggestion than an issue but seeing how you've switched to double click for opening torrent info would it not now make sense for a single click to select. If you disagree please close the issue.

**Comment by WDaan** [comment]
It used to work exactly like that, single click to select and double to open...but people didnt like it for some reason. Then a dedicated the select-mode was introduced, and opening was switched to a single click because people suggested it was more convenient. 

Now @IevgenSobko suggested to make it double click to avoid accidental opening

I feel like we're running in circles here 😅

**Comment by IevgenSobko** [comment]
I have few suggestions on this.
When the select mode is not enabled we can remove this grays selection effect. It also bothered me, but not as much as accidental openings of info models.
But when selecting is enabled it should stay and selection should work not just when clicking checkbox but also on clicking torrent card(now it works only on clicking checkbox).
From a usability perspective, I guess it would be much better.
I often find myself clicking just torrent card but selection doesn't work in that way currently.

**Comment by WDaan** [comment]
I'm afraid I don't know how to remove that effect :sweat_smile:, if I did it would allready be gone...

I do like the click on card when selectmode is enabled suggestion

**Comment by IevgenSobko** [comment]
I am gonna take a look at how this grey selection effect works and maybe will have some ideas on how to disable it

Btw torrent card context menu selection initialization doesn't work for me if you are going to look into it you might try to fix it.
Or maybe it is obsolete functionality that is not necessary just remove that context menu item.

**Comment by LukePrior** [comment]
I just had another thought about the UI, when you right-click a torrent and get the popup menu.

Advanced >
Set Priority >
Set Category >

These submenus all open on the same x position which makes navigation harder. I would kindly suggest that they open on the right so it's easier to use the menu.

![image](https://user-images.githubusercontent.com/22492406/106378836-f0a1aa80-63fb-11eb-845f-fe97631c1abf.png)

**Comment by LukePrior** [comment]
Can the historical download statistic UI show the same statistics as live or use units?

![image](https://user-images.githubusercontent.com/22492406/106378936-889f9400-63fc-11eb-9085-b7cf411a3408.png)

**Comment by WDaan** [comment]
I did think about that, reason I didnt is because it can get cut off when opening the menu on the side of the screen & also the limited space of mobile devices

**Comment by LukePrior** [comment]
> I did think about that, reason I didnt is because it can get cut off when opening the menu on the side of the screen & also the limited space of mobile devices

Oh yeah it would only make sense on desktop, possibly you could make it open on whatever side has room?

**Comment by WDaan** [comment]
Little easier said than done 😅

**Comment by LukePrior** [comment]
> Little easier said than done 😅

No worries at all, I understand you are just doing this in your spare time.
I would try and help but I don't have the slightest clue about vue.js.

**Comment by WDaan** [comment]
Thanks for understanding!

Do you have other Web Development experience? If you do, it's pretty easy to get started.
