### ISSUE TITLE
Crash when loading torrent content.

### ISSUE THREAD

**Issue by jkavalon** [WDaan/VueTorrent#1360]
When right clicking on a torrent, selecting show info, and selecting content VueTorrent is crashing. It only appears to be occuring on larger torrents with many files. This is not occurring with the default WebUI.

**Comment by jaywong966** [comment]
> When right clicking on a torrent, selecting show info, and selecting content VueTorrent is crashing. It only appears to be occuring on larger torrents with many files. This is not occurring with the default WebUI. 

I encountered the same problem and it seems like this issue hasn't been resolved yet?

**Comment by Larsluph** [comment]
Duplicate of #1115, it's being reworked
