### ISSUE TITLE
Downloads not showing in Vue

### ISSUE THREAD

**Issue by squidds** [WDaan/VueTorrent#137]
When I initiate a download with the Vue webui for qbit, the download starts, I can see the speed of the torrent, but it doesn't populate in my torrent list. Torrent is downloading in qbit, though. 
![Swappshot Sat Jan 30 21:56:12 2021](https://user-images.githubusercontent.com/64927214/106373363-c0e49b00-6346-11eb-8161-973fdc5680ce.png)

**Comment by WDaan** [comment]
How do you host VueTorrent?

It has something to do with the new Magnet Handler.

**Comment by jef** [comment]
I'm oddly getting the same results:

![image](https://user-images.githubusercontent.com/12074633/106390002-3f2b5680-63b4-11eb-92a2-757ea4406de1.png)

My original UI is showing though. This originally was the issue:

https://github.com/linuxserver/docker-qbittorrent/issues/97

**Comment by WDaan** [comment]
Thinking it might be an issue with the service worker?

**Comment by WDaan** [comment]
Does this issue still occur? @squidds  & @jef

**Comment by squidds** [comment]
Will test today

**Comment by squidds** [comment]
Sorry, haven't been able to test it until now. It's working great. Thanks for reminding. Issue is gone.
