### ISSUE TITLE
[Bug] Last Activity: it shows "an hour ago" if the actual value is larger than 45 minutes and less than an hour

### ISSUE THREAD

**Issue by tainewoo** [WDaan/VueTorrent#1375]
Env:
VueTorrent: 2.3.0
qBittorrent: 4.6.2
libtorrent: 2.0.9
Browser: Microsoft New Edge

Steps:
1. Browse to VueTorrent settings, and enable the "Last Activity" property in "Torrent Card" for at least completed torrents.
2. add a torrent (choose a torrent that is not too active), complete the downloading. Seed it withou anyone else downloading from you, for 45 minutes.
3. Check the "Last Activity" value shown in the Dashboard TorrentList view, it would be "an hour ago".
4. Confirm the "Last Activity" timestamp in the TorrentDetail view, INFO tab, Datetime values section, the actual timestamp is in less than an hour.

Notes:
1. Original WEB UI doesn't have this issue.
2. Sometimes we will manage the torrents according to the "Last Activity" value, such as, delete the seeding torrents if they are not active for a long time. So this property is valuable.

**Comment by Larsluph** [comment]
This value is from dayjs: [source](https://day.js.org/docs/en/display/from-now#list-of-breakdown-range)

I added a config to disable those roundings, it should be better now :)

**Comment by tainewoo** [comment]
Thank you so much!
