### ISSUE TITLE
 [Bug] Seeding Time: Torrents older than a month count as 0 months

### ISSUE THREAD

**Issue by KrisCvetkovikj** [WDaan/VueTorrent#1379]
Env: docker
VueTorrent: 2.3.0
qBittorrent: 4.5.5
Browser: Firefox

Steps:

1. Enable seeding time for torrents
2. Have torrents older than a month
3. Sort by Added On

You'll see torrents being seeded more than a month being reported with wrong time.

<img width="330" alt="image" src="https://github.com/WDaan/VueTorrent/assets/4205988/751d6b7f-4ad3-423d-bdef-086c7c92f447">

**Comment by Larsluph** [comment]
We use DayJS to compute durations throughout the app.

The threshold they use for a month is `60*60*24*1000 * 365 / 12 = 2_628_000_000 = 30d 10h`. source [here](https://github.com/iamkun/dayjs/blob/e7eec414093cafb7fe9a7bcc8294f6991c25f1eb/src/plugin/duration/index.js#L11) and [here](https://github.com/iamkun/dayjs/blob/e7eec414093cafb7fe9a7bcc8294f6991c25f1eb/src/constant.js#L9)
By looking at the highest value from your screenshot, that's normal.

**Comment by KrisCvetkovikj** [comment]
How exactly is it normal when it's missing a full month?!

Here's a screenshot from the tracker reporting the seeding time:

<img width="395" alt="image" src="https://github.com/WDaan/VueTorrent/assets/4205988/d2a820fc-1be0-470d-bb60-22dde8ef1885">

Here's from vuetorrent:

<img width="273" alt="image" src="https://github.com/WDaan/VueTorrent/assets/4205988/1fefe1c0-93cc-4d45-8cea-a0cf81493792">

**Comment by KrisCvetkovikj** [comment]
> What's the actual value (in vuetorrent) and the expected one?

Just check the previous comment. The value is being reported wrong on Vuetorrent frontpage. Just try it with a torrent you've seeded more than a month and you'll see it's not showing the correct value. If you've had a torrent being seeded for 3 months and 5 days, it will show as 5 days of seed time.

**Comment by Larsluph** [comment]
Can you send the `seeding_time` sent by qBittorent?
On desktop, you can find it there:
1. Press F12 to open devtools and go to the "network" tab
1. Open the torrent detail where the seeding time should be more than a month
1. Select the request starting with `properties` and go to the "preview" tab
1. You should see the value in the list: `seeding_time: ...`

**Comment by KrisCvetkovikj** [comment]
The seeding time in the response json is `2666547`.

**Comment by Larsluph** [comment]
Thanks, will look into the issue
