### ISSUE TITLE
Improve Context Menu

### ISSUE THREAD

**Issue by IevgenSobko** [WDaan/VueTorrent#139]
Mobile context menu second level pop up menus unable to navigate.
Or maybe I don't know how to use them correctly. Then, please explain how to use it on mobile browsers, and feel free to close the issue.

**Comment by WDaan** [comment]
It's another long press, I don't (yet) know how to make it work on just a single tap/click

**Comment by IevgenSobko** [comment]
Oh, now I see. It works.
Then it is ok to leave it as it is.
And maybe later someone could come up with a better solution.

**Comment by WDaan** [comment]
I just had another thought about the UI, when you right-click a torrent and get the popup menu.

Advanced >
Set Priority >
Set Category >

These submenus all open on the same x position which makes navigation harder. I would kindly suggest that they open on the right so it's easier to use the menu.

![image](https://user-images.githubusercontent.com/22492406/106378836-f0a1aa80-63fb-11eb-845f-fe97631c1abf.png)

_Originally posted by @LukePrior in https://github.com/WDaan/VueTorrent/issues/136#issuecomment-770347380_

**Comment by Kaowain** [comment]
I don't know if you use vuetify. Here is an option with the offset

```
<template>
  <div class="text-center">
    <v-switch
      v-model="offset"
      label="X offset"
      color="primary"
    ></v-switch>
    <v-menu
      top
      :offset-x="offset"
    >
      <template v-slot:activator="{ on, attrs }">
        <v-btn
          color="primary"
          dark
          v-bind="attrs"
          v-on="on"
        >
          Dropdown
        </v-btn>
      </template>

      <v-list>
        <v-list-item
          v-for="(item, index) in items"
          :key="index"
        >
          <v-list-item-title>{{ item.title }}</v-list-item-title>
        </v-list-item>
      </v-list>
    </v-menu>
  </div>
</template>
```
```
<script>
  export default {
    data: () => ({
      items: [
        { title: 'Click Me' },
        { title: 'Click Me' },
        { title: 'Click Me' },
        { title: 'Click Me 2' },
      ],
      offset: true,
    }),
  }
</script>
```

**Comment by WDaan** [comment]
I am & thx!

Just needs a little logic to calculate the offset. 

PS: I'm a little busy with an internship atm, that's why release  frequency is decreased

**Comment by Kaowain** [comment]
Indeed, there are also the edges of the screen

**Comment by WDaan** [comment]
Jup, also submenus that have to go the other way depending on the position of the menu itself

**Comment by WDaan** [comment]
Feel free to try out yourself if you want :) 
otherwise Ill look into it when I find the time
