### ISSUE TITLE
[Feature Request] Disable rechecking all torrents after docker rebuilds (aka forced shutdown?)

### ISSUE THREAD

**Issue by Seltonu** [WDaan/VueTorrent#1404]
To preface, I know docker isn't officially part of VueTorrent but maybe posting here can give a bit more insight. I run hotio's container for VueTorrent and route the traffic through a VPN container (Gluetun). Whenever Gluetun has an update it rebuilds the VueTorrent container which causes every single torrent to recheck itself after Vuetorrent starts back up. 

I believe this to be more relevant to VueTorrent having some kind of "verify all torrents on non-graceful shutdown" flag/feature, rather than a docker thing necessarily. Unfortunately there doesn't appear to be a way to skip this rechecking and for large libraries on hard drive this can take a very long time.

It would be nice to have a way to disable forced rechecking after non-graceful shutdowns to prevent unnecessary wear on mechanical disks (hopefully there is little to no risk of data corruption or else this feature request may not be that useful)

**Comment by Seltonu** [comment]
As an additional note to this, there doesn't appear to be a way to *skip* checking once in progress

**Comment by Larsluph** [comment]
VueTorrent is only a WebUI so we can't interfere with the built-in behaviour of qBittorrent. What you're asking appears to be a server issue more than a client issue.
