### ISSUE TITLE
What do you think about following speed cards?

### ISSUE THREAD

**Issue by IevgenSobko** [WDaan/VueTorrent#141]
What do you think about following speed cards?
![2021-01-31__13-47-01](https://user-images.githubusercontent.com/14232100/106382919-5fb2db00-63cb-11eb-96b9-9f7fd0684436.png)

**Comment by WDaan** [comment]
It's great that there's a lot of room for the speed itself.
But the cards do take up a lot of vertical space in the sidebar. 

Any reason for this change?
I thought the current ones were great & the wrapping issues fixed by rounding the values

**Comment by IevgenSobko** [comment]
The current implementation is OK.
I just playing with my ideas before you implemented the current look.
Something like circles :)
![2021-01-31__14-23-08](https://user-images.githubusercontent.com/14232100/106383649-de117c00-63cf-11eb-993c-6dc43e334db7.png)
Just posting these ideas we might implement in case of redesign

**Comment by IevgenSobko** [comment]
What would you say about the following pill?
I decrease the space taken by using just 2 rows.
Also increased font size to clearly see the speed on laptop and mobile
![2021-01-31__18-51-29](https://user-images.githubusercontent.com/14232100/106391385-bf25e080-63f5-11eb-91ca-53a9b8d03786.png)

**Comment by IevgenSobko** [comment]
Or just following current rectangles with rounded corner
![2021-01-31__19-29-58](https://user-images.githubusercontent.com/14232100/106392523-e501b400-63fa-11eb-83c7-1cbc6d65ddcb.png)

**Comment by LukePrior** [comment]
I like the pill design.

**Comment by mrhotio** [comment]
Just letting you know that if the speed goed above 100MB/s the box goes like in the screenshot, I created the screenshot by using Inspect Element so the indicator for the speed is wrong, but I've seen it in real life.

<img width="257" alt="Schermafbeelding 2021-02-14 om 12 40 04" src="https://user-images.githubusercontent.com/26902309/107875784-25186a80-6ec2-11eb-9717-a81e885978ce.png">
