### ISSUE TITLE
[Feature Request] Maybe it's better to provide a horizental scrollbar  for table view

### ISSUE THREAD

**Issue by tainewoo** [WDaan/VueTorrent#1410]
qB: 4.6.2
Libtorrent: 2.0.9
VueTorrent: 2.4.0
OS: Microsoft Win11
Browser: Microsoft New Edge latest
Display resolution: 1920*1080

Maybe it's better to provide a horizental scrollbar  for table view.
When the user select some more columns for the table view to display, the columns will be displayed out of the display range. But there is no horizontal scrollbar for users to scroll and view the right part of the table.

-- I use a 1920*1080 display screen, maybe it would be better if it's on a 4K display.
-- The more columns are selected for the table view, the more columns are cut and are out of the display range on the width.
-- Currently I uses zoom out function of the browser. After zoom out to 80% or less, the whole table can be displayed.
-- Because the original font size is quite large, normally I will zoom out to 80%-90% on my Phone and my PC when I'm using VueTorrent, no matter list view or table view. But if zoom out to less than 80%, the font size will be a little too small :D

Notes:
**If there is a new feature for users to resize the width of the columns of at least the "torrent title", then this feature request can be ignored becuase we can fit the table size with the screen size by the column width resizing.** 

Screenshot of 100% view (the right part of the table is cut):
![tableview_100p](https://github.com/WDaan/VueTorrent/assets/13391232/68a85730-3a64-4f51-98ae-a3cee905d19b)

Screenshot of 80% view after zoom out:
![tableview_zoomout_80p](https://github.com/WDaan/VueTorrent/assets/13391232/0c468714-e620-43f4-8480-4a081e9ef24f)

**Comment by tainewoo** [comment]
P.S
it can be horizontally scrolled by touch on a phone, but if I'm using a PC without a horizontal scroll button, I may have no method to make it

**Comment by Larsluph** [comment]
You should be able to use the scroll click on your mouse to move the view horizontally. Apart from that, something like Ctrl/Shift/Cmd + Scroll may also work.

I haven't thought of that when designing the view as I always use a trackpad / scroll click so this didn't come to mind ^^

**Comment by tainewoo** [comment]
I tried to use the left and right button of keyboard to scroll horizontally, and it can work.
So please lower the priority for this issue, or ignore it since it's not so important now.

**Comment by tainewoo** [comment]
Referring https://github.com/WDaan/VueTorrent/issues/1401, 
resizing the size of the columns would be more usfule than this.
