### ISSUE TITLE
[Feature Request] Edit the RSS Feed URL

### ISSUE THREAD

**Issue by tainewoo** [WDaan/VueTorrent#1412]
With previous qB, there is no API exposed to edit the RSS Feed URL, we can only edit the RSS name.
Since qB 4.6.0, with qb PR https://github.com/qbittorrent/qBittorrent/pull/18807, the setFeedURL is implemented and exposed to WEB API.

Please consider to implement this feature on the Web UI.
Rather than editting the Feed name, the more we may need to edit the URL to change the search options for the feed.

**Comment by Larsluph** [comment]
Great news! Thanks for letting us know.
