### ISSUE TITLE
I can't select text in the torrent tab

### ISSUE THREAD

**Issue by simonbcn** [WDaan/VueTorrent#1413]
```
qBittorrent 4.6.2
VueTorrent 2.4.0
Google Chrome 120.0.6099.109
```

I double-click on a torrent to enter its details and try to select the torrent name (_because I want to do a search on the tracker I downloaded it from_) but I can't select text.

**Comment by Larsluph** [comment]
This was originally intended, cf #866
I agree that it can be useful on some fields.

For your specific case, you can: Right click on the dashboard > Copy > Name

**Comment by simonbcn** [comment]
Thanks, although that option does not work either, I have created a new issue: #1414 

Why is it intentional? What is the reason for this intentionality?
