### ISSUE TITLE
Copy > ... option doesn't work

### ISSUE THREAD

**Issue by simonbcn** [WDaan/VueTorrent#1414]
```
MacOS 14
qBittorrent 4.6.2
VueTorrent 2.4.0
Google Chrome 120.0.6099.109
```

I select the context menu option `Copy` > `Name` | `Hash` | `Magnet` but it does not copy anything.

**Comment by pbarone** [comment]
Same for me, running qbittorrent in Docker and with any browser (windows) I tried

**Comment by Larsluph** [comment]
The fact that it's not working doesn't come from the browser but from the qbit server environment.
To allow access to the clipboard a website must be considered a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#when_is_a_context_considered_secure).
 You should see a toast indicating that. If not, that's the real bug.

**Comment by simonbcn** [comment]
_qbit server environment_ is insecure by default. 
I doubt very much that there are many people who use it in a secure environment, especially since it is usually run inside the LAN (_which makes it unnecessary_). 
If this doesn't work if the server isn't running using HTTPS, that's when it's most needed to work #1413

**Comment by pbarone** [comment]
But it works just fine if I don't use the Vue WebUI...

**Comment by WDaan** [comment]
>  But it works just fine if I don't use the Vue WebUI...

We nowhere state that we wan't to behave the same as the original....
However I do agree that some design choices might need a little adjustment

**Comment by pbarone** [comment]
Then I would recommend removing the option if it not https. Or (even better) grey it out with a message explaining the behavior. As it is you have a non working link in the interface
