### ISSUE TITLE
Distinguish Speed Graph's 0 values from no data

### ISSUE THREAD

**Issue by josh-h** [WDaan/VueTorrent#1421]
First, thank you for your great contribution. VueTorrent is a pleasure to use over traditional torrent interfaces.

When navigating to VueTorrent, or reloading the page, the Speed Graph appears with series data with 0 y-axis values. This leads to the impression that speeds before loading the page were 0 and the speed increases when using VueTorrent. It would be a better user experience if no data values are not displayed (ie. show as gaps in the graph to the user), and 0 is used only to indicate no transmission, ie. 0 transfer speed.

Here's a simple codepen showing that apexcharts supports null values to show no data, https://codepen.io/blipo/pen/ExrqdKM

I think we can achieve this by changing navbar.ts and changing the Array.fill statements to fill with `null`.

**Comment by Larsluph** [comment]
Awesome! Thanks for the feedback and the codepen, it works perfectly 🚀
