### ISSUE TITLE
Search not returning results from slow engines

### ISSUE THREAD

**Issue by TransLucida** [WDaan/VueTorrent#144]
Using the default webUI I noticed some search engines seem slower to return resulsts than others. With VueTorrent these engines never seem to return any results at all. Anything I can do to help diagnose the problem?

**Comment by WDaan** [comment]
Are there any logs or messages you can see in your browser's console?

The search should keep running as long as the API doesnt mark it as stopped...so it should work regardless of the duration

**Comment by TransLucida** [comment]
Must've been a temporary outage. Tried for a couple hours yesterday and it wasn't working. Woke up this morning and it did. Thanks.

**Comment by WDaan** [comment]
Glad to hear :)
