### ISSUE TITLE
[Feature Request]: Column order change in Table view

### ISSUE THREAD

**Issue by book-of-mormon** [WDaan/VueTorrent#1443]
### Description

Hi Team,
Currently in settings, for views like list/grid/table/ it is possible to disable or enable specific properties to be displayed in main dashboard view. Would be great to not only disable/enable some proiperties to be displayed, but also to change their order - mainly in table view.
Looks like there's a button already in settings (next to checkbox) - but no possibility to drag&drop them and change positions.

Thanks.

### Describe the solution you'd like

Ability to change order of displayed properties in table view (and other views if possible).

### Describe alternatives you've considered

No alternative available (except switching back to default gui).

### Complementary informations

- [x] Is this feature already implemented in the default WebUI?
Yes.

**Comment by Larsluph** [comment]
In that case that's a bug because you should be able to use drag & drop to reorder columns, hence the handle at the left of each property.

Consider creating a bug report instead, or replying with your environment description (browser, OS, ...)

**Comment by book-of-mormon** [comment]
Closing the task, as it worked properly after restart.
