### ISSUE TITLE
[Feature Request]: Permanent Settings

### ISSUE THREAD

**Issue by Pikey18** [WDaan/VueTorrent#1451]
### Description

It would be good if there was a way to set the UI settings globally so user preferences under the VueTorrent tab could be set on one computer and be there on another (for example what items to display on sidebar). 

If there is no way to write to a config file on the server but one can be queried maybe having an option to export one that can be manually copied to the system running qBittorrent would work.

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by WDaan** [comment]
There is no way to automatically transferring setting to another pc. settings are stored in the browser, there is no way to write something to qbittorent.

The solution that was provided was a way to export/import settings but this hasn't been ported over to the vue3 version yet

**Comment by Larsluph** [comment]
#1322
