### ISSUE TITLE
Create a torrent

### ISSUE THREAD

**Issue by bgette** [WDaan/VueTorrent#15]
First of all I really love your project, its the first time I've seen such a amazing WEBUI ! ;)

The possibility of creating a torrent ? It would be great if you could add that.

Ty.

**Comment by WDaan** [comment]
Thank you very much for the kind feedback 🙂

I will put it on the todo list.

At first glance I don't think it's possible? 
The default WEBUI doesn't seem to have this ability nor do I see any mention of it in the their Web API documentation.

**Comment by bgette** [comment]
> At first glance I don't think it's possible?

yes... /:

**Comment by josopu** [comment]
You can actually create a torrent file via the default webUI under tools:
![image](https://user-images.githubusercontent.com/84581781/119154491-810b0600-ba52-11eb-9bde-f87252c1504a.png)
The [guide](https://github.com/qbittorrent/qBittorrent/wiki/How-to-use-qBittorrent-as-a-tracker)

**Comment by WDaan** [comment]
Sure, but I don't see any mention of it in the WebUI API documentation [here](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)), so there's no way for me to implement it.
