### ISSUE TITLE
[Feature Request] Translation

### ISSUE THREAD

**Issue by hot22shot** [WDaan/VueTorrent#150]
Hello,

Do you plan to support the translation of the web ui in any way ?

Regards

**Comment by WDaan** [comment]
It isn't planned...but I was expecting this request sooner or later. 

Depending on demand, we can start looking into this

**Comment by Kaowain** [comment]
May I help you for french translation ?

**Comment by WDaan** [comment]
Ofc! I would reaaaaaaally appreciate your help! :)

**Comment by Kaowain** [comment]
mijn nederlands is niet beter.

**Comment by Kaowain** [comment]
Did you plan to use this plugin [(https://kazupon.github.io/vue-i18n/introduction.html)](https://kazupon.github.io/vue-i18n/introduction.html)

**Comment by WDaan** [comment]
I was :)

**Comment by pboymt** [comment]
> I was :)

@WDaan After you have finished the internationalization configuration, I can quickly provide you with Simplified Chinese and Traditional Chinese support.
