### ISSUE TITLE
Speed graph unreadable in dark mode

### ISSUE THREAD

**Issue by bobokun** [WDaan/VueTorrent#153]
When enabling dark mode and hovering over the speed graph on the left makes the text very difficult to read.
![image](https://user-images.githubusercontent.com/12660469/107882857-a7506100-6eb9-11eb-9e31-b5a710d5b5d8.png)

**Comment by WDaan** [comment]
I dont know which version you're running but it this is allready fixed

![image](https://user-images.githubusercontent.com/25707052/107917427-3a47d480-6f68-11eb-9976-a95e4a918096.png)
![image](https://user-images.githubusercontent.com/25707052/107917465-4469d300-6f68-11eb-8413-9b328fd75845.png)

Perhaps it's isn't released yet
