### ISSUE TITLE
Torrent Search Not Displaying Correctly On Mobile

### ISSUE THREAD

**Issue by LukePrior** [WDaan/VueTorrent#156]
Torrent search doesn't seem to work as it should on mobile. The torrent name will be cut off and the sort text does not appear. I have attached an image. I'm not sure what the best UI solution would be, I did see this design.

![IMG_20210216_220201](https://user-images.githubusercontent.com/22492406/108054357-a7f81b80-70a2-11eb-94da-b71f712c1377.jpg)

![images (14)](https://user-images.githubusercontent.com/22492406/108054476-cf4ee880-70a2-11eb-8a64-e22edf3bdb6a.jpeg)

Let me know if I can help in any design or testing way.

**Comment by WDaan** [comment]
Just made it usable for now, might redesign in the future

![image](https://user-images.githubusercontent.com/25707052/108170700-c68a0100-70fa-11eb-86d1-33da25edced3.png)

**Comment by LukePrior** [comment]
I still seem to be running into the issue, I can confirm I am running 0.6.0. Any ideas?

**Comment by LukePrior** [comment]
I also noticed that the bottom plugin manager and X aren't always at the bottom of the screen.

![IMG_20210217_214803](https://user-images.githubusercontent.com/22492406/108193700-da208080-7169-11eb-953c-59489a2d9c42.jpg)

Thanks for all the time and effort you are putting into making this project.

**Comment by LukePrior** [comment]
Is there anything I can do to help you debug?

**Comment by WDaan** [comment]
Thanks a lot for the appreciation!!

Woah I don't understand 😅
I've tested with Chrome/Firefox on a bunch of different sizes.
Tested on my phone itself (OnePlus Nord) with both Chrome & Firefox.

My 'window' is allways fullscreen for mobile devices & entries fit just fine (as in my screenshot)

**Comment by LukePrior** [comment]
The screenshot was taken on Brave Android 10 on my Oppo Reno 10X Zoom. I find the same behaviour when using Chrome and Firefox.

That leads me to believe it is something with my particular device which is causing the issue. The screen resolution is 2340*1080.

**Comment by WDaan** [comment]
I don't think that should be an issue, I'm kinda clueless here 😅

**Comment by LukePrior** [comment]
I just tested it on my desktop by resizing the browser window and I see the same behavior as on my phone.

The behavior seems to be dependent on what I'm searching for, when I search for Ubuntu all the torrent names are short and the interface is displayed correctly. If I search for something different like "test" the torrent names are different lengths so I'm guessing this is the cause? 

Does that help point you in the right direction?

Cheers

**Comment by WDaan** [comment]
![image](https://user-images.githubusercontent.com/25707052/108468507-21506380-7287-11eb-9831-fa340e7ad6aa.png)
![image](https://user-images.githubusercontent.com/25707052/108468595-42b14f80-7287-11eb-8280-3ebca34a22ca.png)
![image](https://user-images.githubusercontent.com/25707052/108468696-6b394980-7287-11eb-87ae-aa2499010608.png)


I would like to see it occur for myself 😅 It's kinda hard fixing something without seeing it yourself.
Anyone else also having issues with this?

**Comment by LukePrior** [comment]
Yeah this is what I see:

![image](https://user-images.githubusercontent.com/22492406/108470438-1248d000-72de-11eb-8cf8-bc5cd80cb919.png)

**Comment by webiebuilders** [comment]
the problem occurs when the file name is too long,

**Comment by WDaan** [comment]
Thank you for your interest in the project!

And a massive thank you for analysing the problem and suggesting a great way to fix it! 

I'll implement it as soon as I can.
