### ISSUE TITLE
After updating to 0.6.0, "Unacceptable file type, only regular file is allowed."

### ISSUE THREAD

**Issue by WestonHanners** [WDaan/VueTorrent#159]
I have installed via the single branch method.
Running qBittorrent-nox 4.3.3
I have checked the directory ownership and they match the user running qBittorrent.
Ubuntu Server Groovy

This worked fine on 0.5.6, but once I updated to 0.6.0, I now get "Unacceptable file type, only regular file is allowed."
I checked the small FAQ in the README, but it didn't seem to cover anything I might be doing to cause it.

**Comment by WestonHanners** [comment]
Also to add, I install via the official qBittorrent ubuntu repo.

**Comment by scatterfish** [comment]
The files need to be placed in a folder called `public`, and the release routine should have done that automatically but in the meantime you can do it manually as a fix.

**Comment by WestonHanners** [comment]
That worked, thanks.
