### ISSUE TITLE
Button to select all torrents in select mode?

### ISSUE THREAD

**Issue by LukePrior** [WDaan/VueTorrent#161]
I just found out from the other issue that CTRL-A selects all torrents, I think it would be handy for new users to have a button with this action. The button could appear when in select mode or select mode could select all with a double click?

What do you think?

**Comment by WDaan** [comment]
It's also mentioned in the README tho 😅 but nobody seems to read those. I think Ctrl+A is a quite natural shortcut.

Ideally there would be a checkbox above the list of torrents, but the search and stuff is allready there...I will think about how Im going to solve that
