### ISSUE TITLE
Paused and Seeding colors are very similar

### ISSUE THREAD

**Issue by IevgenSobko** [WDaan/VueTorrent#162]
Paused and Seeding colors are very similar
When using a dark theme and lowering the brightness of the laptop screen it is hard to distinguish Paused and Seeding torrents because of very similar colors.
I guess we need to change them to be much more distinguishable.
![2021-02-21__23-33-01](https://user-images.githubusercontent.com/14232100/108639528-a614ca80-749d-11eb-9f35-a7b470ef3c24.png)

**Comment by WDaan** [comment]
Don't you mean 'done' & 'seeding'? Because those are the 2 shown in the picture, if I'm not wrong. :)

**Comment by IevgenSobko** [comment]
Yep, these are `done and seeding` as well as `done and seeding paused` 
I checked not done and paused and it is shown as some shade of gray or white.
I would expect every `paused` should have the same color not depending on the completeness status.

**Comment by WDaan** [comment]
They're to similar indeed.
I guess we should let the public decide which colors we're going with 😝

So anyone who reads this, feel free to make suggestions or a poll or something :)

**Comment by IevgenSobko** [comment]
@WDaan how about making all paused have the same color(not dependent on completeness status)?
Do you agree with this?

**Comment by WDaan** [comment]
these are the only torrent states that exist.... there should be only 1 type of paused
![image](https://user-images.githubusercontent.com/25707052/109273956-2bd4a500-7813-11eb-9272-f0ebec2c68c5.png)

**Comment by IevgenSobko** [comment]
But there are 2 see my last screenshot.
And it depends on completeness status.
If torrent is not complete you get this grey color that I think is correct.
If torrent completed and seeding and you pause it you get second row in my screenshot.

**Comment by IevgenSobko** [comment]
Woops. Accidentally closed in mobile application of GitHub.
Sry 😭

**Comment by WDaan** [comment]
Okaay, it took me a while to understand what you were trying to say ... sorry 😅
Yes, pausedUp is used to mark is at 'done', I thought it was the same way that the default WebUI decides it.
You're saying that pausedUp should result in paused as well?? But than there is no way to know if a torrent is actually done?

![image](https://user-images.githubusercontent.com/25707052/109274993-6c80ee00-7814-11eb-8396-6e56d9e6bcfc.png)

**Comment by IevgenSobko** [comment]
I played with original UI and seems you are correct about they distinguish paused depending on the completeness status.
For me it is important to know whether torrent is paused or not because I download torrent just few hours but leave it to seed for a months if not years.
I such a situation I think 🤔 just making seeding and done distinguished by colors would be ok if we want to follow original qbittorent ideas.

**Comment by IevgenSobko** [comment]
I suggest something like the following color for `done` state.
Green indicates it is done and dark shade means it is doing nothing(paused)
![2021-02-26__11-11-52](https://user-images.githubusercontent.com/14232100/109280401-aa394300-7823-11eb-829a-4c3293b8472a.png)
But it might not play well with dark or bright theme.
I'll check it in a few hours when free.

**Comment by IevgenSobko** [comment]
@WDaan btw what IDE r u using?

**Comment by WDaan** [comment]
PhpStorm & VSCode :)

**Comment by IevgenSobko** [comment]
I think following color might work 
`$torrent-done: #16573e;`
![2021-02-26__12-54-17](https://user-images.githubusercontent.com/14232100/109291584-d2c83980-7831-11eb-99d7-385925d1d0aa.png) ![2021-02-26__12-54-39](https://user-images.githubusercontent.com/14232100/109291588-d360d000-7831-11eb-884c-e2e289f5199e.png)

**Comment by WDaan** [comment]
The destinction between the colors is a lot better, yes :)

**Comment by IevgenSobko** [comment]
If noone objects feel free to incorporate this color in next release.
It doesn't make sense to open merge request for a such big change 🤣

**Comment by WDaan** [comment]
If someone wants to get mentioned as a contributor perhaps
