### ISSUE TITLE
[UI] Displaying category index as name on "add new torrent"

### ISSUE THREAD

**Issue by alexbcberio** [WDaan/VueTorrent#164]
When adding a new torrent the category list does not show the name of the category but its index. If you select it a new category is added named as the selected number.

Screenshot of proof:
![image](https://user-images.githubusercontent.com/22194879/109212861-445fa380-77b0-11eb-8e3a-a2fe11f63544.png)

On the details page the listing works ok
![image](https://user-images.githubusercontent.com/22194879/109212999-66f1bc80-77b0-11eb-9e33-e169b4fb96c3.png)

PS I've not seen any report of this.

**Comment by WDaan** [comment]
Was mentioned in #115, I thought it was fixed

**Comment by IevgenSobko** [comment]
I don't have such a bug with the latest release.
@alexbcberio could you pls post the version number of your vuetorrent?
If it is not 0.6.0 pls try to update and clear the browser's cache.

**Comment by alexbcberio** [comment]
In the settings says than I'm under 5.1, I have a cron job to sync the repo but seems there is a merge problem.

Problem is definitelly on my side, thanks for the fast response.

I'm closing the issue
