### ISSUE TITLE
[idea] show first torrent progress in title bar

### ISSUE THREAD

**Issue by FatSandwich** [WDaan/VueTorrent#166]
There should be a feature that turns the title (the tab name) to the percentage of the first torrent!

**Comment by WDaan** [comment]
Would many people use that? I don't really think that's usefull 


Perhaps other people have an opinion?

**Comment by Kaowain** [comment]
It's depend, for me it's the icing on the cake. Not necessary, but a plus (80-20 ;) ), if you want a quickview of the state like 'idle, downloading "Title of first current download",... 

Not really difficult to implement but as a priority it's low.

**Comment by WDaan** [comment]
I've tried it & there is barely enough space to show the state & the progress percentage... let alone the name
When you hover over it, you can see part of the name though.
The hover part was impossible to screenshot 😅

![image](https://user-images.githubusercontent.com/25707052/109394307-9fb3a200-7926-11eb-9f93-42cb33f03228.png)

**Comment by Kaowain** [comment]
Just keep it simple ^^. 
Or Like D: 57.71Kb/s U: 2.2Kb/S

**Comment by WDaan** [comment]
So exactly like the current global one but for the first torrent??

**Comment by Kaowain** [comment]
Yes indeed (I just noticed this behaviour)
[D: 0 B/s; U:O B/s] 

I wonder if the title of the 1st download is really necessary in the title 
I have mixed feelings, because the goal is to know if we are download, I don't care what is downloading now.

**Comment by Kaowain** [comment]
> It's depend, for me it's the icing on the cake. Not necessary, but a plus (80-20 ;) ), if you want a quickview of the state like 'idle, downloading "Title of first current download",...
> 
> Not really difficult to implement but as a priority it's low.

Not really a good idea at all
