### ISSUE TITLE
Torrent Detail modal with multiple tags shows only one tag selected

### ISSUE THREAD

**Issue by IevgenSobko** [WDaan/VueTorrent#167]
Torrent Detail modal with multiple tags shows only one tag selected
![2021-02-27__17-10-16](https://user-images.githubusercontent.com/14232100/109391298-0765ef00-791f-11eb-9fd4-8009f865f9ab.png)
![2021-02-27__17-10-42](https://user-images.githubusercontent.com/14232100/109391299-07fe8580-791f-11eb-9bc3-6ae4a762f830.png)

**Comment by WDaan** [comment]
Jup, I noticed when I refactored it. There is no reason it shouldnt show them all, yet it doesnt... So I'm thinking it's an issue on vuetify component itself, but I don't know for sure

**Comment by IevgenSobko** [comment]
Seems it is an issue not with the component itself but how we get tags for torrent.
I've tried to debug and found it is returning extra space for every not first torrent tag.
![2021-02-27__19-10-13](https://user-images.githubusercontent.com/14232100/109394454-b9a5b280-792f-11eb-8dd1-3a1bba145346.png)
Trying to debug further to fix this.

**Comment by WDaan** [comment]
You are right, I'm stupid 😅 I think a simple trim solves it... no clue how I didn't catch that

**Comment by IevgenSobko** [comment]
No way person wrote this whole UI is stupid 🤫
