### ISSUE TITLE
search support

### ISSUE THREAD

**Issue by jmaris** [WDaan/VueTorrent#17]
This is more a feature request than an issue, but would it be possible to implement torrent search (that searches sites) ?

**Comment by WDaan** [comment]
I do admit that would be a really cool feature.

If someone can link me an easy to use indexer API, sure.
I believe Jackett is one of the more popular, but I don't see any API docs at first glance.

**Comment by jmaris** [comment]
I  believe qBittorrent has integrated support for search ?

**Comment by WDaan** [comment]
I did not know you could do that! 😯

I've implemented a basic version in the development build, I hope you like it 🙂

**Comment by jmaris** [comment]
Thats awesome :D i'll take a look today :)

**Comment by jmaris** [comment]
for the moment i appear not to be getting any results (it just searches forever). Could be network constraints on my side though, i'll look into it and get back to you :)

**Comment by WDaan** [comment]
Are there any error messages you could show me? 
It worked instantly at my end.

Anyone else having problems with it??

**Comment by jmaris** [comment]
Was a connectivity issue on my side! 

It now works totally fine !

Cheers :)
