### ISSUE TITLE
[Show] Mod for LinuxServer.io's container

### ISSUE THREAD

**Issue by arafatamim** [WDaan/VueTorrent#177]
If you are using qBittorrent from LinuxServer.io, I've created a mod so that you can quickly install VueTorrent onto your container. [More info here](https://github.com/arafatamim/linuxserver-io-mod-vuetorrent).

**Comment by WDaan** [comment]
Awesome, thx! I've added it to the Wiki :smiley:

**Comment by jeff15110168** [comment]
@arafatamim  @WDaan  hi guys. having trouble setting this up. I setup this variable in my linuxserver qbit container. I then launch the qbit container and go to settings -> webUI but i don't know what to enter in the field "files location" under "use alternative web UI". I've tried "/vuetorrent" and "DOCKER_MODS" which both didn't work. Also when i run `root@Server:~# docker exec qbittorrent ls -la /vuetorrent`, i get `ls: cannot access '/vuetorrent': No such file or directory`

How do i get this working with linuxserver qbit container on docker / unraid?

![image](https://user-images.githubusercontent.com/9892738/128674332-077f48b6-a24c-43a0-b10b-d96ec76a91ab.png)

**Comment by arafatamim** [comment]
@jeff15110168:
Interesting. Can you post the log here? (`docker logs <container-name>`). Also, I can't quite recognise the software shown in your screenshot, what's it called?

![image](https://user-images.githubusercontent.com/31634638/128675722-7abbc91f-4b2e-4d67-a356-9693b51754e0.png)

**Comment by arafatamim** [comment]
PS Did you try setting the "Key" above to "DOCKER_MODS"?

**Comment by WDaan** [comment]
The software he's using looks like the UnRaid WebUI 😛

**Comment by jeff15110168** [comment]
Perfect - that worked! Thank you so much :)
