### ISSUE TITLE
Unacceptable file type, only regular file is allowed. (i know)

### ISSUE THREAD

**Issue by Kaowain** [WDaan/VueTorrent#178]
Hello,

Due to a failure of my NAS, I've to reinstall all entire thing. But I've made a mismatch with the config of VueTorrent and QBitorrent

Here is the parameters (in qBittorent.Conf)

`WebUI\RootFolder=/vuetorrent`

in my nas

![image](https://user-images.githubusercontent.com/935349/110657378-140d0180-81c1-11eb-82e1-2ee02ad35c3f.png)

where is the mistake?

**Comment by Kaowain** [comment]
update 
`docker/qbittorrent/vuetorrent` ==> `/vuetorrent` 

in the config file

`/vuetorrent`

now I've a blank page

**Comment by WDaan** [comment]
From what I understand you've configured it exactly as it should be.

To summarize, your QBittorrent should point to a folder that contains the public folder.  

If you're allready doing that, the issue probably lies somewhere else

**Comment by Kaowain** [comment]
the reference path '/vuetorrent' in docker should point to docker/qbittorrent/vuetorrent/public or shorter docker/qbittorrent/vuetorrent/ ?

**Comment by Kaowain** [comment]
there is my index page actualy with the latest config. It's strange

`<!DOCTYPE html><html lang=en><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1"><meta name=Description content="The sleekest looking WEBUI for qBittorrent made with Vuejs!"><!--[if IE]><link rel="icon" href="./favicon.ico"><![endif]--><title>VueTorrent</title><link href=css/app.c1c3a150.css rel=preload as=style><link href=css/chunk-vendors.5730a3a9.css rel=preload as=style><link href=js/app.ab2ff2d8.js rel=preload as=script><link href=js/chunk-vendors.b30a8ce0.js rel=preload as=script><link href=css/chunk-vendors.5730a3a9.css rel=stylesheet><link href=css/app.c1c3a150.css rel=stylesheet><link rel=icon type=image/png sizes=32x32 href=img/icons/favicon-32x32.png><link rel=icon type=image/png sizes=16x16 href=img/icons/favicon-16x16.png><link rel=manifest href=manifest.json><meta name=theme-color content=#4DBA87><meta name=apple-mobile-web-app-capable content=no><meta name=apple-mobile-web-app-status-bar-style content=default><meta name=apple-mobile-web-app-title content=vuetorrent><link rel=apple-touch-icon href=img/icons/apple-touch-icon-152x152.png><link rel=mask-icon href=img/icons/safari-pinned-tab.svg color=#4DBA87><meta name=msapplication-TileImage content=img/icons/msapplication-icon-144x144.png><meta name=msapplication-TileColor content=#000000></head><body><noscript><strong>We're sorry but VueTorrent doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id=app></div><script src=js/chunk-vendors.b30a8ce0.js></script><script src=js/app.ab2ff2d8.js></script></body></html>`
