### ISSUE TITLE
Improvements to the header on Safari for iOS (Progressive Web App)

### ISSUE THREAD

**Issue by tdeverx** [WDaan/VueTorrent#180]
Currently, when you add Vue to your home screen as a Progressive Web App, the header has a black bar at the top to accommodate for the "notch". However, this is easily fixed with a tiny bit of code.

You may refer to this blog post on how to implement the fix.

https://medium.com/appscope/changing-the-ios-status-bar-of-your-progressive-web-app-9fc8fbe8e6ab

**Comment by WDaan** [comment]
Thanks for the tip, I've chose the translucent option!

I have no way of testing it myself so we'll have to see upon release.

**Comment by WDaan** [comment]
Shoudl be fixed with release 0.7.0, feel free to re-open if not
