### ISSUE TITLE
[Feature] Confirm prompt for "delete with files"

### ISSUE THREAD

**Issue by Ansem93** [WDaan/VueTorrent#191]
Hi,
I wanted to ask if it would be possibile to add a confirm prompt in case someone missclicked and use "delete with files" instead of "delete"

**Comment by m4ximuel** [comment]
It's nice opinion.
It would be good to combine the delete menu of the right-click menu into one and open the delete dialog.

**Comment by Ansem93** [comment]
Just tired the 0.8 release.
I actually thought at something different:
- keep the delete and "delete with files" as separate button when you right click on a file
- If you click on "delete with files" prompt a warning asking if you're sure. 

Otherwise I agree with #199 ,Delete with files should be a checkbox since a button so close to "delete" is still dangerous.

**Comment by WDaan** [comment]
Thx for the input!
In the next release, there will be a checkbox. And the delete button changes color depending on whether it's checked or not, so it's very clear what's happening
