### ISSUE TITLE
[Feature] New dialog designs conforming to the standard

### ISSUE THREAD

**Issue by m4ximuel** [WDaan/VueTorrent#200]
![Untitled-1](https://user-images.githubusercontent.com/54457152/113801596-1cdafe00-9794-11eb-9253-a04dd61562f6.png)
![Untitled-2](https://user-images.githubusercontent.com/54457152/113801597-1d739480-9794-11eb-9cf7-75a48861c4e5.png)

What do you think of this new design?
It followed the Vuetify standard as much as possible and caught most of the possible layout bugs.
All dialogs have been tested.

**Comment by WDaan** [comment]
Doesn't look bad but I think we should stick to the [material](https://material.io/components/dialogs) design specs as close as possible.

![image](https://user-images.githubusercontent.com/25707052/113816553-49cbe880-9775-11eb-8210-6374e803478d.png)

**Comment by m4ximuel** [comment]
@WDaan 
I fully agree to the material.
That's a design with only rounded and button style changes from the default material design. Then, how about having to the new design as this but also having the changed to material style?

**Comment by WDaan** [comment]
I personally prefer the corners and buttons to be a little less rounded and more like the official standard... but I'm not an expert by any means :sweat_smile: 

I guess other people could mention their preference & we make a decision based on that

**Comment by m4ximuel** [comment]
That round and iconic design is completely my personal taste.
I think it would be nicer if I modify your design a little closer to the material standard. Or I can keep your design and change only the layout conflicts I find to the standard.

**Comment by WDaan** [comment]
Sure! I look forward to seeing some implentations

**Comment by IevgenSobko** [comment]
@m4ximuel Do you have a repository with this rounded design implemented?
I would like to try it.

**Comment by m4ximuel** [comment]
@IevgenSobko When fixing a layout bug, I will code the corner sizes to be globally adjustable in the stylesheet.
