### ISSUE TITLE
[bug] vue2-perfect-scrollbar issue

### ISSUE THREAD

**Issue by m4ximuel** [WDaan/VueTorrent#206]
How about removing the vue2-perfect-scrollbar package? I implemented it neatly without it. That package causes child modal scrolling problems.
The new layout source code does not use that package.

**Comment by WDaan** [comment]
Sure, if it's no longer needed.... The fewer dependencies, the better

**Comment by IevgenSobko** [comment]
Is it going to fix also #170?

**Comment by m4ximuel** [comment]
@IevgenSobko Touch gesture scrolling scrolls the background when the top-level modal has no more content to scroll.
However, your experience will be much better than before, as the mentioned packages can cause errors in situations of similar nesting.

**Comment by WDaan** [comment]
will be closed by #207
