### ISSUE TITLE
[feature] New icon design

### ISSUE THREAD

**Issue by m4ximuel** [WDaan/VueTorrent#209]
![화면 캡처 2021-04-11 120220](https://user-images.githubusercontent.com/54457152/114290907-ff70a180-9abd-11eb-80e4-dd056876390c.png)
Typography design using letters 'Vt'.

**Comment by WDaan** [comment]
Woaaaaaah, that looks insane!

**Comment by WDaan** [comment]
I'd love to have it as the new icon! We should put it in the README as well... To make it stand out a little more

**Comment by m4ximuel** [comment]
Icon resource modifications in vue.config.js are in progress. Please fill out the README as I will temporarily upload a resource.
![512-temp](https://user-images.githubusercontent.com/54457152/114305526-6bc9c000-9b13-11eb-9931-814f54571b66.png)

**Comment by m4ximuel** [comment]
@WDaan 
If there is a place you want to apply, such as a readme, apply it using the image above. The standardized resource will be reflected through #207.

**Comment by WDaan** [comment]
Great! You should swap it in a PR as well. So it becomes the official VueTorrent logo.

**Comment by m4ximuel** [comment]
#214
