### ISSUE TITLE
Queued / Seeding shows as failed

### ISSUE THREAD

**Issue by tmayoff** [WDaan/VueTorrent#21]
I was going to fix this myself and contribute some work, but I wanted this here to keep track.

![image](https://user-images.githubusercontent.com/10094264/89227777-48299f80-d5ac-11ea-979e-b9e8e1b4b83f.png)

**Comment by WDaan** [comment]
Thank you for contributing 🙂 this is a milestone in the project.
I've made some small changes to your pull request

**Comment by tmayoff** [comment]
I'm happy to work on it. Although I'm new to Vue.Js so it's taking me a bit to figure things out, it'll be a while before the settings menu is actually usable

**Comment by WDaan** [comment]
Feel free to reach out to me if you have any questions or want some help :)
