### ISSUE TITLE
[Feature] blur effect when modals open

### ISSUE THREAD

**Issue by m4ximuel** [WDaan/VueTorrent#210]
![화면 캡처 2021-04-12 042015](https://user-images.githubusercontent.com/54457152/114318123-88332000-9b46-11eb-8686-2ef83750044a.png)
![화면 캡처 2021-04-12 042214](https://user-images.githubusercontent.com/54457152/114318156-b0bb1a00-9b46-11eb-8528-efab60ced24e.png)
It's incredibly simple code. However, it may cause lag depending on the device.
In terms of optimization, in my opinion, vuetify itself is by no means a light-weight resource, so if it's pretty enough it seems to be applicable.

**Comment by WDaan** [comment]
I think it looks great! I don't like the added lag though...but if it's not much, it should be fine.

I know vuetify is pretty bloated, as a matter of fact...I looked into getting rid of it today, tried a few alternatives but I'm not really sure what to do yet.

**Comment by m4ximuel** [comment]
@WDaan 
`
.v-dialog__content {
    backdrop-filter: blur(3px) !important;
}
`
I tried the weird way, but this one was enough and fast...

**Comment by m4ximuel** [comment]
@WDaan For performance testing, this feature will be pending release.
There are still a lot of other things to go on. Others first.

**Comment by m4ximuel** [comment]
![화면 캡처 2021-04-15 164617](https://user-images.githubusercontent.com/54457152/114833088-2c002280-9e0a-11eb-842f-6c5ad510cbba.png)
@WDaan After a few days of using it with the new layout, I realized something confusing. The blue layout doesn't attract attention because of the new red layout. For that reason, I would suggest removing that blue layout entirely and displaying and merging it into the red layout. Leave only 'Add Torrent', 'Search', and 'Settings' in the blue layout.

**Comment by m4ximuel** [comment]
Continuous testing results, adversely affecting users in some environments.
In particular, in the iOS environment, it is a serious delay when memory stacks up.
It should never be used for years to come.

**Comment by WDaan** [comment]
Hahaha, thank you for testing so thoroughly. 
Too bad there's such a performance decrease
