### ISSUE TITLE
[Feature] new select mode design

### ISSUE THREAD

**Issue by m4ximuel** [WDaan/VueTorrent#211]
![new select mode design](https://user-images.githubusercontent.com/54457152/114385549-1fda5200-9bcb-11eb-9f0f-89828411980d.png)
Mode conversion no longer changes the layout size.
The check box on the left now float on the right.
Select All button is floating in the upper right corner.

**Comment by WDaan** [comment]
I really like the floating buttons! They look great! 
Do they work well for mobile as well?

**Comment by m4ximuel** [comment]
@WDaan 
![desk](https://user-images.githubusercontent.com/54457152/114436587-78781200-9c00-11eb-9f41-ed5920f1f5de.png)
![mobile](https://user-images.githubusercontent.com/54457152/114436592-79a93f00-9c00-11eb-80c7-37d71fb8a6f4.png)

I adjusted the position of the check buttons.

**Comment by m4ximuel** [comment]
@WDaan 
I liked VueTorrent so much that there was a bit of source code I personally worked on.
Please work hard for a while. :D

**Comment by WDaan** [comment]
And I'm very happy with your help :). Going at it alone gets tedious achter a while

**Comment by m4ximuel** [comment]
![화면 캡처 2021-04-15 164617](https://user-images.githubusercontent.com/54457152/114833088-2c002280-9e0a-11eb-842f-6c5ad510cbba.png)
@WDaan After a few days of using it with the new layout, I realized something confusing. The blue layout doesn't attract attention because of the new red layout. For that reason, I would suggest removing that blue layout entirely and displaying and merging it into the red layout. Leave only 'Add Torrent', 'Search', and 'Settings' in the blue layout.

**Comment by WDaan** [comment]
Thanks for the detailed screenshot! That helps a lot.
I agree on merging them together. Now there are 2 places with actions which isn't very intuitive. Related actions should be grouped together.

Could you make this a seperate PR so I can try it out for myself?

**Comment by m4ximuel** [comment]
@WDaan After working with Modal.js. I will proceed with PR after completing the mentioned parts. It seems to take about 2-3 hours.

**Comment by WDaan** [comment]
Sure, no hurry at all! Work on this when you feel like it :slightly_smiling_face: 

I'm working myself, so I don't have a lot of time

**Comment by m4ximuel** [comment]
> Sure, no hurry at all! Work on this when you feel like it 🙂
> 
> I'm working myself, so I don't have a lot of time

Then, when it becomes more perfect, I will surprise you with PR.

**Comment by Asgardsurfer** [comment]
Guys, the latest update is amazing, thanks!

**Comment by m4ximuel** [comment]
#221
