### ISSUE TITLE
Root Folder Management for torrents/add Changed with qBittorrent v4.3.2

### ISSUE THREAD

**Issue by rmartin16** [WDaan/VueTorrent#215]
The qBittorrent devs made changes to how `torrents/add` works with regard to root folder management. This is part of a larger change within qBittorrent.

1) The `root_folder` param for `torrents/add` was replaced with `content_layout` starting with `v4.3.2` (`v2.7`)
2) The `create_subfolder_enabled` param from `app/preferences` was replaced with `torrent_content_layout` in the same version.

FYI: I created qbittorrent/qBittorrent#14755 to see if changes like this can be mitigated in the future.

**Comment by jbonet** [comment]
Please, this is a problem when single torrents are replaced by a pack, it can't find the content easily to not re-download everything again.

**Comment by WDaan** [comment]
@Larsluph might be fixed like in #584?

**Comment by Larsluph** [comment]
Correct
