### ISSUE TITLE
[Feature] new navigation button group design

### ISSUE THREAD

**Issue by m4ximuel** [WDaan/VueTorrent#221]
![new navigation](https://user-images.githubusercontent.com/54457152/115144631-ab9b2500-a088-11eb-89ea-7e2eca241340.gif)

Don't mind the background color
Ultimately, I'm trying to reduce the excess space on the dashboard.
How do you like this concept? I need your opinion

**Comment by WDaan** [comment]
I think it looks insane! Very impressive.

But from a UX standpoint, it might not be as clear where everything is.

**Comment by m4ximuel** [comment]
![nav](https://user-images.githubusercontent.com/54457152/115155404-cbe3d780-a0ba-11eb-97a6-06925809cdc2.gif)
It's easier to notice the change.

**Comment by WDaan** [comment]
Oh yeah! That floating tooltip is great!!
I love it!

Maybe up the contrast so it's easier to read?

PS. We still need to choose a select color

**Comment by m4ximuel** [comment]
![nav](https://user-images.githubusercontent.com/54457152/115155883-c7202300-a0bc-11eb-9dae-0a65c8582f35.gif)
@WDaan haha, I think also select color is too strong. I'm looking for a good color.

**Comment by WDaan** [comment]
Contrast on the tooltip is perfect on darkmode. Maybe a little less transparency for light mode, so it's easier to read?

How does the menu work on mobile?

**Comment by m4ximuel** [comment]
![nav](https://user-images.githubusercontent.com/54457152/115156164-f08d7e80-a0bd-11eb-86fd-17c4a9a5224f.gif)

@WDaan I changed it a little bit more opaque.

**Comment by WDaan** [comment]
It looks great! Really good job in this! :)

**Comment by WDaan** [comment]
Would like to see a PR for this as well :) 

Also for the amazing login screen you've made

**Comment by m4ximuel** [comment]
@WDaan I'm currently looking for 'disadvantages' and 'bugs'. PR soon.

**Comment by m4ximuel** [comment]
@WDaan The login modal is now combined with a new technology. Offline notification and waiting for login response. I also planning a new design for desktop mode only.

**Comment by WDaan** [comment]
Damn, you got a lot of things going on right now! 😮

**Comment by m4ximuel** [comment]
@WDaan Half of the functions I'm pull request have been working on since 3 months ago and the other half have recently started working on them. I was thinking about using it just personally but started sharing it. Thank you for your kindness and you are my github teacher.

**Comment by WDaan** [comment]
Well I'm very glad you started sharing them, you're doing great work and getting lots of valuable experience 🙂

**Comment by m4ximuel** [comment]
@WDaan 
![nav](https://user-images.githubusercontent.com/54457152/115594183-6852e780-a310-11eb-9dbe-8bacd4519fd3.gif)
Testing whether gradients are effective for status notifications.
