### ISSUE TITLE
[Feature] new select mode color

### ISSUE THREAD

**Issue by m4ximuel** [WDaan/VueTorrent#226]
![sel color](https://user-images.githubusercontent.com/54457152/115183901-acc76300-a117-11eb-84f8-7d2627fa3142.png)
How about just using the state color?

**Comment by WDaan** [comment]
It looks okay, but isn't that just confusing?

**Comment by m4ximuel** [comment]
@WDaan It's better than blue, but I agree that it's not the best yet.
First, would you like to try it yourself and decide it? I will include it in the nav menu PR.

**Comment by WDaan** [comment]
Sure :)

**Comment by m4ximuel** [comment]
#221
