### ISSUE TITLE
Problem with CSS and page title

### ISSUE THREAD

**Issue by Mehdib92** [WDaan/VueTorrent#229]
I just moved from 0.7.0 to 0.9.0 by replacing the files on the last version of qBittorrent.

Since that, I encountered 2 problems :

- On the left panel, every second the scrollbar show then hidden...
- On the page title, the Download speed and the upload speed are inverted

**Comment by m4ximuel** [comment]
1. The problem cannot be reproduced. Please let me know in more detail. environment, etc...
2. The title issue will be resolved in the next version.
