### ISSUE TITLE
[Feature] Dashboard graph

### ISSUE THREAD

**Issue by m4ximuel** [WDaan/VueTorrent#232]
![torrent graph](https://user-images.githubusercontent.com/54457152/115323926-f077a680-a1c3-11eb-94fa-8dde09ecdc33.png)
The activated torrent is noticeable and visually beautiful.

**Comment by WDaan** [comment]
Looks super cool! But how about performance??

**Comment by m4ximuel** [comment]
@WDaan I have defined how to draw a graph. Therefore, I am optimizing the code. For example, the current code has String operations but changed to Array operations.
But at least it'll be a hell of a lot faster than using Apex charts.

**Comment by WDaan** [comment]
It looks great and I know it's more performant than Apex. But isn't drawing a graph on every single item in the dashboard, resource intensive?

**Comment by m4ximuel** [comment]
@WDaan About 7 columns count resources will be added per dashboard item.

**Comment by m4ximuel** [comment]
![dash](https://user-images.githubusercontent.com/54457152/115346204-d7ceb700-a1ea-11eb-89c1-ea9bdc77c34f.png)

**Comment by LukePrior** [comment]
Very cool looking indeed.

**Comment by m4ximuel** [comment]
@WDaan Since it was designed inside torrent.vue, I confirmed that it only updates the item. The downside is that when page is turned over, all graphs start over at zero. It seems to be perfect in performance.

**Comment by WDaan** [comment]
Than I'd love to have it! Looks insanely cool!

**Comment by m4ximuel** [comment]
@WDaan Any ideas to make it a little prettier in drawer? Shall we insert a gradient mask on the left and right?

**Comment by WDaan** [comment]
Perhaps a little more rounded to fit the rounder design?

Gradients would be nice as well

**Comment by m4ximuel** [comment]
@WDaan I want to try it, but you mentioned the most difficult feature to implement. I'll burn my brain sooner or later. please cheer for good results.

**Comment by WDaan** [comment]
Yes I know 😅😅

We don't NEED to do that, it's just suggestion. I really like it the way it is allready! :)

**Comment by m4ximuel** [comment]
@WDaan I want to do it, but it's a feature I've been trying to deny. your suggestion led to victory in the fight with myself. Anyway, researching.

**Comment by WDaan** [comment]
Allright, great! 

Don't put TOO much time in it though!!

**Comment by m4ximuel** [comment]
![graph](https://user-images.githubusercontent.com/54457152/115396952-817c6b00-a220-11eb-8f23-7d3de1ba020f.png)
@WDaan Quadratic Bézier
The graph now has a more natural curve than the 'apex charts'.

**Comment by LukePrior** [comment]
> Quadratic Bézier

Will you be using these new graphs for downloads and uploads?

**Comment by WDaan** [comment]
Oh my god!! Those are amazing! I think they look even better than the Apex ones! Really great job on those! :) 
I would LOVE to see a PR for this

**Comment by WDaan** [comment]
@LukePrior Yes, it's the plan too use these for download/upload.

Possibly also per torrent on the card, as shown in this issue. Not sure wether this will become standard or a setting users will have to enable.

**Comment by m4ximuel** [comment]
![redesign](https://user-images.githubusercontent.com/54457152/115400942-caceb980-a224-11eb-821b-6092558a9e26.png)

@WDaan @LukePrior 
PR is ready.  #233
