### ISSUE TITLE
[Feature] Active use of context menu

### ISSUE THREAD

**Issue by m4ximuel** [WDaan/VueTorrent#241]
![detail context](https://user-images.githubusercontent.com/54457152/115817290-8403de00-a435-11eb-8fbd-7562e2fc2d39.png)
![nav context](https://user-images.githubusercontent.com/54457152/115817292-85350b00-a435-11eb-9f5f-572d3779e052.png)
Currently, it can be used with two method.
1. Assign 'TorrentRightClickMenu.vue' to each modal of 'Torrent details' and 'navigation'
or
2. Emulate click or touch to 'Dashboard.vue'

I am using method 2 Considering the compatibility, it seems best to imitate the user. But on the one hand, it's uncomfortable.
Any better ideas to do the same thing?

As a side note, The purpose of doing this is to make 'context-menu' as a public controller.

**Comment by WDaan** [comment]
I think it's great you can access the context menu on the modal! Very convenient.

Perhaps of directly mounting the context menu on the dashboard, we turn it into a 'modal' so we can spawn it anywhere?

**Comment by m4ximuel** [comment]
@WDaan Um... or is there a way to deliver the command directly to 'Dashboard.vue'? For example, how to use mutation.

**Comment by WDaan** [comment]
You would probably need to use the store and watch data from there. Which isn't really a nice way to do it, if It think about it

**Comment by m4ximuel** [comment]
@WDaan 
openMenu() {
      if (this.touchTick) {
        ...dispatchEvent(new TouchEvent('touchstart', {... // 1 finger first
        ...dispatchEvent(new TouchEvent('touchstart', {... // 2 finger
      } else {
        ...dispatchEvent(new MouseEvent('contextmenu', { ...
      }
    }

Currently, I'm using this code to command to 'dashboard'.
Is this for sure and for the best at the momentarily?

**Comment by WDaan** [comment]
I think there is no cleaner way to do it at the moment, this is probably fine 🙂

**Comment by m4ximuel** [comment]
#249
