### ISSUE TITLE
Option If You Want Auto Install Search Plugins

### ISSUE THREAD

**Issue by AyaanZaveri** [WDaan/VueTorrent#242]
I only want to use the Jackett search engine but every time I refresh the page all of them come back. Is there a way you can add a toggle if this **[feature](https://github.com/WDaan/VueTorrent/commit/abc5457882892ce4840ae0eef7a438e5ea4c7c90)** should be enabled or not?

**Comment by WDaan** [comment]
Has been resolved in #443
