### ISSUE TITLE
[Feature] Global QoS

### ISSUE THREAD

**Issue by red-machine95** [WDaan/VueTorrent#246]
Is it possible to add the global QoS option?

Sometimes I notice that my internet connection is slow, because the active torrents use up my bandwidth.

I'm having trouble activating this option on this interface...

**Comment by red-machine95** [comment]
@WDaan Any news about this feature?
This interface is great, but without this functionality, it's a big downgrade for me.

**Comment by WDaan** [comment]
I don't want to sound insensitive, but that is your problem. I don't force you to use this.
If you want it that bad, feel free to submit a PR.
I work on this in my free time when I feel like it, I'll get to it when I get to it.
