### ISSUE TITLE
[Feature] Allow copy text from modals

### ISSUE THREAD

**Issue by IevgenSobko** [WDaan/VueTorrent#251]
Since modals redesign, it is not possible to copy text from modals.
I use this functionality from time to time to copy some necessary information and apply it to other torrents, like some custom paths.
It would be great to have the ability to copy text from modals again.

**Comment by m4ximuel** [comment]
This is currently allowed in the delete comfirm modal.
In my opinion, rather than allowing text selection, it would be better to include a function that copies the text when double-clicked in certain situations (e.g. torrent information modal).

**Comment by IevgenSobko** [comment]
It is ok with me to have the ability to copy information just from the torrent info values table.
Maybe some icon like copy code snippets on other websites..., double click like you suggested, or both.

**Comment by m4ximuel** [comment]
@IevgenSobko yes I think it's great way. icon is more better.
