### ISSUE TITLE
Torrent card context menu font inconsistency

### ISSUE THREAD

**Issue by IevgenSobko** [WDaan/VueTorrent#252]
`Set Priority` and `Set Categoty` submenus have their text fonts decreased in comparison with other submenus

![2021-05-02__11-55-44](https://user-images.githubusercontent.com/14232100/116807874-4b9f8680-ab3e-11eb-9f08-1b2b30f56fd9.png) ![2021-05-02__12-02-27](https://user-images.githubusercontent.com/14232100/116807876-4cd0b380-ab3e-11eb-83c1-11a745bef728.png)

**Comment by m4ximuel** [comment]
I found this issue when working with the right-click menu, but decided to put it on hold. If the font size is unified, users with many tags will get excessive menu area. I'll add a lot of tags later and think about how to modify them.

**Comment by WDaan** [comment]
I think this was resolved during Hacktoberfest
