### ISSUE TITLE
Horizontal scrollbar in 'Add a new Torrent' window not working

### ISSUE THREAD

**Issue by mcollins1290** [WDaan/VueTorrent#254]
Hi,

I installed the latest version of VueTorrent (v0.10.0) this morning and I am finding that in both the latest versions of Chrome and Edge that the horizontal scrollbar in the ‘Add a new Torrent’ window is not working for me. I quite often use Magnet links where those links can be rather long and more often than not the horizontal scrollbar will have to appear when I copy and paste the Magnet URL into the ‘URL’ field. I then find that I am unable to scroll down and click on the ‘Add Torrent’ button because the scrollbar does not appear to work. Instead, when I try to click on it, the ‘Add a new Torrent’ window closes.

Versions of software I am using:
Browser OS: Windows 10
Chrome: 90.0.4430.93 (Official Build) (64-bit)
Edge: 90.0.818.51 (Official build) (64-bit)
Server OS: Raspbian GNU/Linux v10.9 (buster)
Apache: 2.4.38
qBittorrent: v4.3.4.1

Finally just to add that before testing the new version of VueTorrent released last night, I completely cleared both the Chrome and Edge Browser cache and History and even tried testing in a Private window of both browsers and the behavior is the same. Oh and I should mention that scrollbars in the Settings window on the various tabs work as expected.

Thanks,
Martin
![scrollbar](https://user-images.githubusercontent.com/38381180/116815718-cf507780-ab2c-11eb-94c2-2402535fb1c6.png)

**Comment by m4ximuel** [comment]
This is the part that I couldn't check while removing dependencies. I will create a PR later. Thank you for the report.

**Comment by mcollins1290** [comment]
Thank you so much @m4ximuel . If you commit a fix then let me know. I would be more than happy to test it for you.
