### ISSUE TITLE
search result text too dark when using dark theme

### ISSUE THREAD

**Issue by binhex** [WDaan/VueTorrent#257]
Could the text colour for the search result please be changed, as the dark blue/grey against a black background is very hard to see (at least for me it is). i understand that the text colour follows part of the dark theme colours used, but perhaps you could use the same colour as the search icon (green), as i think it would make it a lot more readable, example screenshot included:-

![image](https://user-images.githubusercontent.com/1121837/117114274-87775d80-ad83-11eb-94e6-5b50a75e9a02.png)

**Comment by WDaan** [comment]
Yup, you're right... this should definitely be tweaked

**Comment by WDaan** [comment]
Has been resolved
