### ISSUE TITLE
Run external on torrent completion - nonexisting?

### ISSUE THREAD

**Issue by morganzero** [WDaan/VueTorrent#258]
Hi there,
First and foremost, I love VueTorrent. However, I'm not sure if I missed it but it doesn't seem like your "theme" supports "Run external on torrent completion".

Below is an example of settings I'm currently using with qBit, and I would love the ability to use your theme in combination with my settings. 
![image](https://user-images.githubusercontent.com/57449785/117131502-ce744b80-ada1-11eb-893f-36ce160b5cae.png)
Thank you!

**Comment by WDaan** [comment]
I think this might be possible, yeah 
I don't know when I'll get to it though, so please be patient.
Thx for using vuetorrent! 🙂 

(link for self reference) [link](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-application-preferences)

**Comment by morganzero** [comment]
> I think this might be possible, yeah
> I don't know when I'll get to it though, so please be patient.
> Thx for using vuetorrent! 🙂
> 
> (link for self reference) [link](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-application-preferences)

Thanks mate! :) appreciate your good work!

**Comment by WDaan** [comment]
You can leave it open, I see it as a To-Do list 😝

**Comment by morganzero** [comment]
Alrighty :)
