### ISSUE TITLE
[Feature] Torrent right-click menu guide text

### ISSUE THREAD

**Issue by m4ximuel** [WDaan/VueTorrent#260]
![sel1](https://user-images.githubusercontent.com/54457152/117193197-898dfa80-ae1d-11eb-8d6c-08c0c02df5e0.png)
single

![sel2](https://user-images.githubusercontent.com/54457152/117193201-8abf2780-ae1d-11eb-9d20-d578bcb33f8f.png)
multiple

It shows more clearly which item has been selected

**Comment by WDaan** [comment]
Pretty cool!

**Comment by m4ximuel** [comment]
@WDaan 
![화면 캡처 2021-05-17 162248](https://user-images.githubusercontent.com/54457152/118447781-25780a00-b72c-11eb-84ef-558e8c2a9fa2.png)
I modified the overall size little by little. It is controlled by css. Would it be okay?

**Comment by WDaan** [comment]
haven't seen the code, but look great to me anyway
