### ISSUE TITLE
Proxy Settings?

### ISSUE THREAD

**Issue by bigdork** [WDaan/VueTorrent#261]
I must be missing it, where are the proxy server settings? SOCKS5, etc?

**Comment by WDaan** [comment]
No, you are not missing anything. Not all the settings have been implemented as of yet. I started with the most frequently used and went from there.

**Comment by milindpatel63** [comment]
want this as well...
timeline for when this will be added?

**Comment by BaIanced** [comment]
Proxy settings would be super useful! :)
