### ISSUE TITLE
[ Feature ] new layout concept for torrent list

### ISSUE THREAD

**Issue by m4ximuel** [WDaan/VueTorrent#263]
![Animation](https://user-images.githubusercontent.com/54457152/118091757-29431e00-b406-11eb-9c4f-8ecaf8ce5251.gif)
![화면 캡처 2021-05-13 161916](https://user-images.githubusercontent.com/54457152/118094164-5cd37780-b409-11eb-8bc0-07413081e1b5.png)

I hope to pursue a layout integrated with mobile devices and desktop devices.
Please take a look at the rough concept and leave a review.

**Comment by WDaan** [comment]
The numbering is cool but I don't know if it is thát usefull.

So you want to use the same layout for both mobile and desktop? You sure thats a good idea? I feel like the desktop should show more info like it does now. Or perhaps we should finally start the table layout 😅

**Comment by m4ximuel** [comment]
@WDaan Let's just choose the good ones that we agree with. And, How about to hide the progress bar for downloaded items? I will apply the numbering design later.

**Comment by WDaan** [comment]
Yes, hiding the downloadbar for items that are done, does make sense. Makes it easy to dinstinguish them at first glance

**Comment by m4ximuel** [comment]
@WDaan How about grouping a few items together and using icons instead of titles? For example, it looks good to bind 'Downloaded' and 'Uploaded'.

**Comment by WDaan** [comment]
I cant imagine it 😅 how would you do that? Can you do like a quick sketch mockup drawing?

**Comment by m4ximuel** [comment]
@WDaan 
![a](https://user-images.githubusercontent.com/54457152/118387907-1aee3f80-b65c-11eb-91d6-958d278d6328.png)

I think 'Downloaded' and 'Size' can be group and 'Uploaded' and 'Ratio' also can be group.

**Comment by ManCaveMedia** [comment]
For downloads in progress I have Download, Downloaded, Seeds and Availability enabled, which can be grouped like suggested.

For completed downloads I replace them with Upload, Uploaded, Peers and Ratio, which can be grouped too.

**Comment by WDaan** [comment]
Seems like a very efficiënt way to show a lot of information! 🙂 
Perhaps we can just add some more configurable components?

**Comment by m4ximuel** [comment]
@WDaan It is possible to apply a few changes from the existing method, but it seems that the priority is to upgrade the method of saving the settings before modifying the settings.

**Comment by WDaan** [comment]
Perhaps 😅 but that's a bit more difficult and less fun

**Comment by m4ximuel** [comment]
@WDaan The new design concept is going to evolve a bit, let's slowly improve the way we store the settings. 😄

**Comment by m4ximuel** [comment]
![normal image](https://user-images.githubusercontent.com/54457152/118434163-8812db00-b717-11eb-980a-dd41b633eef2.png)

![desc image](https://user-images.githubusercontent.com/54457152/118434158-877a4480-b717-11eb-9a4b-bfe69d32ba56.png)

1. Add on date. Always display.
2. Content area. Contains components related to various torrent information.
3. Each component (or grouped component) has a fixed size. This way, for each torrent, the components are in the same location, giving a sense of stability and unity.
4. Display the index of the torrent aesthetically. You can recognize it easily and it unobtrusive.

Personally, I would like to recommend this as an integrated design. In the case of the desktop area you are concerned about, I recommend to implement it in the following way. designate the five items currently displayed in the concept design as 'fixed content', and display the 'additional content' customized by the user afterwards.

**Comment by WDaan** [comment]
Thanks for the detailed explanation/analysis 🙂!
I think it's great. It's clean, uniform, easy to understand.
It gives a lot of info at first glance & if they want more detail they can see it in the info modal.
Also, I think it's nice to keep some of the customisable parts as you suggested 🙂

**Comment by NayamAmarshe** [comment]
> @WDaan
> ![a](https://user-images.githubusercontent.com/54457152/118387907-1aee3f80-b65c-11eb-91d6-958d278d6328.png)
> 
> I think 'Downloaded' and 'Size' can be group and 'Uploaded' and 'Ratio' also can be group.
> I would like to suggest a direction to minimize the amount of information while maintaining it.

This is amazing
