### ISSUE TITLE
[Features] Looking forward to providing a multilingual version

### ISSUE THREAD

**Issue by tobylibo** [WDaan/VueTorrent#264]
I have to express my gratitude to the developers. This is a very exciting project. It would be better if it could provide a choice of languages. Expect developers to provide multi-language versions.

**Comment by m4ximuel** [comment]
He said he wanted to support multilingualism. But I can't explain the period because we're busy right now.

**Comment by WDaan** [comment]
Thank you for taking an interest in the project!

As @m4ximuel says, I allready said I was going to...as specified in #150 but I don't have the time right now (thesis due in 2 weeks)
