### ISSUE TITLE
Show item count after category

### ISSUE THREAD

**Issue by Askadelion** [WDaan/VueTorrent#268]
Hi, How can i Setting the count of torrents after the Catecory name as in the original web interface

![grafik](https://user-images.githubusercontent.com/41443013/122102464-bb7b7f00-ce15-11eb-9b34-14b2312754fd.png)

In your UI, the number of torrents is at the bottom, but I would like to have it right next to the category name. Is there any way I can set or change this?

![grafik](https://user-images.githubusercontent.com/41443013/122102515-c9c99b00-ce15-11eb-888e-58f7473cdd08.png)

**Comment by WDaan** [comment]
No, at the moment this is not possible 🙁
