### ISSUE TITLE
Unraid

### ISSUE THREAD

**Issue by foXaCe** [WDaan/VueTorrent#27]
hello,
i use qbittorent on UnRaid docker version.
your theme works on this ?
how please ?
thank you.

**Comment by WDaan** [comment]
My own UnRaid server is a bit broken atm. So I cant really screenshot in detail...but in general:

- Download, unzip the release & place it on the server
- create the QBit docker & add an extra volume mount which points to the unzipped vuetorrent folder.
- in the default QBit WebUI, set the alternative path to the volume mount you've created in the previous step.

You can look at the docker-compose.yml in this repository, it's basically the same.
In my default QBit WebUI, I set the path to '/vuetorrent'


I hope that helps!

**Comment by foXaCe** [comment]
like this ?

/mnt/user/Download/UI/vuetorrent

**Comment by foXaCe** [comment]
Unacceptable file type, only regular file is allowed.

**Comment by WDaan** [comment]
So you download the 'release.zip', when you extract it... it contains a folder called vuetorrent.
Place this folder somewhere on your server.

![](https://ipsassets.unraid.net/uploads/monthly_2019_02/Plex006.PNG.68351d80e5d864eafc208c39b10630ca.PNG)

(I found this picture somewhere on internet)

Host path => where you've place the 'vuetorrent' folder
Container path => type something like '/vuetorrent'


finally in your default WebUI, you set it like in the picture below.

![image](https://user-images.githubusercontent.com/25707052/91661145-68c91480-eada-11ea-87e6-ce14e99b87a4.png)

**Comment by foXaCe** [comment]
ok now it work
thank you for help me

**Comment by WDaan** [comment]
Great! I'm glad you got it working.
I hope you like it!😄
