### ISSUE TITLE
Add new torrent layout broken on moblie and on computer

### ISSUE THREAD

**Issue by Nilon123456789** [WDaan/VueTorrent#270]
The add new torrent when using a magnet url is broken.
![image](https://user-images.githubusercontent.com/51246940/124291346-7bf5a800-db22-11eb-9c13-bd3bed6207cd.png)

**Comment by WDaan** [comment]
Any more info about the issue you're experiencing? :sweat_smile: 

Is it not getting added? Or is it some UI bug?
