### ISSUE TITLE
Wrong background on floating speed informations when using dark theme

### ISSUE THREAD

**Issue by Dalfrak** [WDaan/VueTorrent#271]
Hello,

As you can see, it has the wrong background color when using dark theme, so we can't see what's wrote.
(and maybe the wrong theme is applied to this popup when using light theme)

Dark Theme :
![image](https://user-images.githubusercontent.com/16808381/124952099-4108de00-e014-11eb-861a-18a0d76a9bac.png)

Light Theme:
![image](https://user-images.githubusercontent.com/16808381/124953025-0ce1ed00-e015-11eb-8ee9-54af2e880a3b.png)

Thx for your great work, and gl maintaining it ! :D

**Comment by WDaan** [comment]
Seems like a silly mistake indeed, thanks for submitting the issue!

You're right, maintaining gets harder with a fulltime job 😅

**Comment by WDaan** [comment]
Are you sure you're on the latest version? I can't seem to reproduce the issue

**Comment by Dalfrak** [comment]
I'm on the version 0.10.0, the latest I see on the release page. But I didn't touch anything and now the theme is correct ... It's kinda weird 😅

**Comment by WDaan** [comment]
Have you tried clearing browser cache? 

What browser are you using? 

I tried it this morning in Chrome and couldn't reproduce the issue

**Comment by Dalfrak** [comment]
Nah, I did nothing and the "bug" is solved !?
(And I'm using Firefox 89.0.2 (64bits))

**Comment by WDaan** [comment]
On the one hand....great!


On the other hand it would be nice to know what caused it

**Comment by Dalfrak** [comment]
Yeah xD
Sorry for wasting your time on that 😅

**Comment by WDaan** [comment]
No worries! :)
