### ISSUE TITLE
feature: replicate default webui copy name / hash context menu functions

### ISSUE THREAD

**Issue by beyondmeat** [WDaan/VueTorrent#277]
I select torrents and use the context menu to copy the torrent names with the default webui, can't do it with vuetorrent.

Also can't select to copy any text in the info panel.

**Comment by BachoSeven** [comment]
@WDaan, I just tested this on the new version, and it doesn't work(i.e. clicking on copy and then any of the three options didn't copy anything onto my clipboard).

System: Arch Linux, `qbittorrent-vuetorrent-bin`(AUR package), latest qbittorent-nox version.

**Comment by WDaan** [comment]
Which browser are you using? I only tested on chrome because I thought it was standardised functionality

**Comment by BachoSeven** [comment]
`ungoogled-chromium`, version 92.0.4515.131

**Comment by BachoSeven** [comment]
I also tried it on `Vieb`(an Electron-based browser), and I get the same behaviour.

**Comment by WDaan** [comment]
Tested on Chrome, Safari and Firefox & didn't notice any issues.

**Comment by BachoSeven** [comment]
I also tested it on Firefox, and it doesn't work. Opening console, I noticed this:

```
TypeError: navigator.clipboard is undefined
    copyToClipBoard TorrentRightClickMenu.vue:407
    click TorrentRightClickMenu.vue:11
    VueJS 4
        ie
        n
        ie
        $emit
    click VListItem.ts:126
    VueJS 3
        ie
        n
        _wrapper
vue.runtime.esm.js:1897:12
```

And then I thought of also looking at Chromium's console:
```
vue.runtime.esm.js:1897 TypeError: Cannot read property 'writeText' of undefined
    at o.copyToClipBoard (TorrentRightClickMenu.vue:407)
    at click (TorrentRightClickMenu.vue?18e3:11)
    at ie (vue.runtime.esm.js:1863)
    at o.n (vue.runtime.esm.js:2188)
    at ie (vue.runtime.esm.js:1863)
    at o.In.t.$emit (vue.runtime.esm.js:3903)
    at o.click (VListItem.ts:126)
    at ie (vue.runtime.esm.js:1863)
    at HTMLDivElement.n (vue.runtime.esm.js:2188)
    at HTMLDivElement.Qr.a._wrapper (vue.runtime.esm.js:6961)
```

**Comment by WDaan** [comment]
Thank you for this! It means for some reason the clipboard API is not supported for both your browsers 😮😮

The compatibility list is shown [here](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard), it should be globaly supported 🤔🤔

**Comment by BachoSeven** [comment]
But I installed stock Firefox(!)

**Comment by WDaan** [comment]
I believe you 😅 you don't have to convince me.
I'm just trying to figure out why it does not work for you

**Comment by BachoSeven** [comment]
Sorry I thought by both browsers you meant the chromium-based ones I mentioned earlier.

Maybe this is relevant, since I don't use https on the server and the linked issue mentions that:

https://github.com/storybookjs/storybook/pull/13777/files

**Comment by WDaan** [comment]
Well after some further reading [here](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard) and [here](https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API). It might be due to a permission issue. I will have to investigate on what to use as a fallback

**Comment by beyondmeat** [comment]
I tried the latest release and it works for me. However it only works for a single torrent selected. The qbit webui allows multiple torrents to be selected and you can still copy the name, hash, and url. Select multiple torrents and copy the name, it will put each name on a single line, so when you paste you have a list of torrent names.

Please make this work with multiple torrents are selected. Right now the copy menu isn't an option when multiple torrents are selected.

**Comment by WDaan** [comment]
Just out of curiosity... When do you actually need to copy the name/hash/magnet of multiple torrents? What is the use case?

**Comment by beyondmeat** [comment]
I have a script that copies my torrents and renames them.

I paste the names of the torrents (which matches the download location). The script knows where the torrents are, adds the torrent name to the path, copies the downloaded torrent files and processes them.

It's a slightly manual process but it works. I also used that in cases where I want to compare the list of torrents in my client to another list.

Sure, I could find a way to automate it by working with the client API or something  but the manual process of copying the names hasn't bothered me that much yet.

As for magnets, I could see the use case for quickly copying torrents from one client to another.

**Comment by WDaan** [comment]
Thanks for the explanation!

**Comment by beyondmeat** [comment]
@WDaan unfortunately, the latest versions of Edge, it no longer copies to the clipboard.

I recommend looking at the copy button that github now has. (Could be a feature preview, so check that if you don't see it below).

```
copy test passed
```

You should be able to view the source and dig in to find the JS code they are using to copy to the clipboard and use that in VueTorrent.

**Comment by lieuweberg** [comment]
This is a permissions issue. The Clipboard API is only available in secure contexts, meaning pages served over HTTPS, localhost or 127.0.0.1.

If you want to bypass this for a chromium browser you can head to `chrome://flags/#unsafely-treat-insecure-origin-as-secure` and add your domain/ip to the list in the supported format (i.e. `http://192.168.178.60:8989`), then enable the feature.

Better would of course be to reverse proxy your site with something like ✨ caddy ✨ or nginx.

**Comment by WDaan** [comment]
Thanks for the analysis!

My proxy of choice is NginxManager 🙃
