### ISSUE TITLE
[Bug] QBittorrent no longer has default search plugins??

### ISSUE THREAD

**Issue by WDaan** [WDaan/VueTorrent#289]
## Description
It seems that Qbittorrent no longer has default search plugins, please investigate.

**Comment by kusky3** [comment]
qbittorrent still has default search plugins

**Comment by WDaan** [comment]
This list used to be pre-loaded by default, but that no longer seems to be the case
<img width="801" alt="Screenshot 2021-11-27 at 11 44 25" src="https://user-images.githubusercontent.com/25707052/143677968-2f070adf-c046-4a89-aded-1be744d8719b.png">

**Comment by kusky3** [comment]
if you click on check for updates it will show the default plugins

**Comment by WDaan** [comment]
not working for me on `qBittorrent v4.3.9`

**Comment by kusky3** [comment]
remove  ~/.local/share/qBittorrent/nova3
and retry

**Comment by kusky3** [comment]
i'm also using 4.3.9 and i get the default plugins
(archlinux package)

**Comment by WDaan** [comment]
Removed my config folder but didn't seem to make a difference 
I'm using `linuxserver/qbittorrent:latest`

**Comment by kusky3** [comment]
did you check the  [SearchEngines] section in .config/qBittorrent/qBittorrent.conf?

**Comment by kusky3** [comment]
https://github.com/linuxserver/docker-qbittorrent/issues/90

**Comment by calebsw83** [comment]
I'm on 4.4.3.1 and also having this issue. I also cannot manually add plugins. Just wanted to keep this thread alive since it might not be resolved yet.

**Comment by WDaan** [comment]
Seems to be resolved
