### ISSUE TITLE
Could you please add the category

### ISSUE THREAD

**Issue by ManCaveMedia** [WDaan/VueTorrent#29]
First of all I want to let you know I love the looks of the WebUI you made! My compliments!

I have a suggestion, in case you take them:
Could you please add the category to the view?

I use categories a lot, so a webUI without the category is'n very helpfull to me.
For example: some of my media managers change the category on an imported download to imported. This way I know it's save to remove manually after the upload ratio is reached. 

So just a column showing the category on the main view would do.
Thanks. :)

**Comment by WDaan** [comment]
Thank you very much! It's always nice to hear that people like it.

I'm taking a look at categories right now!

**Comment by calegendre** [comment]
I'm impressed. It looks slick, feels slick.... but I definitely wish under the sidebar (as OP suggested) - a sort by Categories and a sort by Status option, so you could see "seeding" or "downloading" or "completed" easily - and so you could see categories only as well. Not a selection of one plus the other - but just be able to select one or the other... 

Keep up the great work, it's a beautiful thing!

**Comment by WDaan** [comment]
Thanks for the kind words!

I will look into it when I finish the category stuff. (It's almost done)

**Comment by ManCaveMedia** [comment]
Wow, didn't expect you to respond this fast!
Will provide more feedback soon to help you make this project even better...
