### ISSUE TITLE
Unacceptable file type, only regular file is allowed.

### ISSUE THREAD

**Issue by DirtDiver4x4** [WDaan/VueTorrent#299]
Been using the VueTorrent UI for Qbit for a few months now and until recently it has worked great. But now the UI is not accusable and I get the "Unacceptable file type, only regular file is allowed." message. I'm using the binhex-qbittorentvpn container in Unraid and have also tried it with every other version of Qbit available in the Unraid following the video by IBRACORP on YouTube. The only one that works is the one that comes with VueTorrent baked in already. The obvious answer is to just use the one that comes with it but unfortunately that one isn't set up for a VPN nor is the VPN version set up to use OpenVPN only Wireguard. So is there's a way to fix this or am I just screwed?

**Comment by WDaan** [comment]
Please check out the [FAQ](https://github.com/WDaan/VueTorrent/wiki/FAQ)
