### ISSUE TITLE
How to access the interface on Windows?

### ISSUE THREAD

**Issue by askfriends** [WDaan/VueTorrent#300]
Hello;
Sorry for the very basic and noob qsuestion but im really confused being new to this, and couldnt find the answer anywhere.

I have downloaded the release package and unzipped in my C:/ drive, then given that path in Qbittorrent>Options>WEB UI>Use alternative WEB UI

Now where i can access the new Interface?
I restarted qbittorren and its still the same as old GUI

**Comment by MrComexs** [comment]
It's a web ui. You have to enable remote access and open your browser with your ip and put the port. Example 192.168.0.123:8080

**Comment by askfriends** [comment]
> 192.168.0.123:8080

Thank u so much, it surely helped and finally im able to see it.
Just to put it on record;

Find whats your ip address and put that in qbittorrent Options>WEB-UI>Ip Address

And just put that in any browser like;
Your-Ip-Address:8080
192.168.0.123:8080
