### ISSUE TITLE
[Feature Request] Active Uploads - Color Change

### ISSUE THREAD

**Issue by ooglyboogly** [WDaan/VueTorrent#301]
Since seeding and active uploading look the same minus the Speed rate, it would be nice if the UI had some color change to indicate visibly which torrents are actively uploading. 

One possible implementation would be: if upload > 0 AND status is SEEDING, make the Text of the Torrent name the color of `upload--text`.

Visual example:
![image](https://user-images.githubusercontent.com/2380915/135701634-270f2fae-c566-4891-84b5-ab5d3fc70ac5.png)

**Comment by JStrongy** [comment]
This would be pretty cool!

**Comment by jagadam97** [comment]
https://github.com/WDaan/VueTorrent/pull/1035
