### ISSUE TITLE
Want to set tags in batch

### ISSUE THREAD

**Issue by ted423** [WDaan/VueTorrent#305]
the orignal webui can do it

**Comment by ted423** [comment]
Hope to add more batch features
Like set location ,change tracker

**Comment by SawkeeReemo** [comment]
Agreed. I'm incredibly happy to finally be able to access qBT via mobile, and this interface is really nice. But I use tags a lot to help manage things.

**Comment by reyqn** [comment]
I often use set location, on the webUI and other apps, it pre-fills the field with the location of the first torrent I selected, which is really useful to set the same location on new torrents without typing it. This would be a really nice addition.

**Comment by Larsluph** [comment]
Fixed with #570, can be closed @WDaan
