### ISSUE TITLE
click to paste magnet in add torrent modal

### ISSUE THREAD

**Issue by sintax69** [WDaan/VueTorrent#307]
adding a magnet link to new torrent can only add using ctrl v no right click paste into url

**Comment by vtruong68** [comment]
I might be blind but where is the new paste button? Right-clicking still does nothing and the seemingly clickable button to the left of the URL field doesn't seem to do anything either.

![image](https://user-images.githubusercontent.com/31712352/205418415-8ce05d0e-6d2c-43a4-9b6e-3a59e4e4142d.png)
