### ISSUE TITLE
Please add ability to set Share Limit by torrent

### ISSUE THREAD

**Issue by parsedout** [WDaan/VueTorrent#308]
Hi, this UI is amazing but it lacks one critical feature I need for my workflow.  The base qbittorrent UI allows to set the share ration limit by torrent, if you could add that to the "Set Limit -> Upload" section that would be amazing and hopefully not too difficult?  Thank you for the work you put into this and keeping it maintained.

**Comment by WDaan** [comment]
I've started with a simple share modal, that can set the ratio. Which I think is the most used.
Will add the time limit soon

**Comment by parsedout** [comment]
Thank you, that works well.  One issue, once you set the share limit, if you go back into to change or remove the share limit (back to infinite) it doesn't show the current share limit in the text box.  Not the end of the world and it functions, but a minor bug that I thought I'd share.  Appreciate this feature addition very much!

**Comment by WDaan** [comment]
I now have a version like this, with 2 sliders. 
I believe it's the most intuitive way to get both the value/unlimitted/ use global limit inside of 1 UI component.
(As you can see, still WIP because the labels are still too small)
The only downside to using this, is that it's not very easy to use for setting time limits.... because of the big values
Let me know what you think
<img width="547" alt="Screenshot 2021-11-03 at 08 56 25" src="https://user-images.githubusercontent.com/25707052/140025538-e3f62d9b-afbf-4c9c-8c93-3a33bbf4d659.png">

**Comment by westernstatesflooring** [comment]
I think the slider has potential but I agree it may be difficult.  What do you think about having a text box to enter a specific value (like you have now) and next to that a radio set (or a 3 way toggle?) for use custom/override, unlimited or global limit and if one of those are selected it disables the text box?  Might be a bit more intuitive?  Or maybe just a text box and if the value is left null it defaults to the global limit and if you put a value in it overrides it, just that simple?

**Comment by parsedout** [comment]
I think the slider has potential but I agree it may be difficult. What do you think about having a text box to enter a specific value (like you have now) and next to that a radio set (or a 3 way toggle?) for use custom/override, unlimited or global limit and if one of those are selected it disables the text box? Might be a bit more intuitive? Or maybe just a text box and if the value is left null it defaults to the global limit and if you put a value in it overrides it, just that simple?

**Comment by WDaan** [comment]
> Or maybe just a text box and if the value is left null it defaults to the global limit and if you put a value in it overrides it, just that simple?

Skipping unlimited altogether? 🤔
I think that if there's no global limit, that global limit === unlimited. But I would have to test that to confirm.

If that's the case than I wouldn't write off the slider just yet...

I can, for example, make sliding it all the way to the left show an infinite symbol & everything else it's value. For ratio I can maybe do 0.5 increments up to 5 & for time limit some smarter logic that increases the duration exponentially, e.g. 5min, 30min, 1h, 6h, 1d or something like that.

Making the whole experience a little bit more intuitive than the original UI.

**Comment by WDaan** [comment]
Or do the above and a toggle for unlimited that disables the slider 🤔

**Comment by parsedout** [comment]
From a UX perspective I personally like toggles, they are universally
intuitive.

**Comment by WDaan** [comment]
True, but 2 toggles ánd a textbox for both limits results in 6 UI components instead of 2.

Making the whole thing look more cluttered? 

I'm by no means a UI expert 😅 so I do value others input very much

**Comment by parsedout** [comment]
I definitely don’t claim to be a UI genius either but sometimes clarity of
purpose outweighs sleek. Takes a special talent to combine the two well. :)
