### ISSUE TITLE
[Feature] Quick Sort

### ISSUE THREAD

**Issue by FadingArabChristians** [WDaan/VueTorrent#309]
Is it possible to add 

I'm not sure if this is allowed but I have a suggestion to add "Quick sort options" right under "Dashboard".

i.e. You click on a button to the right of Sort Torrents and it sorts it torrents by ETA  instead of having to go into the Sort Torrents menu.

Let me know if feature requests like this is not allowed Ill gladly take it down. thanks! <3

**Comment by WDaan** [comment]
They are definitely allowed! You're ofcourse right, the current way of sorting is a bit cumbersome. Let's see if I can just put it in a drop-down instead of a dedicated modal. Would probably still fit next to the search box.
