### ISSUE TITLE
[Feature] RSS Support (Hear me out!)

### ISSUE THREAD

**Issue by Clickbaitcake** [WDaan/VueTorrent#311]
Before this issue is quickly closed please hear me out! I have read the other issues on this topic and can see no one really pressed good reason other than yourself, @WDaan if you wont use this feature then of course its fair enough that you wont develop it but id like to add my reason to the pile to see if I can convicne you...

I do not use Radarr or Sonarr because for me they are overkill. I dont use their features and dont really like having to maintain multiple services, I just have a box with lots of storage and your wonderful torrent client. For simplicity people like me might want to use https://showrss.info. Whenever a show is on it gets dropped into the RSS feed from ShowRSS and automatically downloads. Its great because the user does not have to worry about installing and maintaining Sonarr, Radarr and of course Jackett. This leaves the user with a nice simple server which focuses on what it does best, downloading torrents. I found 6 other requests for this issue with 12 thumbs up which means a rough total of 19 people (including myself) would like to see this feature!

If I had the know how I would build this and submit a pull request but I just dont. Although @WDaan  you owe us nothing, we would all really appricate this feature. Im sure some folks would even donate a coffe or two... I know I will.
Paging other supporters of this idea: @NilSilva @Zonimi @Azraelle @kbipinkumar

In any case, thank you for your development work so far already, this is a great project!

**Comment by will-blk** [comment]
It's a feature I also use a lot. That will be my first attempt with VUE but I will try it out. 

My goal will be:

- Enable/Disable rss auto download
- Add feed
- Add rule

I also have a full-time job so whatever comes next will depende on how long I can get it done x)

How that sounds @WDaan ?

**Comment by WDaan** [comment]
@will-blk 

Looking forward to your PR. Let me know if you need help.

**Comment by will-blk** [comment]
Actually, I do. I'm trying to use addFeed api but couldn't get it right. Only returns 400

The request: `this.execute('post', '/rss/addFeed', { url: feed.url })` where feed is: `{ url: 'whatever'}`

The references: 
- [github](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#add-feed)
- [readthedocs](https://qbittorrent-api.readthedocs.io/en/latest/apidoc/rss.html)

I was able to list and delete feeds and rules already but couldn't figure those creations out, tried both params options. I'm looking the right doc?

**Comment by will-blk** [comment]
Finally, got that creation working!

**Comment by WDaan** [comment]
What changed??

**Comment by will-blk** [comment]
Add the param named path, it seems to be required and not optional. Copied the value of the URL for it as seems to be the behavior on default webview

**Comment by will-blk** [comment]
It's a ton of copy and paste from existing code but works. VUE is confusing

**Comment by lyaschuchenko** [comment]
@WDaan if it possible add view list from feeds?

**Comment by Larsluph** [comment]
The only feature left is the mark as read but everything else should be implemented!

**Comment by will-blk** [comment]
Thanks for taking it another step forward! It's really satisfying to see that small contribution has evolved ^^

**Comment by Larsluph** [comment]
"mark as read" is now implemented, I also added an "unread articles" filter in #657.
Is it enough to close this issue @WDaan ?

**Comment by WDaan** [comment]
Good enough for me 😄
