### ISSUE TITLE
Support filtering by tags

### ISSUE THREAD

**Issue by hmnd** [WDaan/VueTorrent#312]
Currently, it's only possible to filter torrents by search, status, or category. It would be useful to filter by one or multiple tags in addition to these. I'd also like the ability to filter by torrents *not* containing specific tags, too.

**Comment by WDaan** [comment]
For searching I use [fuse.js](https://fusejs.io/), I don't think they support excluding terms from a search as far as I know :/ 

Searching for a tag should provide the wanted result 🤔
Tags is added as a searchable property: https://github.com/WDaan/VueTorrent/blob/master/src/views/Dashboard.vue#L249

**Comment by IevgenSobko** [comment]
Search by tag currently works  and worked for me all along since i started using VueTorrent.
@hmnd pls try again and provide additional details for case that doesn't work for you.
