### ISSUE TITLE
If not select a torrent file or fill a link to download ,it cannot close the "Add a new Torrent" window

### ISSUE THREAD

**Issue by Kaol-Fu** [WDaan/VueTorrent#314]
As the title, if not select a torrent file or fill a link to download ,there is no way to close the "Add a new Torrent" window. I have trid to press the "Esc" buttom, it not work. The only way to clear the window is refresh the web.

**Comment by WDaan** [comment]
There's a close button, it's just not visible for lightmode.... it's a known bug I forgot about 😅
I think there's an issue for it but I can't find it immediatly.

<img width="921" alt="Screenshot 2021-11-02 at 08 52 31" src="https://user-images.githubusercontent.com/25707052/139806815-af43af43-4b08-4c8c-9a29-8953bbe0797b.png">
<img width="921" alt="Screenshot 2021-11-02 at 08 52 41" src="https://user-images.githubusercontent.com/25707052/139806845-7f2684b4-b863-417b-a287-5084fcfeb6c7.png">
