### ISSUE TITLE
Seeding shows as failed

### ISSUE THREAD

**Issue by ManCaveMedia** [WDaan/VueTorrent#32]
Same as #21 : While seeding an entry shows as failed.

Edit: I noticed the status only shows 'fail' while actively uploading. While seeding but idle the status shows 'done'

**Comment by WDaan** [comment]
Could you perhaps look into the old webui and see what the torrent's state is?

**Comment by ManCaveMedia** [comment]
```
GUI / Default WebUI  <=> Vuetorrent:
Completed            <=> done
Downloading          <=> busy
Downloading metadata <=> fail
Queued *             <=> fail
Queued **            <=> queued
Seeding              <=> fail
Stalled              <=> fail
[F] Downloading	***  <=> fail
```

`*`   Queued as in "waiting in que for a download slot to open up"
`**`  Queued as in "downloaded and waiting for an upload slot to open up"
`***` No matter whether actually downloading or not, always shows as 'fail' in VueTorrent

**Comment by WDaan** [comment]
Seems like I've messed up somewhere along the way... I've re-released v0.3.0 and I hope it's fixed now

**Comment by ManCaveMedia** [comment]
Thanks! I appreciate all the hard work 👍 
I will give it a try soon and let you know...

**Comment by ManCaveMedia** [comment]
* "Seeding" and "Stalled" (GUI) still both show as "fail" in VueTorrent unfortunately.
* "Checking" (GUI) shows as "checking" in VueTorrent (so that's correct).
* "Downloading metadata" (GUI) shows as "busy" in VueTorrent (I would prefer "downloading metadata" or "metadata")
Didn't have any other status to check at the moment.

**Comment by WDaan** [comment]
I've added the 'stalled' and 'metadata' states. 
They'll be available in the next release.

**Comment by ManCaveMedia** [comment]
Okay, a quick check of the code against the WebUI API:
* `case 'forcedDL':` should be `case 'forceDL':` (remove the extra 'd')
* `case   'queuedForChecking':` is not in the API (anymore) as far as I could find
* `stalledDL`, `stalledUP` and `uploading` are missing in your code.

I've used the Possible values of `state` from the [qBittorrent wiki](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-torrent-list) as a reference.

**Comment by WDaan** [comment]
Thx for the help!

- that one is indeed a typo!
- I referenced the original code, didn't check every single one specifically
- I messed up the branches, you can find them in the Filtering pull request

**Comment by ManCaveMedia** [comment]
Look like it's all solved in the latest v3.0.0 release!
I'm very happy with how the webui is looking right now. 👍 🥇

**Comment by WDaan** [comment]
Awesome!
I'm really glad you like it!

After some small planned fixes, I'll take a look at your other issue

**Comment by ManCaveMedia** [comment]
I've opened some more...
Sorry ;)
