### ISSUE TITLE
Some downloads are not displayed in VueTorrent

### ISSUE THREAD

**Issue by dm9tr0** [WDaan/VueTorrent#326]
Some downloads are not displayed in VueTorrent

See picture below:
https://i.imgur.com/I8A1WUI.png

Do not know what I can provide here. Tried to clean Cache. Did not help. Re-login did not help.

Open one more tab, but in incognito mode: works and can see torrent file, cleaned cookies - did not help 
https://i.imgur.com/rkz14ua.png 

---

**Comment by WDaan** [comment]
Might still be a caching issue 🤔 
Settings are stored in local storage, (sort options too) maybe some persisted

**Comment by 13Dima13** [comment]
No, I found issue - settings "Show Tracker Filter", when it is enable - nothing displayed even if you choose ALL trackers in menu.
https://i.imgur.com/hAzbv38.png

**Comment by rickwang2002** [comment]
I have the same issue, no nothing displayed when enable "Show Tracker Filter".

It can be easily reproduce the bug on my computer: 
- Clean all cached data 
- Open website 
- Enable "Show Tracker Filter"
- Everything disappear

Select a specific tracker and then select 'All' will fix it.

By the way, I think it will be great if you add a button to easily clean all cached data.

@WDaan

**Comment by Larsluph** [comment]
With the addition of the active filters chip, I think this can be closed @WDaan ?
