### ISSUE TITLE
Torrent search modal closes on enter keypress

### ISSUE THREAD

**Issue by czornikk** [WDaan/VueTorrent#329]
When pressing enter in the search box dialog after inputting a search term the dialogs closes instead of triggering the search.
![image](https://user-images.githubusercontent.com/47973790/143679054-20dc1512-d1cc-4109-acb1-ebe85ae6b1d2.png)
Reproduction steps:
Open the search dialog, input some text in the search box and press enter

Expected behaviour:
The search is triggered after pressing enter and the dialog doesn't close

**Comment by WDaan** [comment]
Duplicate of #259? 🤔

**Comment by czornikk** [comment]
It is, sorry, I search using the browser search but didn't switch to the second page of issues. My bad, sorry.

**Comment by WDaan** [comment]
No worries 🙂
