### ISSUE TITLE
Request: Different view for downloaded entries

### ISSUE THREAD

**Issue by ManCaveMedia** [WDaan/VueTorrent#33]
I hope you don't mind me posting ideas on how to improve this project.
This one especially might be tricky and subject to personal preferences.

Would it be possible to show different labels on a dashboard entry depending on the download status (like percentage downloaded)?

If so, I would love for an entry still **in download** (no matter the status) to see:
- Torrent title
- Size
- Done (MB/GB and/or percentage)
- _ETA_
- Status
- Category
- _Download_
- _Seeds_

And for entries that are **fully downloaded** (not matter the status):
- Torrent title
- Size
- _Ratio_
- Status
- Category
- _Upload_
- _Peers_

Hope you like the idea...

**Comment by jiznon** [comment]
If i'm undertsanding correctly, I think this request covers what I was about to request: Being able sort torrents by _Added On_. My typical use-case for a webui is to check on the status of my most recently added torrent (whether added by the webui or automatically via sonarr, radarr, etc). That's the one thing holding back from using any of the handful of good looking webuis I've seen.

**Comment by ManCaveMedia** [comment]
> If i'm undertsanding correctly, I think this request covers what I was about to request: Being able sort torrents by _Added On_. My typical use-case for a webui is to check on the status of my most recently added torrent (whether added by the webui or automatically via sonarr, radarr, etc). That's the one thing holding back from using any of the handful of good looking webuis I've seen.

Actually my request was to change the displayed field of downloaded torrents, because it doesn't really make sense to show the download speed when the download is done. But It does make sense to show the ratio.

**Comment by WDaan** [comment]
I will make it change! Show ratio when its done, otherwise show download speed

**Comment by ManCaveMedia** [comment]
Maybe a little early to close the issue, but that's up to you of course...

My original request was to remove "Done", "ETA", "Download (speed)" and "Seeds" from the torrent view as soon as the download is at 100%, because they don't really make sense by then anymore.
They could be replaced by "Ratio", "Upload (speed)" and "Peers", because they start making (more) sense as soon as the download is done, but stays available just for upload.

**Comment by ManCaveMedia** [comment]
Could also be two options in the VueTorrent settings:
- fields to show on an 'active' download (<100%)
- fields to show on a completed download (=100%)
Possibly with an option to set the order.

**Comment by WDaan** [comment]
I will try to create 2 arrangeable lists where you can pick which fields to show and drag them around to change the order.

1 list for done torrents, the other for busy ones

**Comment by ManCaveMedia** [comment]
Great!
Can't wait...
But don't rush :)

**Comment by WDaan** [comment]
I am proud to anounce the very first version of the configurable dashboard, this will probably create quite a few issues in the future... but its a really cool feature, if I say so myself
