### ISSUE TITLE
Anonymous mode doesn't work

### ISSUE THREAD

**Issue by notpeelz** [WDaan/VueTorrent#338]
When I check the "Enable anonymous mode" setting, [it also controls the "Enable Local Peer Discovery" setting](https://github.com/WDaan/VueTorrent/blob/a7ce1492671c7ee10778a569a61ed57516c38757/src/components/Modals/SettingsModal/Tabs/BitTorrent.vue#L30).

**Comment by k-matti** [comment]
Confirm, have the same issue

**Comment by steakhutzeee** [comment]
Same issue here.

**Comment by Anteus** [comment]
Seems like a copy paste error here's the fix.
https://github.com/Anteus/VueTorrent/commit/bcdc7a76921f61b15f90eda4381787af6d533a47
