### ISSUE TITLE
Add settings for global speed limits

### ISSUE THREAD

**Issue by notpeelz** [WDaan/VueTorrent#339]
It would be nice to have a way to configure the global speed limits

Native:
![image](https://user-images.githubusercontent.com/920910/144101796-a5600b72-c219-4203-a67b-2dab79f8b682.png)

Default WebUI:
![image](https://user-images.githubusercontent.com/920910/144102050-aa83cb10-29e1-4ff3-9e32-61805010c2bf.png)

**Comment by david-kalbermatten** [comment]
Yes, especially if you use a docker install where you only have the web GUI. Right now, I have to switch off the theme every time I want to change the speed limits

**Comment by giacomocerquone** [comment]
I'd like to work on this! I might try and start to get my hands dirty for real for the first time with vue maybe (I'm mainly a react / angular dev)

@WDaan you didn't introduce this because qbittorrent doesn't support controlling the global speed from a custom theme or for some other reason?

**Comment by WDaan** [comment]
First of all, sorry for tuning in so late... my Github notifications have been a little broken the last couple weeks.

Usually I look at [this](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-v3.2.0-v4.0.4)) documentation when implementing a feature for the custom WebUI.

Thanks @giacomocerquone! I'm looking forward to reviewing your PR.

**Comment by giacomocerquone** [comment]
Yeah, yesterday while writing the code I found that repo too because the API I linked weren't that great since are based on the Py client. Thanks for the link nonetheless 😊

@WDaan I'll wait for the review, there are few changes l, shouldn't require much time
