### ISSUE TITLE
Downloadspeed shows as NaN on the graph while nothing downloading

### ISSUE THREAD

**Issue by ManCaveMedia** [WDaan/VueTorrent#34]
Downloadspeed shows as NaN on the graph while nothing downloading.
I noticed you tried to fix this before, but on V0.2.0 downloadspeed on the graph still shows NaN when no downloads are active (only seeding entries).

Also the header off the mouse-over pop-up shows a number (from 1 to 15), without explanation. Maybe you want to invert this (15 minus current value) and add ' seconds ago'.

**Comment by WDaan** [comment]
That's a good idea! 

Thanks for the honest feedback & ideas!

I am renovating the house though, so I can only start in about a week

**Comment by ManCaveMedia** [comment]
You're welcome for the suggestions.
Good luck on renovating the house!
I'll keep an eye open for changes here on Github, but don't worry, no hurry! ;o)
