### ISSUE TITLE
Question: How to change date and time formats?

### ISSUE THREAD

**Issue by 13Dima13** [WDaan/VueTorrent#340]
For example by default I can see: `mm/dd/yyyy , H:mm:ss AM\PM`
https://i.imgur.com/ti08yNC.png
I would like to have:
`dd/mm/yyyy, hh:mm:ss `
According to example: `2/12/2021, 18:07:07`

**Comment by WDaan** [comment]
This is non configurable at the moment, but I guess it would be a nice addition 😄

**Comment by 13Dima13** [comment]
It would be nice change it even manually (without UI settings) in some json config or whatever. Thank you.

**Comment by WDaan** [comment]
Unfortunately, things like JSON configs is currently impossible because VueTorrent is purely a WebInterface compatible with the QBitorrent API. It's impossible for it to 'read' data from a config file, hence all settings are managed in the UI & saved to localstorage of your browser.
