### ISSUE TITLE
Skip "Add A New Torrent" Screen

### ISSUE THREAD

**Issue by Joshakazam** [WDaan/VueTorrent#342]
Hey Team,

Thanks for all your hard work on this UI, it looks beautiful!
I know there's a way to skip the "when adding a new torrent" screen on the desktop client. Is there a way to do this while using VueTorrent? 
![image](https://user-images.githubusercontent.com/20770402/144816507-6aa792dc-0122-4439-bbac-c57f19fedf18.png)

I always want to just run with the default settings that I have configured, so going through that additional popup can be annoying.
Thanks!

Kind regards,

**Comment by WDaan** [comment]
Not at the moment unfortunately ☹️ 

But I don't see many other people requesting this, so closing for now.
