### ISSUE TITLE
Cannot load qBitTorrent + VueTorrent in Organizr iframe

### ISSUE THREAD

**Issue by Ryther** [WDaan/VueTorrent#345]
```yaml
Version:
  qBitTorrent: 4.3.9
  VueTorrent: 0.15.0
```

I'm using Organizr with an iframe which contains qBitTorrent.
If I use qBitTorrent with "Enable clickjacking protection" OFF i can see the client correctly from Organizr.
When I activate VueTorrent I cannot see the client anymore with this error in the developer console:

```
Refused to frame 'https://qbittorrent.example.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".
```

**Comment by WDaan** [comment]
Im sorry for not replying sooner.

Seems like we need to add another csp header?
Any idea which one?

**Comment by RynoXLI** [comment]
I fixed this issue for myself. I had a reverse proxy and I added a csp header there.

`content-security-policy: frame-ancestors https://organizr-url.com`

Additionally, I also had "Enable clickjacking protection" and "Enable Cross-Site Request Forgery (CSRF) protection" turned off from the qbittorrent UI. Couldn't find those options in the VueTorrent UI.
