### ISSUE TITLE
Rename content buttons not available on mobile

### ISSUE THREAD

**Issue by hbooo** [WDaan/VueTorrent#348]
![image](https://user-images.githubusercontent.com/242125/146786183-61eb4339-abbb-40be-99c8-3386af78b002.png)

I'm unable to rename a content on mobile 
![image](https://user-images.githubusercontent.com/242125/146786428-99d5dfb2-f888-438d-b9c6-f7f54b106f4a.png)
buttons aren't available and nothing happens if I long press the name

**Comment by WDaan** [comment]
This is intentional, but I can't immediately find the issue explaining why.
