### ISSUE TITLE
All-time stats

### ISSUE THREAD

**Issue by Bankst** [WDaan/VueTorrent#351]
I'm not sure if this is somewhere and I'm just missing it, but I can't seem to find the all-time stats view.

**Comment by WDaan** [comment]
Does that exist? There are session stats under the speed graph in the sidebar.

Not sure if there are stats that survive a server reboot

**Comment by Bankst** [comment]
![image](https://user-images.githubusercontent.com/1190764/147373488-f74fe09a-3876-4609-b631-5a5555f11068.png)
the desktop client definitely has lifetime stats

**Comment by WDaan** [comment]
Sure. But are those available in the default WebUI? I can only show what's available through their API.

**Comment by Bankst** [comment]
Yes, this is from my qbittorrent docker container.
![image](https://user-images.githubusercontent.com/1190764/147397118-05a29632-4db0-4b90-8836-1a883016f22d.png)

**Comment by Thanzex** [comment]
@WDaan in the `/sync/maindata` api endpoint there are the `alltime_dl` and `alltime_ul` stats

**Comment by kotx** [comment]
Any update on this? It would be really useful.
