### ISSUE TITLE
npm install found 63 vulnerabilities?

### ISSUE THREAD

**Issue by Seltonu** [WDaan/VueTorrent#353]
![image](https://user-images.githubusercontent.com/10287568/147384087-a4cdc6d8-ebca-4144-bb8b-ef007efa43b4.png)

Installing the cloned repo with "npm install" found 63 vulnerabilities of which 49 are "moderate" and 14 are "high". This is my first time using npm for anything, is this cause for concern? Also a lot of warnings about deprecated packages.

**Comment by WDaan** [comment]
I think that's something that occurs in most projects.
I always try to keep packages updated as best as I can.

I made a branch with Vite, which is another build tool. In an attempt to reduce the number of required (and deprecated) dependencies. But haven't gotten it working 100% just yet.
