### ISSUE TITLE
Mention QBitTorrent

### ISSUE THREAD

**Issue by andrisi** [WDaan/VueTorrent#356]
You do a great job with this alternative UI for QBitTorrent, but it deserves to be mentioned, and prominently. Perhaps "QBitTorrent w/Vue" or something like this, instead of just "VueTorrent" in the title and dashboard. As it is now, it's a bit unfair: you're taking credit for something that is 85% someone else's work. I could not find any obvious mention of QBitTorrent on the UI currently, and it's barely mentioned here on GitHub, for example missing from the "Credits" section.

**Comment by WDaan** [comment]
It's literally the first sentence in the README? Also the subject of the repo.

I did not mean to offend anyone. I certainly didn't think anyone would confuse the origin of the project. As I thought VueTorrent was clearly known as an alternative WebUI, nothing more nothing less.

**Comment by andrisi** [comment]
Sorry if I sounded too harsh @WDaan. You're work is great. Just add "QBitTorrent" prominently in the UI that all users see every day. Perhaps in the title, where you have VueTorrent now? And then "with VueTorrent" or whatever you fancy. As it is now, it looks like I'm using a product called VueTorrent, not QBitTorrent with an alternative web interface. Except if you read readmes :-)

**Comment by Kajover** [comment]
I had the same confusion with my friends. Maybe resolve this by adding a dropdown menu like with "VueTorrent title" with the option to choose between VueTorrent and qBittorrent and something else. Alternatively, a text field could be implemented in the settings to edit the title altogether.

**Comment by Kajover** [comment]
@WDaan, thank you a lot for your work. It is really appreciated.

The fix you implemented is a mention in the credits. It does not consider the possibility to change the title though. Should a new issue be created for the option to change the title, or can this issue be reopened again? Thank you.

**Comment by Hukuma1** [comment]
This is why this generation can't have nice things. 

Thank you for your awesome alt web UI, @WDaan. Keep up the great work!

**Comment by andrisi** [comment]
@Hukuma1 what are you referring to?

**Comment by Kajover** [comment]
@WDaan thank you for v0.15.1 - this is how it looks now:
<img width="399" alt="Screen Shot 2022-01-13 at 19 51 00" src="https://user-images.githubusercontent.com/83403952/149391599-8eacc83f-5964-4985-8734-36a2bf7388a8.png">
Unfortunately, the tab title is not reflecting the name change to (the correct form of) 'qBittorrent'. It would be great if we had a toggle in the settings to be able to change between VueTorrent and qBittorrent. Thanks again.

**Comment by WDaan** [comment]
Feel free to submit a PR.

**Comment by Kajover** [comment]
I am not a programmer but maybe somebody else might chip in. Thank you anyway.

**Comment by WDaan** [comment]
Sure.


You're right, it looks a little silly if it doesn't match. Might change it to Qbittorrent as well.

Don't want to make it a setting though...there are enough Vuetorrent specific settings already.

**Comment by Kajover** [comment]
v.0.15.2
<img width="376" alt="Screen Shot 2022-01-13 at 20 37 12" src="https://user-images.githubusercontent.com/83403952/149397870-b575c0fc-a274-48dd-bcf5-b0bf96a926e0.png">
Thanks. It's 'qBittorrent' though if you want to correct it in a future release. I can live with it though :) Thank you again.
