### ISSUE TITLE
iOS Safari cannot  show PC right-click menu through long pressing

### ISSUE THREAD

**Issue by jiangjiangflies** [WDaan/VueTorrent#357]
Hi,
First, thanks for your great work! It's really a fantastic qb webui!
I'm using it on my iphone Safari. When I want to do something with a torrent（like rename,change location, etc）by long pressing, the menu won't pop up or disappear quickly. It can't focus. On my PC, however, I can do this by right-click easily.
Can you fix it?
Thank you very much!

**Comment by WDaan** [comment]
I know it's super annoying 🙁 

Temporary workaround is to tap with 2 fingers, that should work the same as a right-click.

**Comment by SparkNZ-VC** [comment]
> I know it's super annoying 🙁
> 
> Temporary workaround is to tap with 2 fingers, that should work the same as a right-click.

Never realised I could do it with two fingers, this is a perfect work around!

**Comment by WDaan** [comment]
Re-tested myself and it seems to be working fine now.
VueTorrent v0.17.1 and iOs 15.5
