### ISSUE TITLE
[Feature] Rename folders

### ISSUE THREAD

**Issue by khatharsis42** [WDaan/VueTorrent#358]
In the vanilla qBittorrent UI, you can rename the folders inside your torrent. This is not the case with this UI, would there be any way to add that ? Thanks !

**Comment by NeoTheOne** [comment]
This is really needed, please add it.

**Comment by ShawHaines** [comment]
This is complementary to #354, not limited to the top directory folder, but ALL folders are unavailable to be renamed.

![image](https://user-images.githubusercontent.com/50012391/166131886-cf638e54-e1da-45a8-80a5-c67b17f223e2.png)


@flashlab has fixed this issue in his [fork](https://github.com/flashlab/VueTorrent/pull/7), please apply them to this repo.

**Comment by flashlab** [comment]
@ehawman I've make a lot of modifications based on my own needs, so it will be complicated to seperate the single feature inorder to merge into this repo. You can checkout my commit and pick up useful code. For now I don't have plan to do the merge stuff;)

**Comment by HeyMeco** [comment]
Bump, for now I'm just deactivating the custom UI, rename and activate it again. The Edit button for folders would be much appreciated

**Comment by xheonin** [comment]
#500
