### ISSUE TITLE
Content tab 'crashes' for torrents with many files

### ISSUE THREAD

**Issue by BrendanL79** [WDaan/VueTorrent#359]
Attempting to view the "Content" tab on a torrent with many (100's) of files causes the UI to spin for a few seconds, then the torrent's popup disappears entirely.

**Comment by EYW-015** [comment]
I'm using PT. There are many torrents contain lots of files even over 3 thousands. That's a big problem.

**Comment by Larsluph** [comment]
Popup is no longer relevant. This may not occur now. @WDaan
