### ISSUE TITLE
url input pushes other items out of box in mobile bug

### ISSUE THREAD

**Issue by green99999** [WDaan/VueTorrent#360]
![3](https://user-images.githubusercontent.com/97542049/148985693-1e3d4219-3cf9-4a02-8fa8-355613a6c63b.jpg)
maybe limit the size of the URL box

**Comment by Larsluph** [comment]
@WDaan Outdated

**Comment by WDaan** [comment]
Thansk @Larsluph  for going through them 😛  I sometimes forget which are already resolved
