### ISSUE TITLE
Anonymous mode activated after first install

### ISSUE THREAD

**Issue by Kajover** [WDaan/VueTorrent#362]
Anonymous mode was activated after first install of VueTorrent in VueTorrent, although it is deactivated in the standard webUI.

**Comment by WDaan** [comment]
What method did you use for installation?


The WebUI itself should not have any influence on the default settings of qbittorrent.

**Comment by Kajover** [comment]
@WDaan by creating a folder on the server, copying the extracted release files to it, and redirecting qBittorrent to use the folder for the alternate WebUI. Nothing out of the ordinary.

**Comment by kevocl** [comment]
This is probably related to https://github.com/WDaan/VueTorrent/issues/338

It looks like the checkbox for Local Peer Discovery is wrongly 'wired' to the Anonmous Mode checkbox in the UI.

**Comment by steakhutzeee** [comment]
> 

I have this exact issue. Anonymous mode not activated in qBittorrent but activated and wired to Local Peer Discovery in Vue.

**Comment by steakhutzeee** [comment]
> This is probably related to #338
> 
> It looks like the checkbox for Local Peer Discovery is wrongly 'wired' to the Anonymous Mode checkbox in the UI.

I have this exact issue. Anonymous mode not activated in qBittorrent but activated and wired to Local Peer Discovery in Vue.

**Comment by koningcool** [comment]
Same here :)

**Comment by Anteus** [comment]
Seems like a copy paste error here's the fix.
https://github.com/Anteus/VueTorrent/commit/bcdc7a76921f61b15f90eda4381787af6d533a47
