### ISSUE TITLE
[Feature] An easy accessible button to switch theme

### ISSUE THREAD

**Issue by jsmdy** [WDaan/VueTorrent#365]
As all features aren't usable (like speed management) on this beautiful theme, it can be useful to have a button (easy to access) to open a new window with the all-features classic theme, a temporary view that disappear once window is closed

**Comment by WDaan** [comment]
I understand the request but still find it a little weird.

It does not actually solve the problem, nor do I think what you suggest is actually possible in a reliable way.

I believe it will probably be easier to implement the features you are missing, which is the right way to go about this in the first place.

**Comment by jsmdy** [comment]
I've an inspirational experience similar. I'm using an audio linux client-server distribution, [Daphile](https://www.daphile.com/) (based on Logitech Media Server), the vanilla skin is not so bad but not very actual, the plugin [Material Skin](https://github.com/CDrummond/lms-material) add a nice theme (on all kind of screens) but lacks somd of the parameters. But it's not a problem because most of this missing parameters are not for a everyday usage. The skin version is accessible via IP:9000 and the vanilla just with IP of the server, this way it is easy to switch from one to another.

I'm feeling the same "story" for Vuetorrent, some specific parameters will not change everyday, if a button is too weird or not reliable, maybe an additional address part can be another way (I clearly don't know if it's technically possible).

But yeah, the global bandwidth limitation is more an everyday usage so it can be useful to have it on Vuetorrent, I agree

**Comment by WDaan** [comment]
I completely understand the use case.

With how VueTorrent currently works, it is not possible to host both of them on a different port. VueTorrent is purely a WebUI served by the qBittorrent container. 

To achieve something like this I would have to make a custom qBittorent Docker with perhaps Nginx inside to host VueTorrent & proxy requests to qBittorent.
