### ISSUE TITLE
[Feature] Download directory should have default value when adding a new torrent

### ISSUE THREAD

**Issue by jackblk** [WDaan/VueTorrent#367]
As title, when I add a new torrent, sometimes I want to change the subfolder. By default now, it's empty so I have to type the full directory path, it's kinda a hassle to do.

For example, if the default path is `/downloads` and I want to change the location to `/downloads/shows`, I can just type in `/shows`. For now I have to type the full path.

Great project by the way :).

Info:
* qbit version 4.4.0
* vuetorrent version 0.15.2

**Comment by pedrosantosdev** [comment]
In case of subfolders, you can use the categories of the qbittorrent, will put in the correct subfolder, just add a category in Settings > Tags & Categories, when add new torrent just put the category, and no need to worry typing the correct path.
I use to manage shows, movies, books

**Comment by jackblk** [comment]
I do use the categories, but it does not work nicely with Shows, only works with Movies.

For example, I want to download Season 01 of show ABC, then I have to put it into `/downloads/shows/ABC (2022)`. If I select category `shows`, then it can only set the directory to `/downloads/shows/`

It would be great if it can automatically set the directory based on the category: when user sets `shows` category, the directory is filled with `/downloads/shows`.

**Comment by Larsluph** [comment]
Already fixed I think ? I can't reproduce the issue.

**Comment by Larsluph** [comment]
@WDaan Seems outdated, can be closed
