### ISSUE TITLE
I have some UI problem

### ISSUE THREAD

**Issue by Tao311** [WDaan/VueTorrent#383]
Every time login in,it's shows some problems like the picture,but it's perfect after I changed language,and also perfect in my iPhone
My device is Sony Xperia 1 iii,Yandex browser,I tested use Chrome,same issue

![Screenshot_20220301-074059](https://user-images.githubusercontent.com/42931532/156077484-34237a80-97b3-4827-a488-74f4bfe13454.png)

**Comment by WDaan** [comment]
So it's a scaling issue?

Sony Xperia 1 must have a quite unique screensize perhaps 🤔
