### ISSUE TITLE
Hope to add more full Chinese translations

### ISSUE THREAD

**Issue by RenMu-V** [WDaan/VueTorrent#387]
Hope to add more full Chinese translations, thank you very much for your work. The interface is very beautiful!

**Comment by WDaan** [comment]
Sure, which sections would you like to see translated? 

I'll add it to the default language so you can provide the translations.

**Comment by flashlab** [comment]
I've created a fork and complete as much i18n string as possible (mainly for Chinese), maybe will do some help. Since there're tens of modifications of the source code, which makes it unsuitable for merge into the origin repository.

**Comment by WDaan** [comment]
Yeah, would be geat if you provide the language file :)

**Comment by flashlab** [comment]
@WDaan check this(https://github.com/flashlab/VueTorrent/commit/fa59795b6a31f30ef83e737bfc8020ea6aaf84b5) commit. I've transformed language file from js to json in order to make use of i18n-ally. Besides, I make the translation based on the Chinese grammar, so maybe somewhere hard coded. Glad to see VT becoming better ;)

**Comment by RenMu-V** [comment]
I would like the settings page to be fully translated, but it involves too many modifications. Thanks also to my friend above who provided the document. With everyone's joint efforts, VT will definitely get better and better!

**Comment by dongfengweixiao** [comment]
> I would like the settings page to be fully translated, but it involves too many modifications. Thanks also to my friend above who provided the document. With everyone's joint efforts, VT will definitely get better and better!

嘿嘿，刚刚我把设置页面的所有语言资源单独提取了出来，然后顺手将这些资源文件完全翻译为中文了。修改已经pr，看看作者如何处理。后续我会继续处理界面上的其他资源文件。
