### ISSUE TITLE
Automatic Updates

### ISSUE THREAD

**Issue by LarsBoeckel** [WDaan/VueTorrent#388]
Hello! I have been a user of vuetorrent for quite some time now and I have been happy with it. Though I would really like to see some kind of automatic update function. If that is not doable with the limitations of qbittorrent maybe packages for common distros (apt source, aur etc) would be a nice way to achieve similar functionality as well.

**Comment by WDaan** [comment]
What's wrong with a simple cron command?

Checking out the release branch en running `git pull` every X minutes?


For this usecases seems like the easiest approach?
