### ISSUE TITLE
Sorting/Filtering

### ISSUE THREAD

**Issue by ManCaveMedia** [WDaan/VueTorrent#39]
The input field "type to sort..." actually filters instead of sorts the entries.

**Comment by WDaan** [comment]
Jup I got excited with the new implementation, I forgot all about it :sweat_smile:
It's good someone keeps me on my toes

**Comment by ManCaveMedia** [comment]
So, the sorting option is gone?
It was a little complicated, but I liked that at least I was able to sort (by "eta" for example).

**Comment by WDaan** [comment]
Right now it's gone, yeah.

It was cool but not very user-friendly or intuitive, that's why I simplified it.
The searching is more powerfull than before though.

If you have a better way so implement sorting, please let me know.
Most WebUI's have a table with all the props and you click them to sort... but in my implementation that doesn't quite work.

Maybe another select like the one for states & categories?

**Comment by ManCaveMedia** [comment]
Like I said I do believe some form of sorting would be really helpful sometimes.
I agree on the 'old' implementation being not very user-friendly.

A select in the navbar would be a more elegant solution, but would also limit the functionality if not enough options are provided.
I guess these would be used most:
* Default (the order set in the GUI/in which they are added)
* Title
* Category
* Percentage done
* ETA
* Ratio
* Seeds

Maybe, more, but I can't think of them now.

**Comment by WDaan** [comment]
I don't want to overpopulate the sidebar though... Especially on mobile it's getting a little crowded.
I've added some more option to configure what is and isn't shown to solve this.
For sorting I think I'm going with a modal in the top right, you can check it out in the latest release. 
I hope you like it!

**Comment by ManCaveMedia** [comment]
Perfect!
Didn't have too much time to test it, but at a first glance it looks great.
It looks like all bugs are gone, but to be sure I need to find some time to do some more testing.

**Comment by WDaan** [comment]
Sure! If there is something that is not to your liking, fire away

**Comment by jef** [comment]
The sort seems to be working, but not sure about "reversed". Toggling doesn't seem to change the view.
