### ISSUE TITLE
Current Speed shows download / upload when nothing is downloading/uploading

### ISSUE THREAD

**Issue by joszz** [WDaan/VueTorrent#394]
When I have no torrents listed, or for example stalled torrents, I see a quite high download speed (max speed of my connection) and some random upload speed.
When I go back to default qBittorrent theme, and show the DL/UL in the title bar, I don't observe the same behaviour. Then it just shows 0 / 0 when there are no torrents in the list, which makes sense.
I'm on Ubuntu, running the latest qBittorrent (4.3.9) from the official repo.

**Comment by WDaan** [comment]
That's weird 🤔  I don't seem to be experiencing that kind of behavior 

<img width="1134" alt="Screenshot 2022-07-03 at 12 55 46" src="https://user-images.githubusercontent.com/25707052/177036379-c45b2186-7dcb-4b3c-ab7a-62d73e5c6069.png">

**Comment by joszz** [comment]
I switched to a docker container based setup and never seen this again. Might be some weird fluke on my end
