### ISSUE TITLE
[Bug] VueTorrent tries logging in with empty credentials 

### ISSUE THREAD

**Issue by MBR-0001** [WDaan/VueTorrent#396]
Steps to reproduce:
1. open a new (incognito) tab
2. open the network monitor and select the Fetch/XHR filter
3. open the vuetorrent page
4. observe that a POST /api/v2/auth/login request has been made but the login fields are empty

This is a big issue if IP banning is enabled, just a few page reloads can get you blocked

EDIT: I looked at the code and it appears that the app is intentionally trying to log in without a username and password :thinking: 
(https://github.com/WDaan/VueTorrent/blob/master/src/App.vue#L57-L63)

**Comment by WDaan** [comment]
Yes, it is intentional... although I know it's not ideal. The goal was to check if you're already authenticated or not, unfortunately didn't find a better way to do that at the time. Not sure if there is now.

**Comment by MBR-0001** [comment]
from what I see **GET** `/api/v2/app/version` returns the version (`v4.4.2` in my case) if the cookie is valid (I assume that's what you're checking) or 403 forbidden if not, could that be used?
