### ISSUE TITLE
Is there no watch folder for this theme? (for auto downloading)

### ISSUE THREAD

**Issue by heartdeadz** [WDaan/VueTorrent#397]
Hey! i just swapped to your theme, and i absolutely LOVE it on my seedbox!

i just have one tiny question!  Where did the setting for Automatically adding torrents from a watch folder go?

or isent this  a part of your theme?  as i wanted to use my irssi with qbit, buuuuut there's no watch folder setting, so i can't set it to add torrents from watch folder automatically! xD 

or am i blind as a bat? :o

**Comment by WDaan** [comment]
You're not blind 😅, there is an open issue for it [here](https://github.com/WDaan/VueTorrent/issues/96).
So I'll be closing this one in favor of the existing issue.
