### ISSUE TITLE
Scrolling in settings is clunky

### ISSUE THREAD

**Issue by antonkvm** [WDaan/VueTorrent#398]
I'm using a Mac with Firefox, and scrolling with the trackpad in settings is very clunky.

Otherwise beautiful work.

**Comment by WDaan** [comment]
I know, when I started building this I used modals and kept using modals for everything resulting in tons of layers upon layers with computed heights etc. It resulted in what we have now, it works but is not ideal. I've been thinking about re-structuring everything and use more of a 'page' setup (as opposed to all the modals) and I think it would result in a better UX. 

However this would be quite a big overhaul and unfortunately I haven't found the time just yet. 

But thanks for opening this issue, this shows that it might need to receive a higher priority.

**Comment by antonkvm** [comment]
Thanks for the reply, I understand fixing the issue is not remotely as trivial as identifying it.
