### ISSUE TITLE
How to install??

### ISSUE THREAD

**Issue by ssheduardo** [WDaan/VueTorrent#4]
Hi,
How install VueTorrent?
I have qBittorrent with docker-compose for access to default interface for example for me is 192.168.1.30:8090
With  what ip replace values?

- QBIT_HOST= ?
- VUE_APP_DOMAIN= ?

**Comment by WDaan** [comment]
Hi! Sorry for the late reply.

QBIT_HOST is the url you use to access the qBittorrent webui, so QBIT_HOST=http://192.168.1.30:8090

VUE_APP_DOMAIN can be discarded, that's from a time where I didn't know how to use the Vuejs devproxy 😅

I do have some issues with qBittorrent atm, so I can't really test right now.

qBittorrent doesn't want to connect to my backend....
Neither does the nzb360 app, so I guess it's a qBittorrent issue.
