### ISSUE TITLE
plugin manager on mobile does not work

### ISSUE THREAD

**Issue by antenna2008** [WDaan/VueTorrent#404]
plugin manager on iphone does not work while works properly on ipad and desktop pc.

**Comment by giacomocerquone** [comment]
Only issue I found in the plugin manager on mobile is the following one where I cannot scroll the modal

![telegram-cloud-photo-size-4-5933972746990106173-y](https://user-images.githubusercontent.com/9303791/161566638-3bfe8580-5305-4119-bd4f-ff392e891a9c.jpg)
