### ISSUE TITLE
PWA / mobile app

### ISSUE THREAD

**Issue by Matth7878** [WDaan/VueTorrent#405]
VueTorrent is great but it seems it is lacking info about PWA  ability. 
When using mobile browser you can't create a PWA shortcuts. It doesn't matter when using a chrome browser as it would still treat it as  a web app -> When using shortcut it won't show you browser interface but this not the case with Android Firefox.

So Firefox (and probably other non chrome browser) does not recognize VueTorrent as a web app. It would only allow you to have a shortcut which will open VueTorrent in browser without hiding browser UI.
It would be really nice if it was possible to implement what is missing to make it recognized as a PWA.

**Comment by WDaan** [comment]
You only have to 'install' a PWA just once, so doing it via chrome/safari for one single time, doesn't seem that big a deal.

You're right, it should work wherever but I'd have to look into it. I'm not sure why it would not be recognised.

**Comment by giacomocerquone** [comment]
I'd say it lacks the ability to be installed as a real app through PWA due to the missing manifest.json file.
There are just a few requirements to make a web app a PWA:

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs

**Comment by giacomocerquone** [comment]
mmhh manifest.22 ? what is that? I don't know if it gets recognized by browsers honestly.

As said in another issue, I'm no vue dev and therefore I don't know what the vue-cli you use (I suppose) does to bundle the app

**Comment by WDaan** [comment]
IIRC that version number was specifically added to fix an issue with webworkers not loading a new version and staying on the old one. I don't know if this ia still needed

**Comment by giacomocerquone** [comment]
> IIRC that version number was specifically added to fix an issue with webworkers not loading a new version and staying on the old one. I don't know if this ia still needed

I imagined.

Though the fix to invalidate the cached apps needs to be applied to the js and CSS assets, not to the manifest file itself!

**Comment by WDaan** [comment]
Let's see if that new release works

**Comment by WDaan** [comment]
Manifest name has just been fixed, but yes.... PWA's require a valid domain with https :/ 


I guess this can be closed?

**Comment by Matth7878** [comment]
> I guess this can be closed?

Yes it can.
I just tried with new release but my problems lies with lack of secure domain.
I guess I would have to use Chrome if I want to run VueTorrent as a webapp without using https.

Thanks WDaan

**Comment by giacomocerquone** [comment]
Exactly, the https problem isn't this web app's issue. That's a whole other thing, but the manifest needed to be fixed.

Thanks @WDaan
