### ISSUE TITLE
is it 0.16.0 made progress percent too small?

### ISSUE THREAD

**Issue by IevgenSobko** [WDaan/VueTorrent#410]
In addition progress lost its colored highlight 
<img width="354" alt="Screenshot 2022-04-16 at 17 59 50" src="https://user-images.githubusercontent.com/14232100/163679968-69b876f9-9249-4298-b286-e3296d3a5ddd.png">

**Comment by WDaan** [comment]
I had some problems with the CSS variables when updating `vuetify` and `vuetify-loader` dependencies. Thanks for reporting!
