### ISSUE TITLE
Magnet link text box should not expand

### ISSUE THREAD

**Issue by quaintdev** [WDaan/VueTorrent#413]
Hello,

Thank you for creating vuetorrent. It's beautiful.

I have wanted to report an issue for both desktop and mobile version. The magnet link text box currently expands and overshadows the entire dialog box if the magnet link is long. I think the text box should not expand with the length of magnet link instead it should have a fix height with a scroll bar. It's even fine if it's a non expandable single line because I don't think any user edits the magnet links ever.

The UI becomes hard to navigate on desktop and unusable on mobile because of this issue.

**Comment by WDaan** [comment]
This is indeed a very annoying issue. Unfortunately there is no official fix for this yet so I had to go with the work-around.
https://github.com/vuetifyjs/vuetify/issues/10009
