### ISSUE TITLE
Login prompt with bypass turned on with Nginx Subpath/location

### ISSUE THREAD

**Issue by 33masterman33** [WDaan/VueTorrent#414]
I am receiving the same bug that was previously fixed in issue #266 only though my reverse proxy. I'm not sure if how I'm doing this is unsupported but I have the following nginx configuration set for the path. When accessed directly through the ip it works as expected however on the proxy it prompts the login page then it disappears on refresh.
`location /torrent/ {
                proxy_pass http://192.168.0.20:8585/;
                proxy_redirect http://192.168.0.20:8585/ http://192.168.0.20/torrent/;
        }`

**Comment by evlo** [comment]
also logs in when click on login, but would be nice to just get dashboard and no login prompt

**Comment by maaaaz** [comment]
Hello there,

I am having the same issue, using Apache proxy_pass.

Cheers !

**Comment by pinchi** [comment]
same with traefik 2.6

**Comment by MargeyShah** [comment]
Traefik as well. 

I found that if I sign into my 2FA first before going to my qb I have no issues if anyone is looking for a workaround.

**Comment by DrRaider** [comment]
Same when using behind OpenVPN
