### ISSUE TITLE
Request: Number of items in Dashboard view

### ISSUE THREAD

**Issue by GROSU1** [WDaan/VueTorrent#42]
Hi,

I would first like to thank you for doing such a great and simplistic WEBUI. I see a lot of people appreciate it as well and with good reason.

I wanted to ask/request for future releases, if it is possible, to add an item counter for dashboard? Would be great to have a way to display number of items in view (thinking about filtering/searching here as well) and maybe selected/total items when selection is applied to one or more items? That would be great.

Thanks.

**Comment by WDaan** [comment]
Thank you very much for the kind words!

Do you mean something like this?

![image](https://user-images.githubusercontent.com/25707052/94459192-4d275b80-01b7-11eb-9f54-03925179e496.png)
![image](https://user-images.githubusercontent.com/25707052/94459235-5c0e0e00-01b7-11eb-8040-fccd224d71ba.png)

**Comment by GROSU1** [comment]
Perfect indeed. No word :) keep on doing what you’re doing! Amazing.

**Comment by WDaan** [comment]
Thanks! 

I'll release it soon (maybe tomorrow) with some other minor improvements.
