### ISSUE TITLE
Torrent info modal Progress just green bar without percent displayed

### ISSUE THREAD

**Issue by IevgenSobko** [WDaan/VueTorrent#430]
After 0.17.0 release update, I see the following 

![image](https://user-images.githubusercontent.com/14232100/172049895-efe5ef3e-2107-4bd8-9955-b84afa0a43d3.png)

**Comment by IevgenSobko** [comment]
Ohhh... It seems to be new feature I missed.
But why it has some dark space in the end if this torrent is 100% downloaded. I would expect it to be drawn to the scrollbar then.
Maybe it still makes sense to have percentage displayed before or after this progress bar?

**Comment by WDaan** [comment]
It's just the padding, but I can imagine it can be confusing.

Adding a percentage might be clearer but not sure how to in a visually appealing manner just yet.

**Comment by IevgenSobko** [comment]
I think it requires some border that will identify allowed field of filling for progress.
Then it won't be so confusing.
