### ISSUE TITLE
Update functionality

### ISSUE THREAD

**Issue by Kajover** [WDaan/VueTorrent#436]
It would be great if VueTorrent could

1. update automatically
2. show an update, and we can press a button to update
3. just notify that there is an update available, and we can download/install it manually

**Comment by WDaan** [comment]
Hey! This question has been asked multiple times.

You can actually just pull the `latest-release`-branch on a cronjob and be up to date. It's a really nice idea but for now I don't think the development effort is really worth it and might be better spent elsewhere.
