### ISSUE TITLE
Couldn't load Web UI translation for selected locale (en).

### ISSUE THREAD

**Issue by jprokos** [WDaan/VueTorrent#437]
```
6/7/22 10:53 PM - Using custom Web UI. Location: "/Users/john/GitHub/VueTorrent/vuetorrent".
6/7/22 10:53 PM - Web UI: HTTPS setup successful
6/7/22 10:53 PM - Couldn't load Web UI translation for selected locale (en).
```

I've been seeing this for quite some time... I am unsure where this error is coming from. Looks like the `src>lang>en.js` is omitted when the package is being built?

qBittorrent v4.5.0alpha1
VT v0.17.0

_Originally posted by @jprokos in https://github.com/WDaan/VueTorrent/discussions/434_

**Comment by WDaan** [comment]
There is no reason why it should be omitted. I also don't seem to be having this issue myself 🤔 

Which installation method are you using? 

(I'm just pulling the latest release branch, on 0.17.0 now and english is working fine)

**Comment by jprokos** [comment]
I tried two methods. 
Originally just pulled latest release. Then I installed master and built it using npm. Both methods give me a working app but in both cases there is no English file and I get the notice in qBittorent that it's missing.

**Comment by WDaan** [comment]
I think there might not be a dedicated en file because it's imported by default and probably bundled up with the other code. 


Doesn't explain why it wouldn't load in the app though 🤔

**Comment by jprokos** [comment]
I am just referring to the warning in qBittorrent. If that is "normal" or to be expected then I'll just ignore. I do have an English interface. But it seems qBT is expecting something and not finding it.

**Comment by WDaan** [comment]
It's good that it's still working but there shouldn't be a warning message. What browser are you using?

**Comment by jprokos** [comment]
The warning pops up in the qBT log not the browser.

**Comment by WDaan** [comment]
Aha never looked at that tbh, so I guess it's safe to ignore
