### ISSUE TITLE
Trying to load an inexistant "img/icons/favicon.svg" resource

### ISSUE THREAD

**Issue by maaaaz** [WDaan/VueTorrent#441]
Hello @WDaan,

There's this bug in the current stable release:
* The `index.html` tries to load `img/icons/favicon.svg` in the following section:
```
<link rel="icon" type="image/svg+xml" href="img/icons/favicon.svg">
```
* But this resource does not exist, so there is an error 500

Cheers !

**Comment by matt-laird** [comment]
Possibility a mime type issue, since the response from the qBitttorrent server is `Unacceptable file type, only regular file is allowed.` with a response Content-type header of `text/plain; charset=UTF-8`.
