### ISSUE TITLE
Category Dropdown Torrent Filter resets without resetting the view

### ISSUE THREAD

**Issue by Lightningblade** [WDaan/VueTorrent#444]
![image](https://user-images.githubusercontent.com/30607152/175782867-8b479019-0e5e-4710-b818-919a74261c0d.png)
I have the UI pinned in Firefox. At random(?) times, when visiting the tab again, this dropdown is reset to the (default) All option instead of staying at uncategorized (I mostly only (want to) look at uncategorized torrents), however the Uncategorized filter is still the one applied to the torrent view. This means that even when All is showing in the drop down it is not showing all.

**Comment by Larsluph** [comment]
@WDaan Already fixed, you can close it as completed ;)
