### ISSUE TITLE
Ultra.cc and VueTorrent

### ISSUE THREAD

**Issue by Amiral1212** [WDaan/VueTorrent#455]
Hello, i got a seedbox with ultra.cc and i tried to install vuetorrrent theme for qbittorrent but i just got a blank interface.. tried to do the same with another theme and it worked perfectly, what i do wrong with vuetorrent ?

my path is ./webui/vuetorrent  pointing directly to public folder

![Capture d’écran 2022-07-04 154310](https://user-images.githubusercontent.com/78618594/177168045-1e238f02-5337-4c35-9665-1166028bc8ac.png)

**Comment by WDaan** [comment]
I'm also on Ultra.cc, the way I got it working is by:
- cloning the latest-release branch/downloading the .zip and putting it in your home directory. So I have a `Downloads` folder, a `media` folder, the `www`-folder AND a `vuetorrent`-folder.
- in qBittorrent, I don't use a relative path buth rather the full path like `/home/my-cool-username/vuetorrent`

That's seems to work just fine for me

**Comment by Amiral1212** [comment]
It works perfectly like that thank you very much ! :)
