### ISSUE TITLE
Category filter issue

### ISSUE THREAD

**Issue by mylogon341** [WDaan/VueTorrent#461]
When I sort by category - music, for example, the filter is applied. If I then hit refresh on the page, the dropdown now shows "All", but the filter is still applied.
The only way to get out of this now is to change the filter to something else ("movies", for example) then I am able to change it "All".

This is possibly related to #444

**Comment by IevgenSobko** [comment]
Yes, having the same behaviour since I started using vuetorrent ui.

**Comment by WDaan** [comment]
Closing in favor of #444
