### ISSUE TITLE
Don't reset page opened when closing details view

### ISSUE THREAD

**Issue by IevgenSobko** [WDaan/VueTorrent#462]
**Scenario:** 
I have about 50 pagination pages. I need to update some tags for torrent. Whenever I find torrent and open its details to update tags, when details is closed i resets Ui to the first pagination page and I need again to go to necessary page to update next torrent tags. 
It is very inconvenient.

**Prerequisite:** 
Have multi page torrent list

**Steps to reproduce:**
1.  Go to any not first age in paginaition
2. Open any torrent details by double clicking it
3. Close torrent details

**Expected result:**
- UI opened the same pagination page with the same scrool of list

**Actual result:**
- UI is reset to the first pagination page

**Comment by IevgenSobko** [comment]
Also noticed that search also is reset, which means you will need again type text and wait few seconds because we hae performance issues on big amount of torrents.

**Comment by JStrongy** [comment]
I’d love to see this issue (including the search being reset) addressed.

It’s literally the only negative I have on the UI. Keep up the great work guys!
