### ISSUE TITLE
Unchecking boxes on Settings - Vuetorrent - Dashboard is incredible hard on IOS Mobile

### ISSUE THREAD

**Issue by bedub1** [WDaan/VueTorrent#463]
Using an iphone, it's incredibly hard to uncheck the boxes on the Dashboard settings page.  IE uncheck the "downloaded" box.

**Comment by WDaan** [comment]
Using an iPhone myself?

Which ones are you talking  about?

**Comment by bedub1** [comment]
I'm just using it in the browser.  The items I'm speaking of are the Properties to Display.  
![image](https://user-images.githubusercontent.com/37815229/178152253-8d941daf-32ee-483f-8268-1f8af9832748.png)
