### ISSUE TITLE
Rename file : after saving, file not renamed

### ISSUE THREAD

**Issue by Ribero** [WDaan/VueTorrent#465]
There is two issues with the rename features : 

* you can try to rename a file but when the change is saved, the file is not effectively renamed
* When trying to do the same from an iPhone : the rename button does not appear

 
~~(Can't remember if the same issue present for iPad (will test it as soon as I have access to an iPad)~~ -> button is displayed on iPad

In short :
* Safari macOS, Safari iPad -> button displayed, but rename does not work
* Safari iPhone -> no button and obviously no rename possible too.

QBittorrent release : 4.4.3.1
VueTorrent release : 0.18.1

**Comment by Ribero** [comment]
Latest version solve the issue on iPad. Thanks !
Any chance ton enable renaming on iPhone ?

**Comment by WDaan** [comment]
Its disabled because it was deemed to small on that screensize, back when it was implemented. Maybe we can work something out now.

**Comment by Ribero** [comment]
> Its disabled because it was deemed to small on that screensize, back when it was implemented. Maybe we can work something out now.

@WDaan I didn't want to reopen an incident if you hadn't changed your mind so: is it possible to reactivate this feature on iOS? It's true that it's not very comfortable to rename torrent files from an iphone but it's even worse to have to do it from the original interface when you have nothing else.
