### ISSUE TITLE
“Add” button always displayed

### ISSUE THREAD

**Issue by Kajover** [WDaan/VueTorrent#466]
Would it be possible to have the “Add” button always displayed, and not hide it in the dropdown menu. As this is the most commonly used button, this would improve the overall user experience/speed of adding new downloads.

![E020987A-A84A-4B61-B383-842341E25B25](https://user-images.githubusercontent.com/83403952/178211463-918e3bed-30de-4b06-9376-0a0770ea47fd.jpeg)

**Comment by WDaan** [comment]
Valid concern! Yes, maybe we should do that.

**Comment by saideepesh000** [comment]
hey @WDaan , can i take this up?

**Comment by WDaan** [comment]
@saideepesh000 Sure :) let me know if you need help with anything. 

Its been a busy few weeks 😅 there are some other fixes that I need to release as well

**Comment by saideepesh000** [comment]
hey @WDaan, i got to this UI after running `npm run serve`, but 
<img width="544" alt="Screenshot 2022-08-14 at 7 54 19 PM" src="https://user-images.githubusercontent.com/43727167/184541478-7dcaf369-3492-4591-85ca-1f70ad5c42b5.png">
can't able to signup, can u give me dummy credentials?

**Comment by WDaan** [comment]
Declared in docker-compose file :)
