### ISSUE TITLE
some little suggestions

### ISSUE THREAD

**Issue by lee911214** [WDaan/VueTorrent#467]
①Is it possible to add seeds for the display of seed volume?
②Can you add an io queue to the display? Because many swipe streams with the seedbox have to determine if the hard disk appears to be stuck based on io. This will stop the automatic addition of seeds based on the upload and download speed as well as the queue io.
③Is it possible to add an option to change the download speed and upload speed when adding individual seeds manually? This will make it easier to limit the speed for some seeds
④Can you add a button to return to the original version of qb? Tap to switch between the two versions quickly
⑤Add the option to edit the original tracker instead of adding a new one, some seed trackers show not working, but changing http to https or vice versa will work
Finally, thanks for selflessly sharing and providing such a good-looking web client.

**Comment by WDaan** [comment]
Can we please keep all issues in English? Thank you 🙏

**Comment by lee911214** [comment]
> Can we please keep all issues in English? Thank you 🙏

sorry,i have edited in english. I hope you can seriously consider my suggestions

**Comment by Anteus** [comment]
4. You can toggle alt webui on/off with these links below. Save to bookmark bar or similar.
alt webui on: http://IP:8080/api/v2/app/setPreferences?json=%7B%22alternative_webui_enabled%22%3Atrue%7D
alt webui off: http://IP:8080/api/v2/app/setPreferences?json=%7B%22alternative_webui_enabled%22%3Afalse%7D

**Comment by jsmdy** [comment]
6- I've also a suggestion, add a possibility to check category visibility (instead of 1 by 1, check several categories to display), but it's not something that the basic UI can do so maybe it's too complicated to do

**Comment by WDaan** [comment]
If some things are still required, I think we should go for seperate issues to track things independently.
