### ISSUE TITLE
Cannot render duplicated filenames

### ISSUE THREAD

**Issue by doskoi** [WDaan/VueTorrent#468]
I got a torrent with 3 same filename on the same path, don't know somehow.
but in original web ui, it's shows like
path/file.ext 2G
path/file.ext 4G

but in vuetorrent, it's show like
path/file.ext 6G

of course the download failed in few second, but vue unable to deselect the file to unwanted.
Only switch back to original ui to do it. (any there no button to do this thing)

**Comment by WDaan** [comment]
Is this something we actually should fix? Seems like an edge case almost no one runs into.

Perhaps our efforts are better spend elsewhere?
