### ISSUE TITLE
Autofill broken on iOS

### ISSUE THREAD

**Issue by ericswpark** [WDaan/VueTorrent#474]
When logging in with autofill, sometimes fields are not properly filled in. The placeholder text shows behind the filled-in fields. Attempting to log in in this state will cause an error message to show. Clicking on the bugged field will empty it out – filling it in manually and trying to log in again works.

**Comment by WDaan** [comment]
Are you using it as PWA?
Which browser?

I've been having some issues with the PWA not suggesting my keychain remembered credentials. But haven't encountered what you're describing yet.

**Comment by ericswpark** [comment]
I've tried as PWA (by adding it through Safari), and in Firefox. Occurs in both instances, albeit randomly and sporadically.

I've also had the password autofill recommend the wrong websites for some reason.

**Comment by ericswpark** [comment]
Here's a screenshot of the bug (occurring in the username field):

![440EA149-ADF5-433A-8FFE-0EC0A63913D2](https://user-images.githubusercontent.com/13326074/183269581-698d292e-4fd7-4275-a23d-ae63b9766b4d.jpeg)

Clicking on the field clears it.

Sporadically happens and affects both fields (username and password), but never both at the same time.

**Comment by janstadt** [comment]
I have this same issue with Bitwarden.
