### ISSUE TITLE
Torrent Detail - INFO

### ISSUE THREAD

**Issue by 3guboff** [WDaan/VueTorrent#477]
Hello, unfortunately, there is no normal way to copy information/value from fields (or use the link in this file containing HTTP link).
Here you can see the comments field that contains a link to the original torrent that can be used to give feedback on this torrent and so on:

![image](https://user-images.githubusercontent.com/1561986/182653023-af16c9de-52a7-42d3-ae74-27be8bd14bc9.png)

Can you please make this field(s) available to copy/interact (at least if we talking about links)?

p.s. original UI allows doing this (copy content/open links)

**Comment by 3guboff** [comment]
> I believe we can mark this issue as solved

Unfortunately not, just checked on version 0.18.2, and the issue is still there.

**Comment by tadasvosylius** [comment]
My bad, it is not released yet. Will be fixed in 0.19.0
