### ISSUE TITLE
[Feature Request] Add an option to set default filters

### ISSUE THREAD

**Issue by Navneet-Suresh** [WDaan/VueTorrent#48]
As the title suggests, it would be easier to filter torrents by default and give the user the option to set it in configs.

* Filter by Date added.
* Filter by Name
* Filter by Size

**Comment by WDaan** [comment]
The sorting options are persistent, if you sort by size it will always be by size.
So the feature you want is already implemented.
I don't want to overcrowd the settings menu too much either.

or do you mean something else?

**Comment by Navneet-Suresh** [comment]
Yes, Sort by Size is implemented, I was wondering if you could add an option to allow choice between size and date.

**Comment by WDaan** [comment]
There are a bunch of options to select from!
![image](https://user-images.githubusercontent.com/25707052/96410278-f544a900-11e6-11eb-9ee3-a7c8cba1a761.png)

With 'Date' you probably mean the time it was added, that is actually the 'Default' option... but I'll add an explicit option as well

**Comment by Navneet-Suresh** [comment]
Oh yeah, I didn't notice it at first.
This is exactly what I was looking for.

**Comment by ManCaveMedia** [comment]
> As the title suggests, it would be easier to filter torrents by default and give the user the option to set it in configs.
> 
> * Filter by Date added.
> * Filter by Name
> * Filter by Size

Filtering by Date added doesn't really make sense if the time is part of this filter too. Because: how many torrents can be added at the exact same date & time?
Did you mean sorting?

**Comment by Navneet-Suresh** [comment]
@ManCaveMedia I meant sorting ;)

**Comment by Navneet-Suresh** [comment]
@WDaan Offtopic question for this issue but I didn't want to create a new issue for now.
Is there a way to add magnet links in bulk in the WebUI?

**Comment by WDaan** [comment]
atm you can only add one url at a time, but I could probably fix that pretty easily

Don't hesistate to create new issues! It makes it easier to keep track of requests/problems, feel free to label them as well.

Also please be patient, I don't always have that much time to fix everything

**Comment by Navneet-Suresh** [comment]
> atm you can only add one url at a time, but I could probably fix that pretty easily
> 
> Don't hesistate to create new issues! It makes it easier to keep track of requests/problems, feel free to label them as well.
> 
> Also please be patient, I don't always have that much time to fix everything

Sure, I will create a separate issue. Off course take your time. :)

**Comment by Navneet-Suresh** [comment]
> Don't hesistate to create new issues! It makes it easier to keep track of requests/problems, feel free to label them as well.
Quick update: I am unable to label the issues.
PS: I am active now because I have unexpected time off from work, I reiterate that I don't expect immediate replies nor fixes ;) .

**Comment by WDaan** [comment]
I did not know that
