### ISSUE TITLE
Field "Download directory" become empty on selecting torrent category

### ISSUE THREAD

**Issue by NikcN22** [WDaan/VueTorrent#481]
Field "Download directory" become empty on selecting torrent category.
No matter one or multiply torrent-files selected.

https://user-images.githubusercontent.com/99127302/184364502-e570bdfc-ff4b-49e2-80fb-5ee0665881b2.mov

**Comment by IevgenSobko** [comment]
I remember opening this issue few releases ago.
But with the latest build it should be fixed.
I don't see it anymore.
Could you please upgrade to the latest release and confirm it is still reproducible.

**Comment by NikcN22** [comment]
This problem also appears in the latest version (0.18.1).

But I noticed the appearance of a setting in which you can specify the save path for each category individually. If you make this setting, then everything is fine.

**Comment by IevgenSobko** [comment]
So issue is for categories with no save path specified and it should use default path in this case.

**Comment by NikcN22** [comment]
@IevgenSobko Everything is right.  Issue is for categories with no save path specified and it should use default path in this case.
