### ISSUE TITLE
Missing options available in standard WebUI

### ISSUE THREAD

**Issue by Bust3r14** [WDaan/VueTorrent#483]
![Screenshot 2022-08-16 144817](https://user-images.githubusercontent.com/42153444/184956914-39cd4111-7b6e-4cb5-99e4-7d56118a95dd.png)
![Screenshot 2022-08-16 144924](https://user-images.githubusercontent.com/42153444/184956918-28f7776f-2d7e-47c7-98f4-8f32b61e406c.png)
The VueTorrent UI does not have options in it's settings for what to do with torrents once they reach certain criteria; the criteria options exist, but the resulting actions (pause, remove, superseed, etc) do not exist.

**Comment by WDaan** [comment]
You're right this is more of a general issues, settings options are being added as we go or when they're requested.

**Comment by giacomocerquone** [comment]
I'm going to work on this 😃
