### ISSUE TITLE
100% progress bar colour (in dark mode) same as 0%

### ISSUE THREAD

**Issue by mylogon341** [WDaan/VueTorrent#488]
I'm running dark mode and find that the 100% progress bar to be a bit confusing. It doesn't catch my attention to handle 100% items as, at a glance, it looks the same as something that is stuck at 0%. Would it be possible to please leave the lighter green background to fill, or possibly choose a different colour all together so it draws my attention?

Thanks

![Screenshot 2022-08-26 at 11 46 45 am](https://user-images.githubusercontent.com/5493303/186887696-6fc8aa1c-312a-4ab1-9a3a-af8febeafa83.png)
![Screenshot 2022-08-26 at 11 46 56 am](https://user-images.githubusercontent.com/5493303/186887708-3af93ae3-6a0f-4d1c-8cf9-9b4ed6d21f41.png)

(I dont have anything stuck fully at 0% atm, so this is the closest I have)

**Comment by DanielBiegler** [comment]
I find this reasonable and a good idea. I'm currently taking a look at how to do this.

**Comment by DanielBiegler** [comment]
So I've identified that we can just change the theme colors and it works! :)

![image](https://user-images.githubusercontent.com/14810858/195987654-05c7fe60-f3ab-4a28-9fec-283661e7fa26.png)

Here I've changed it to the downloading-color and it looks clearer than the darker green imo.

@WDaan I also thought about setting to something else so its even clearer but pretty much all distinct colors are already in use. So it leaves only pretty stark colors like this:

![image](https://user-images.githubusercontent.com/14810858/195988217-93b0b54e-4975-439a-ae38-5234398584ba.png)

Whats your take on it?

**Comment by mylogon341** [comment]
That purple looks good but I think it's already used for the 'metadata' phase of a magnet torrent, right?

**Comment by DanielBiegler** [comment]
It's similar but not the same. Metadata is `7e57c2` which is more purple and the new completed is `9b3184` is more magenta/pinkish, see here:

![image](https://user-images.githubusercontent.com/14810858/196005883-8cd7d710-101f-4a3d-989d-19b4fa2419b7.png)

You can find the color settings [here](https://github.com/WDaan/VueTorrent/blob/42da72323a87522025b5159cb17ba2cb0eda4fe6/src/plugins/vuetify.js#L17).

**Comment by mylogon341** [comment]
Hmm. Yea they seem too similar imo, which kind of brings back to the same issue. I wonder if it'd be worth using something like material design as a reference
https://material.io/design/color/the-color-system.html#tools-for-picking-colors
There are some good example pallets on there to pick from and they show the suggested text colour to use against them for visibility as I think that's an issue too with some choices (in regards to contrast). For example.
<img width="200" alt="Screenshot 2022-10-15 at 10 46 09 pm" src="https://user-images.githubusercontent.com/5493303/196008808-b1a399ce-b810-42bb-ae7b-c083ddab4eab.png">
<img width="200" alt="Screenshot 2022-10-15 at 10 43 25 pm" src="https://user-images.githubusercontent.com/5493303/196008810-ec459a9a-c59b-4b0e-9779-a20e5b7069db.png">

**Comment by DanielBiegler** [comment]
Hey good idea with the material colors, I like them. You got a prefered palette in mind? I'll update the PR then.

**Comment by WDaan** [comment]
thanks for the suggestion @mylogon341

**Comment by WDaan** [comment]
Are we going with a material palette?
