### ISSUE TITLE
Login prompt even though whitelist is enabled?

### ISSUE THREAD

**Issue by jockebq** [WDaan/VueTorrent#498]
I have a weird issue where I have whitelist enabled. However, every time I connect to the WebUI I get the login prompt, which I can easily bypass by refreshing of pressing login without password.
Disabling VueTorrent theme solves this issue. So this is not a qBittorrent issue, but a VueTorrent issue. Using the latest 0.18.2 version. Had the same issue in the previous version.

Any ideas?

**Comment by WDaan** [comment]
Same as #414 I suppose
