### ISSUE TITLE
[Feature Request] Single click to expand info for torrents.

### ISSUE THREAD

**Issue by Navneet-Suresh** [WDaan/VueTorrent#50]
Currently, you have to right-click and select view info.
Proposed change is to make it a default click behavior.

**Comment by WDaan** [comment]
You can also double-click on it! (maybe a little more convenient?)

How would you propose we select torrents then? Option in right-click-menu?

**Comment by Navneet-Suresh** [comment]
Yeah, and also add support for keyboard shortcut.
Ctrl + A to select all torrents.

**Comment by ManCaveMedia** [comment]
> Currently, you have to right-click and select view info.
> Proposed change is to make it a default click behavior.

I agree!
Although it seems local to click to select and right click for more info, it's not as intuitive as it could be.

A checkbox on the top left or top right corner on mouse-over to select one or multiple seems the better option.
Don't know how that should work on mobile devices though.

**Comment by WDaan** [comment]
I've added a few shortcuts that should make selecting easier, or less of a pain at least.
I hope you like it

I will think about the checkbox idea though!

**Comment by Navneet-Suresh** [comment]
Great I will check it out!
