### ISSUE TITLE
Possible XSS in with clickable links

### ISSUE THREAD

**Issue by WDaan** [WDaan/VueTorrent#512]
In #506 raw HTML is rendered to provide clickable links. This should be implemented differently.

**Comment by turikhay** [comment]
We should define a proper CSP that will (hopefully) prevent this kind of issues from happening in the future.

We don't control what CSP the server sends to the client, but we can still [define our policy in the `<meta>` tag](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#using_the_html_meta_element)
