### ISSUE TITLE
[bug] seeding limit action reset 

### ISSUE THREAD

**Issue by bverkron** [WDaan/VueTorrent#514]
qBittorent has a "Seeding Limits > then" that does not appear in the Vuetorrent UI.
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/19174503/195263438-418963dd-d16f-4d12-b7be-08da2b44532e.png">

It seems that if you save the settings in the vuetorrent Settings > Bittorrent screen it resets that setting to the default.

This is how I have it set in qBittorrent...
<img width="425" alt="image" src="https://user-images.githubusercontent.com/19174503/195262889-c6f8daf8-a854-493d-b90e-30d15aefca8b.png">

And this is how it ends up after I've saved the Bittorrent screen in vuetorrent and switched back to the default UI. This occurs even if I don't make any changes in the Bittorrent settings screen in vuetorrent.
<img width="423" alt="image" src="https://user-images.githubusercontent.com/19174503/195262087-2c1e464f-988d-4b2f-9cc7-33ac92fec727.png">

If I save in other Settings screens in vuetorrent it does not seem to happen.

**Comment by giacomocerquone** [comment]
Since I've just worked on this piece, you can assign this to me @WDaan 🙂 

Let you know if it's some front-end or qbit bug

**Comment by giacomocerquone** [comment]
Oh no, I think I know what it was. It's just that it used to get the default value (which was 0 somehow) and set it back, but now users will be in control of that "then" clause, so this issue will automatically get close with #523

**Comment by giacomocerquone** [comment]
this can be also closed

**Comment by WDaan** [comment]
Was just looking for it 😛 

Resolved by #523
