### ISSUE TITLE
Demo Data for ease of future contributors

### ISSUE THREAD

**Issue by DanielBiegler** [WDaan/VueTorrent#518]
I'd like to contribute and I noticed that it'd be way easier to start if there would be demo-data with different statuses to immediately test different features. For example I'd like to improve pagination but I dont have any torrents so theres no pagination. I can't test it.

Maybe it'd be possible to somehow set up the volume for the docker container to already contain a couple different demo torrents?

Getting contributors up and running quicker is a great way to get more contributions.

Maybe theres another way - any ideas?

**Comment by WDaan** [comment]
That's a great idea, I've thought about it a couple of times as well.

I guess we can set an ENV variable and use a fake service to return mock-data instead. 

Seems doable

**Comment by WDaan** [comment]
Started with basic support, I guess more features will be added as we go and the need arises
