### ISSUE TITLE
Sort by Index (# in qBittorrent's UI)

### ISSUE THREAD

**Issue by hl2guide** [WDaan/VueTorrent#526]
Please add Sort by Index (# in qBittorrent's UI).

**Comment by WDaan** [comment]
I think this might be a hard one to do. The current dashboard isn't a classic table like in the default UI, it's a list of cards.
All current sorting happens on API side, and there is no index property to sort on. 

I would have to manually add an index and emit that filter when making the request and I can not guarantee that their indexes will stay the same.

This is however something that could be introuced in the Minimal Overview that was requested in #157.
Here we can generate a classic table and the behavior would be more similar to the legacy UI.

**Comment by WDaan** [comment]
I think index is actually 'Priority'?  🤔 In that case we already support it and it works just fine

**Comment by Larsluph** [comment]
And I just thought of that but I think the index is based on "Default" sort method. The default sort removes it from the API call so maybe it's what you want ?

**Comment by Larsluph** [comment]
> 5\. How come the default WebUI uses index sort? They use the same API, I presume.

They use the same API, but they are using their own components. If you check the GUI version (not the WebUI), they don't use indexes at all, it's a WebUI-specific feature, so not supported by the API.

From what I can find by digging into the WebUI source, they don't use indexes either but the queueing priority instead, if it's still not this, then we need more details on what you're talking about.

**Comment by Larsluph** [comment]
Can you tell me your version of qBittorrent ?

**Comment by Larsluph** [comment]
I just checked from the source and, as always, documentation is not up-to-date / unclear 😖. Out-of-queue torrents aren't set to -1 but 0 and qbit's sort doesn't take this into account.
https://github.com/qbittorrent/qBittorrent/blob/b1492bcd7d339ed1e758402d86005ccd4f11610b/src/webui/api/serialize/serialize_torrent.cpp#L91-L94

Knowing that, I assume that finished torrents are sorted first (value of 0) and then there are pending torrents in order of the queue, you should see them if you reverse the order but we'll need to create a rule to sort that correctly 😕
