### ISSUE TITLE
Adding peers

### ISSUE THREAD

**Issue by draco1544** [WDaan/VueTorrent#529]
On mobile (iOS with safari) it's impossible to add peers in the peers tab

**Comment by WDaan** [comment]
Not sure if that's supported? I don't see that feature in the original WebUI either?? Or am I mistaken?

**Comment by draco1544** [comment]
> Not sure if that's supported? I don't see that feature in the original WebUI either?? Or am I mistaken?

On the original webUI : click on a torrent, then go on the peer tab. Do a right click in area where peer are displayed
