### ISSUE TITLE
Right-click gesture a bit of a nightmare on mobile

### ISSUE THREAD

**Issue by mylogon341** [WDaan/VueTorrent#536]
It looks like a long press on mobile performs the right-click function a torrent row on mobile web (iOS in my test fwiw). The problem is that there appears to be a really tiny window of time that you need to hold the row for the menu to appear and stay visible. If you're either side of that tiny window (say 0.8-1.0 seconds) the menu will appear and quickly disappear and you're at risk of accidentally tapping on "force resume", or something similar. Even then, I sometimes struggle to have the menu stay open at all.

Is there a trick to doing it reliably or is this just a bit of faff atm?
Help/ improvements on this would be great. Thanks

**Comment by WDaan** [comment]
Try a 2-finger tap ;) 

However, it should be fixed nonetheless

**Comment by mylogon341** [comment]
You're quite right, that does work. I thought I'd tried that before, but I guess I... somehow messed it up?
I'll continue using this method for now as it actually does work. 
I'd suggest the fix be either disable long press, or somehow make it more forgiving. I'm not a web person, so I don't want to give it the old PM "ahhhh. that should be an easy fix" routine :D

**Comment by Asgardsurfer** [comment]
I see the same behaviour on iOS also.
If I open the link in Safari for ViewTorrent, right clicking works perfectly, but if I save the webpage link to desktop and then I open the desktop shortcut then I see the OP right click behavior.
Weird.

**Comment by mylogon341** [comment]
Heh. Funnily enough I also open it via a desktop link. The 2 finger tap does work for me though so I just avoid trying the long press.

**Comment by dooniem** [comment]
> Try a 2-finger tap ;)

This should be included in the readme.md :sweat_smile:
I was luckily wise enough to browse the issues before creating a new one

**Comment by WDaan** [comment]
Well it is still an issue tho, as it should work imo 🤷‍♂️

**Comment by Larsluph** [comment]
I don't really understand the issue you're all facing.
I personally noticed that the right click menu was disappearing when scrolling on the page, so I disabled it to be easier to scroll when it's displayed (before that, it was impossible to see the whole menu while using the WebUI on a phone with landscape orientation).

**Comment by dooniem** [comment]
> maybe because I'm on Android ??

Yes.
