### ISSUE TITLE
[Feature Request] Path Under Dashboard properties

### ISSUE THREAD

**Issue by saitoh183** [WDaan/VueTorrent#538]
In the Default Theme, you can show the path of the torrent in the global view but with VueTorrent i need to do a property on the torrent to see its saved location. I used this as a sorting filter to mass move torrents from folder A to Folder B.

**Comment by WDaan** [comment]
Path is a supported filter in the search box IIRC

**Comment by saitoh183** [comment]
Ok cool that is good to know, but would it be possible to have it in the dashboard so we can sort with paths and visually see it?
