### ISSUE TITLE
"Date added" format variables switched

### ISSUE THREAD

**Issue by Hukuma1** [WDaan/VueTorrent#546]
The Dayjs variables seem to be switched: `DD/MM/YYYY, HH:mm:ss` shows up as MM/DD/YYYY in the main view. Switching in settings to `MM/DD/YYYY` would show DD/MM/YYYY.

e.g. default setting is DD/MM/YYYY but would show November 19th as 19/11/2022 instead of proper 11/19/2022.

**Comment by Larsluph** [comment]
I'm not sure that it's a real issue.
If I understand correctly, you say that the format `DD/MM/YYYY` is showing as `19/11/2022` but that's the intended format 🤔.

**Comment by Hukuma1** [comment]
Oops. Just revisited this. Guess I forgot to click save and that may have been the issue. False alarm, sorry all!
