### ISSUE TITLE
Sort by Added On

### ISSUE THREAD

**Issue by jiznon** [WDaan/VueTorrent#55]
Is your feature request related to a problem? Please describe.
Unable to sort by Added On.

Describe the solution you'd like
I would like to have the ability to sort by Added On, and ideally set this as a default.

Additional context
My typical use-case for a WebUI is to check on the status of my most recently added torrent(s) (whether added by the WebUI or automatically via sonarr, radarr, etc). I have been unable to find a way to accomplish this. That's the one thing holding back from using any of the handful of good looking WebUi I've seen.

Thanks!

**Comment by WDaan** [comment]
![image](https://user-images.githubusercontent.com/25707052/96468432-65c1e900-122c-11eb-9757-a8045dea8450.png)

Hi! I'm afraid I don't really understand your question.
You can sort by 'Added On', you can sort by a lot of things.
Settings this option is also persistent, if you set it once... it will be set forever.
It's also the default option.

**Comment by jiznon** [comment]
Huh. On v.0.4.0 here and there is no Added On in the Sort Torrents list. 

![image](https://user-images.githubusercontent.com/4956654/96515283-14692800-1233-11eb-8f05-e4a0665ccf05.png)

However I do see now that the Default in the listing is in fact Added On. Sorry about that!

**Comment by WDaan** [comment]
No worries! 
I renamed it to avoid confusion  in v0.4.1 [#48].
