### ISSUE TITLE
Login Touch ID

### ISSUE THREAD

**Issue by Kajover** [WDaan/VueTorrent#557]
After logging in with Touch ID,
<img width="387" alt="Screenshot 2022-11-30 at 12 13 53" src="https://user-images.githubusercontent.com/83403952/204782600-4a0d6b78-625e-419b-b10a-5cd695347610.png">
the dashboard loads. However, a new prompt is being displayed. This prompt can be canceled as one is already correctly logged into the dashboard.
<img width="280" alt="Screenshot 2022-11-30 at 12 14 01" src="https://user-images.githubusercontent.com/83403952/204782767-d6a3edc0-a5e2-4ca7-9487-fbc130388fbf.png">

Not sure if this is a VueTorrent or Safari issue. This behaviour could be noted on other "apps" such as [Filebrowser](https://github.com/filebrowser/filebrowser) but not anymore - not sure how it was fixed.

**Comment by WDaan** [comment]
Was this ever figured out?

**Comment by Kajover** [comment]
The issue still persists

**Comment by Kajover** [comment]
Still happens with version 1.5.1
