### ISSUE TITLE
Inconsistent naming: Done/Progress

### ISSUE THREAD

**Issue by ManCaveMedia** [WDaan/VueTorrent#56]
While I was trying to sort the torrents by Done (percentage of total filesize downloaded) which is visible on the main dashboard I noticed there's no such option in the sort select list.
However, there is an option named 'Progress', which I believe is the same, but with a different name.

I think it's better if you choose either one of them for both the main dashboard and the sort select list.

Haven't checked for the other select options/labels.

**Comment by WDaan** [comment]
Only other 'inconsistent' ones are download (speed) / upload (speed). 
I don't add the 'speed' word because the label gets too long and it becomes a little wonky looking.
Same reason I kept using 'busy' instead of downloading.
But avoiding confusion is just as important
