### ISSUE TITLE
vutorrent webui wont load on qbittorrent 4.5

### ISSUE THREAD

**Issue by 7h3ju57** [WDaan/VueTorrent#560]
i recently updated to 4.5 and vutorrent wouldn't load the webui, after some digging i found in my qbit logs
> Couldn't load Web UI translation for selected locale (en).

i then found this mentioned in an issue posted on the qbittorrent GitHub.
> qBittorrent will no longer offer translated string to 3rd party webuis. The 3rd party webuis are supposed to handle the translation themselves (usually client-side).

https://github.com/qbittorrent/qBittorrent/issues/18109#issuecomment-1332138714

**Comment by caidaol** [comment]
WebUI\RootFolder=/config/vuetorrent

**Comment by 7h3ju57** [comment]
Just tried the Hoti docker and that's loading. Must be an issue with one of my settings I guess.

Sorry for the false issue.
