### ISSUE TITLE
Unable to type "7" when using search filter

### ISSUE THREAD

**Issue by LiFE1688** [WDaan/VueTorrent#561]
Hi,

When using search filter, you cannot type "7" or it will pop out the search new torrent window.

When you type "7" on this
![search filter](https://user-images.githubusercontent.com/119661656/205257881-0e1dda4a-a540-420c-a933-018e7c9fa907.png)

This pops out.
![search new torrents](https://user-images.githubusercontent.com/119661656/205257978-adf5e9ad-fba9-4597-b6a4-9bf2fcd64560.png)

Thanks.

**Comment by WDaan** [comment]
Good catch! Funny issue though, would have to look into why this occurs 😅  Probably a shortcut not being mapped correctly.
