### ISSUE TITLE
Add missing "autorun on torrent added" option  

### ISSUE THREAD

**Issue by rien333** [WDaan/VueTorrent#568]
qBittorrent (v4.5.0) recently gained the ability to autorun a program when a torrent is _added_. See https://github.com/qbittorrent/qBittorrent/pull/17646.

Currently, this (excellent!) web UI only allows you to configure a program to run when a torrent is finished. Or, actually, it just has one autorun option, so I suppose something needs to be done?

**Comment by rien333** [comment]
Quick aside: I woudn't really need an UI element to configure this, were it not that qbittorrent/VueTorrent would override my `~/.config/qBittorrent/qBittorrent.conf` after qBittorrent launches. Is this normal/expected behavior? (if not, I should probably take this additional isssue elsewhere)

**Comment by WDaan** [comment]
Shouldn't be able to, and haven't heard something like this before yet. It only would override them when you hit save in the settings panel.

**Comment by rien333** [comment]
hm, thanks! the overriding issue is something I will have to further investigate then.
