### ISSUE TITLE
Tags can no longer be applied

### ISSUE THREAD

**Issue by daf0x** [WDaan/VueTorrent#572]
After updating from [v0.18.2](https://github.com/WDaan/VueTorrent/releases/tag/v0.18.2) to [v1.0.1](https://github.com/WDaan/VueTorrent/releases/tag/v1.0.1) I can no longer apply tags. Previously one could:
* open the `Torrent Detail` page,
* go to the `TAGS & CATEGORIES` tab, 
* click on the `Available Tags` and `Available Categories` to add tags and categories.

However, the list items appear no longer clickable so I can't add tags to new torrents.

**Comment by WDaan** [comment]
Being worked on in #570

**Comment by WDaan** [comment]
Duplicate of #559
