### ISSUE TITLE
Filter dropdown by tags not work

### ISSUE THREAD

**Issue by snack32** [WDaan/VueTorrent#577]
Hello!

With the last version (1.1.0) the filter dropdown by tags not work (filter dropdown by categories, however, works perfect).

**Comment by WDaan** [comment]
Thanks for reporting!
This is a new feature and apparently some big slipped through 😬

**Comment by Larsluph** [comment]
It works for me 🤔. Can you give more detail on why it is not working for you ?

**Comment by WDaan** [comment]
I've tested as well and don't see anything wrong with the feature.

**Comment by snack32** [comment]
Tested on safari (iOS, mobile version). 

When I select a tag in the filter dropdown, it doesn't filter the torrents with the tag.

I have not tried it in the desktop version yet.

**Comment by Larsluph** [comment]
It works for me, try clearing your cache or force reload all (Cmd+Option+R if I'm not mistaken)

**Comment by snack32** [comment]
I have tried deleting cookies, deleting vuetorrent and downloading again.. with no luck.

For example, see attached screenshots. One torrent have the “privileged” tag. But selecting these tag on dropdown list still showing all torrents.

![2EE0B398-7774-49CB-B61F-D7C145BE324F](https://user-images.githubusercontent.com/23261891/210093897-c4c7cf7f-50ef-4e99-8b51-cd0dc421c8e8.jpeg)
![CAFEA7B8-979F-40CD-93E1-EF4726378A98](https://user-images.githubusercontent.com/23261891/210093902-db0a55f5-2d9d-4550-be85-2775a7c41674.jpeg)

**Comment by Larsluph** [comment]
If you only deleted your cookies, I'm not sure if it can resolve the issue.
I don't have an iPhone to check the issue unfortunately 😕

**Comment by snack32** [comment]
Sorry for not being more precise, when I said to delete cookies, I meant to delete all data (site data).

In any case, I have done some more tests:

Trying a new browser (opera) that allows me to force the desktop version. Result: both (desktop and mobile mode) failed to filter by tags.

Trying chrome in desktop computer. Again, failed to filter by tags (!). And this has surprised me because I thought that, if the bug existed, it would be related to the mobile mode.

If the bug really existed (and it wasn't a mistake on my part) could it be related to the Qbit version? (4.3.9 in my case).

**Comment by Larsluph** [comment]
And how did you installed VueTorrent ?

**Comment by snack32** [comment]
Downloading the lastest version from github and unzip.

**Comment by snack32** [comment]
I just ran a few more tests:

- Clean qbit (4.3.9) new install. As expected, filter by tags in dropdown list not work.

- Clean latest qbit version (4.5.0) new install. And… work!!

So as I said two days ago, maybe the problem comes from oldest qbit versions?

**Comment by Larsluph** [comment]
Good point, I just checked and the endpoint added the tag parameter in the latest update of the API (released in the 4.4.0)
source: https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#api-v283
