### ISSUE TITLE
change location doesn't prefill

### ISSUE THREAD

**Issue by reyqn** [WDaan/VueTorrent#581]
Before 1.1 release, I think the change location command prefilled the field with the location of the torrent.

It doesn't anymore. It would be nice if it did.
 
Also the batch change location should probably prefill with the location of the first torrent selected.

Right now I can't really check, but if you think the behavior I'm describing is okay, I can try to fix it when I'm back from holidays.

**Comment by Larsluph** [comment]
Yup, it's a known issue, i'm currently working on it.
If you really want it to be autofilled, you have to open the settings before the modal.
