### ISSUE TITLE
Add Keyboard navigation in Torrent Details - Content tab

### ISSUE THREAD

**Issue by EduCampi** [WDaan/VueTorrent#60]
Example:
Torrent with multiple files where we don't want to download all of them.
Right now, one has to scroll down and click one at the time, it would be way quicker if we could navigate with down/up arrows and use the spacebar to select/deselect.

Being able to hold shift to select from one file to another one would also be great.

Thanks,

**Comment by WDaan** [comment]
With the current implementation, I don't think either of those solutions is possible.

There is an open issue about it in the framework though, so it might get solved: https://github.com/vuetifyjs/vuetify/issues/10796

**Comment by m4ximuel** [comment]
I'm working on for this.

**Comment by WDaan** [comment]
Really? It's a tough one to solve, the framework itself doesnt even have a proper solution.

Maybe use the Google material datatable instead of the vuetify one?

Good luck! Let me know if you need any help

**Comment by m4ximuel** [comment]
@WDaan #216
