### ISSUE TITLE
VueTorrent missing advanced settings

### ISSUE THREAD

**Issue by wtesler** [WDaan/VueTorrent#605]
The plain Qbittorrent UI has a tab under settings called Advanced Settings which has, for example, an option to let you choose which network interface you want to use (important for VPN). That tab seems to be absent when using the VueTorrent UI. Am I missing something or is it not available?

**Comment by WDaan** [comment]
Probably not yet available

**Comment by tmknight** [comment]
Feature request submitted: https://github.com/qbittorrent/qBittorrent/issues/18481

Give it upvotes to help push it through

**Comment by tmknight** [comment]
See how to accomplish this here: https://github.com/qbittorrent/qBittorrent/discussions/18487#discussioncomment-4823174

**Comment by CBEpt** [comment]
Could you add this advanced setting feature to the main branch? thanks! felt like missing something...

**Comment by WDaan** [comment]
@CBEpt this is still an open source project, not a restaurant. Feel free to submit a PR yourself.

Settings & features are being added as we go, it's has been this way since the beginning.

Thx for supporting the project!
