### ISSUE TITLE
Redirect to login after idle

### ISSUE THREAD

**Issue by WDaan** [WDaan/VueTorrent#607]
When using the PWA and closing the app, upon reopen it will open the same view but data won't refresh as the cookie is expired.

You have to force close the app in order to get the login screen again and you can re-authenticate.

Todo:

Investigate why? Is the first Auth check falsely passing? Redirect not working? ...?

**Comment by WDaan** [comment]
seems to be resolved now

**Comment by RoboMagus** [comment]
I figured this might be due to me having no authentication setup for VueTorrent itself, but the whole thing hosted behind Authentik as ForwardAuth.

I'll follow this issue to see if it might be something else after all.

**Comment by WDaan** [comment]
I don't have anything in front of Vuetorrent and still run into this, mostly when using the PWA on my phone. Which I then have to force close, so that I'm able to login again. Not sure where in the chain this goes wrong.
