### ISSUE TITLE
Copy paste is not working

### ISSUE THREAD

**Issue by VuzzyM** [WDaan/VueTorrent#614]
Hello.

Copy paste is not working on Xiaomi with Gboard keyboard. Please fix.

![IMG_20230121_173515](https://user-images.githubusercontent.com/66425682/213874319-61643f05-a490-427e-b083-f69d069cf6cc.jpg)

**Comment by WDaan** [comment]
I know it's not a fix, but you should be able to paste by clicking on the icon as well.
