### ISSUE TITLE
Add qBittorrent version

### ISSUE THREAD

**Issue by jef** [WDaan/VueTorrent#63]
It'd be nice to have the version printed _somewhere_. Can't really suggest where, but perhaps somewhere!

**Comment by WDaan** [comment]
Maybe just under the Vuetorrent version? I know it doesnt really belong there but I don't know where else to put it

**Comment by jef** [comment]
Yeah, me either 😅 I'll download and test. You work fast! 🚀

**Comment by WDaan** [comment]
I just happened to have a tiny bit of spare time this morning 😅

It's not yet released though!  I am re-making the search modal and want to add that to the next release.
I don't want to make a new release for every single thing I change, unless you guys prefer that...

Btw thank you so much for your donation! I really do appreciate the support and the feedback.

**Comment by jef** [comment]
Oh yeah, no problem!

Yeah, it's hard to find a release cadence. What I've found to be good is having some sort of nightly/develop branch and then a release branch.

That way users can decide what they want. Usually nightly will be stable, but could be unstable. As main/release would be stable.
