### ISSUE TITLE
Settings sometimes not saving

### ISSUE THREAD

**Issue by EctoBoggan** [WDaan/VueTorrent#634]
Hey,

First of all : amazing work with this project, I like it !

I'm here to report a little bug : 

Sometimes, when clicking on the save buton in order to save my settings, the settings tab just close itself.

- When this happen any change made before the save will be discarded.
- When the setting tab doesn't close after clicking on the save buton, everything is saved.
- In every scenario the green popup shows up.

I'm using [linuxserver/qbittorent](https://hub.docker.com/r/linuxserver/qbittorrent)'s docker image on a Synology NAS.

It's not that bad because after setting up everything you'll never touch it again for a long time. 
But i'm pretty sure it never happened before switching to a custom UI.

Sorry for my english,
Have a nice day.

**Comment by Larsluph** [comment]
Can you check in the DevTools of your browser if the request is sent correctly?
Press F12 to open your devtools, then click on the `Network` tab.

You should see a line added when you press the save button like so :
<img width="299" alt="image" src="https://user-images.githubusercontent.com/22910497/216443849-9bc33d46-a8ac-4547-96f5-66d1c5f82e91.png">

**Comment by EctoBoggan** [comment]
I did some test and I sometimes get status code 502 like this one but on `preferences` : 
![Snag_11870cc0](https://user-images.githubusercontent.com/54527880/216449210-49245de1-3e37-436f-b05e-662ab8ae2c74.png)

All `SetPreferences` were 200.

I tested it right after your message for about 5 minutes and only got 5 non-saving changes out of ~ 60 (which is a lot less than what I went through)

Anyway as I said I just wanted to point out the problem but it's not that problematic. It could be my Browser (Opera GX)
