### ISSUE TITLE
Speed graph flickering

### ISSUE THREAD

**Issue by flaggz** [WDaan/VueTorrent#637]
The speed graph is flickering on Mac without Magic Mouse 
Vuetorrent 1.2.0
qBittorrent latest svn
Safari 16.3 on macOS 13.2 Ventura 

https://user-images.githubusercontent.com/7655589/216767904-bd097ee9-173d-4e3c-947b-1ea0d6d17cde.mov

**Comment by tmknight** [comment]
Seeing something similar in stats now in v1.3.0 on Linux (was fine with 1.2.0)

**Comment by Hukuma1** [comment]
Same. I am seeing all-time stats flicker from 0s to proper numbers (e.g. goes from 0 to 11gb and back). Also disconnected symbol at the bottom.

**Comment by flaggz** [comment]
Still happens on 1.3.0 even after cache cleaning

https://user-images.githubusercontent.com/7655589/217761681-1f237369-0036-44de-a2fb-3ab40b757ee1.mov

**Comment by flaggz** [comment]
same with 1.3.1 on MacOS Safari


https://user-images.githubusercontent.com/7655589/218198373-fc38a71f-2431-4737-890d-191530bd15c2.mov

**Comment by Larsluph** [comment]
Can you send the entire side panel, and your screen resolution / screen size ?

**Comment by flaggz** [comment]
> Can you send the entire side panel, and your screen resolution / screen size ?

The flicker is gone with 1.3.2
