### ISSUE TITLE
Incorrect handling of magnet links?

### ISSUE THREAD

**Issue by RoboMagus** [WDaan/VueTorrent#638]
I've been trying arround with the `MagnetHandler`, and it seems that how the URL parameters are passed the information is lost.

Though it's also very possible that I'm mis-interpreting the spec: [Link](https://en.wikipedia.org/wiki/Magnet_URI_scheme).

When copying a magnet URL and pasting it behind `https://FQDN/#/download=` it results in a URL like `https://FQDN/#/download=magnet:?xt=urn:btih:[...]`. Following this URL the add download dialog only shows `magnet:` in the URL field.

Thoughts?

**Comment by PedroBuffon** [comment]
i'm having that problem too, i run qbittorrent on my raspberry pi in docker with VueTorrent and i'm trying to set the MagnetHandler, when i click a magnet, the url opens and it's just a blank screen just with the network graphs.

**Comment by Larsluph** [comment]
I think that's because you didn't URI encoded it so your browser interprets the ? character as a URL parameter separator, though not passing it to the MagnetHandler correctly.

So for example the magnet link
`https://FQDN/#/download=magnet:?xt=urn:btih:[...]` becomes
`https://FQDN/#/download=magnet%3A%3Fxt%3Durn%3Abtih%3A[...]`

**Comment by PedroBuffon** [comment]
i got magnet handling working by enabling HTTPS with selfsigned certs on my qbittorrent webui, after that no more blank screens @RoboMagus , try enabling HTTPS too and see if the problem persists. if not idk what it is

**Comment by RoboMagus** [comment]
`HTTP` vs `HTTPS` shouldn't be an issue for me as I'm hosting my setup as `HTTPS` anyway.

What @Larsluph mentions is indeed the issue. After URL-encoding the magnet link and appending the result to the `https://FQDN/#/download=` URL does work. But since the [magnet link URI scheme](https://en.wikipedia.org/wiki/Magnet_URI_scheme) is built up in a way to indicate URL parameters it seems counter intuitive to encode this again (especially since often most of these parameters already contain encoded strings).

From what I can tell, these links should be used _as-is_. I could be wrong, but @WDaan already flagged this issue as a bug, so I'm guessing thats the case.

**Comment by Larsluph** [comment]
From the nature of a URL, I don't know how we can pass a value which contains question marks without encoding it first 🤔

**Comment by jagadam97** [comment]
https://github.com/WDaan/VueTorrent/pull/1041
further testing is appreciated
