### ISSUE TITLE
Have Shutdown Application button ask for confirmation?

### ISSUE THREAD

**Issue by Hukuma1** [WDaan/VueTorrent#641]
Not sure if it's muscle memory, but I accidentally hit the shutdown button that's right next to the settings cog wheel and was surprised there was no confirmation yes/no to go ahead with such an action. Is it possible to implement?

And if not, could it be possible to have a setting to hide this button altogether?

**Comment by brezinajn** [comment]
It'd be lovely if you could disable the new button.

**Comment by WDaan** [comment]
I think a confirmation pop-up is the way to go.

**Comment by tmknight** [comment]
Either confirmation (preferred) or reconsider button placement elsewhere.  For those with more robust QBT implementations, the shutdown button is a welcome and required asset.

**Comment by Samillion** [comment]
> Either confirmation (preferred) or reconsider button placement elsewhere. For those with more robust QBT implementations, the shutdown button is a welcome and required asset.

Agreed, both would be perfect to be honest. Moving the Shutdown button (with confirmation) next to Logout button would make sense, in my opinion.
