### ISSUE TITLE
Graphs reset to 0 data when there is no active torrent.

### ISSUE THREAD

**Issue by ValTM** [WDaan/VueTorrent#642]
qBittorrent 4.3.0
Vuetorrent 1.3.0
Regression from 1.2.0

When I visit Vuetorrent the graphs are 0 if there is no active torrent. If there is any activity they randomly populate (with correct data) and then depopulate. Videos attached.

[Video 1](https://i.imgur.com/E62EaDN.mp4) shows graphs depopulating.
[Video 2](https://i.imgur.com/Y18tTTZ.mp4) shows graphs depopulating/repopulating when I pause and restart an active torrent.

**Comment by tmknight** [comment]
Seems related to #637

**Comment by ValTM** [comment]
Right, it looks like it's the same, I somehow didn't see that other issue. Closing this one.
