### ISSUE TITLE
Status bar values jumping about from 0 to correct value

### ISSUE THREAD

**Issue by mylogon341** [WDaan/VueTorrent#646]
Running v1.3.0 dashboard on a dockerised qBit
–

https://user-images.githubusercontent.com/5493303/217761444-40cd3c8b-15a8-4a9e-8856-7b55144107df.mov

Attached is a video to show what I mean. In this video you can see how all the values are incorrectly at 0. This container has actively been running for about 4 days now so even the session stats should be up in the GBs. (edit: I have now restarted that container and it has not helped matters)

I then tap resume on a ubuntu image and it starts up straight away and some of the stats jump from 0 to >900GB for disk space and then back to 0 again, seemingly randomly. Yesterday the speed line chart was also humping back down to 0 and 4MB/s but that seems to be intermittent now too.

I'm assuming/ hoping this is a vuetorrent issue and that it is resolvable as it's quite annoying :|
Thanks a lot.
Luke

**Comment by Neverends4** [comment]
Same here.
qb version 4.5.0+VT UI 1.3.0
platform ARM 64 linux. 
Seems V1.2 does not have this issue.

**Comment by WDaan** [comment]
Solved in https://github.com/WDaan/VueTorrent/pull/644 I believe.

**Comment by mylogon341** [comment]
A thanks. Sorry for the duplicate bug. I didn't look through the closed tickets so made this one. Thanks for the release.
