### ISSUE TITLE
Ctrl or Command + click not behaving as expected on MacOS

### ISSUE THREAD

**Issue by PMarci** [WDaan/VueTorrent#648]
Expectation:
- Executing one of the following will select a torrent from the main view
  1. <kbd>⌃ Control</kbd> + <kbd>LMB</kbd>
  1. <kbd>⌘ Command</kbd> + <kbd>LMB</kbd>
 
Actual behavior:
- Firefox:
  1. <kbd>⌃ Control</kbd> + <kbd>LMB</kbd> brings out the right-click context menu of the list item
  2. <kbd>⌘ Command</kbd> + <kbd>LMB</kbd> does nothing
- Safari
  1. The first <kbd>⌃ Control</kbd> + <kbd>LMB</kbd> brings out the right-click context menu, but a second <kbd>⌃ Control</kbd> + <kbd>LMB</kbd> outside of the context menu, still on the list item will enable selection mode and select it
  2. <kbd>⌘ Command</kbd> + <kbd>LMB</kbd> does nothing

I think it'd be most convenient to have a MacOS environment use <kbd>⌘ Command</kbd> + <kbd>LMB</kbd> instead of however the keys are identified currently, since that combination doesn't seem to do anything else in this context.

**Comment by Larsluph** [comment]
Fixed with acb75a6a81e9634531f53107876b7ccbeeecf82a ?

**Comment by WDaan** [comment]
@Larsluph Not sure, kind off? Not all shortcuts described here are implemented. But now the behaviour for Mac does work properly.
