### ISSUE TITLE
Torrent info / peers no information 

### ISSUE THREAD

**Issue by tmknight** [WDaan/VueTorrent#652]
V 1.3.1
First appeared in 1.3.0

Torrent info / peers on active torrent displays no peers.

Mobile and desktop

**Comment by Hukuma1** [comment]
<img width="627" alt="emptypeers" src="https://user-images.githubusercontent.com/54511555/218356484-8e1c664f-dd59-4701-a5d0-581a358c957c.png">

Seeing this myself. This is on an active torrent with many connections.

**Comment by EzrealC** [comment]
same problem

**Comment by halexh** [comment]
Same here
