### ISSUE TITLE
All torrents are invalid torrents

### ISSUE THREAD

**Issue by jef** [WDaan/VueTorrent#66]
### Description

It seems like _all_ torrents are invalid when adding. I switched back to use the old UI and it worked (just to make sure qBittorrent wasn't goofing up, I had to roll back to 4.2.x for something else).

![image](https://user-images.githubusercontent.com/12074633/97709826-52ffad80-1a91-11eb-9f8f-365380311c3b.png)

**Comment by WDaan** [comment]
![image](https://user-images.githubusercontent.com/25707052/97710995-c834a800-1abc-11eb-875d-20816a45ae5c.png)

it works fine for me 😮

**Comment by jef** [comment]
Oh wow. Okay, I should have the latest release. I've been using the **Release** zips.

Here is the torrent I was testing with: https://www.archlinux.org/releng/releases/2020.10.01/torrent/

**Comment by WDaan** [comment]
![image](https://user-images.githubusercontent.com/25707052/97713692-7857e000-1ac0-11eb-88db-25f38bcc2e69.png)

I retested with your file, and I don't have any issues either

**Comment by jef** [comment]
Printing out all the `f.type`s as well doesn't return anything:

![image](https://user-images.githubusercontent.com/12074633/97714086-18007880-1a97-11eb-85ca-81a4a9c86b90.png)

I wonder if it's a browser issue? I don't know anything about front end stuff 😆

**Comment by jef** [comment]
Here we go, this is much more informative:

![image](https://user-images.githubusercontent.com/12074633/97714516-a37a0980-1a97-11eb-8244-c8b1656205e6.png)

**Comment by jef** [comment]
I suppose a fallback if sites don't set the MIME type:

![image](https://user-images.githubusercontent.com/12074633/97715509-de307180-1a98-11eb-9f0f-e0c2a89c0912.png)

```diff
diff --git a/src/components/Modals/AddModal.vue b/src/components/Modals/AddModal.vue
index 2138bd6..c7d718c 100644
--- a/src/components/Modals/AddModal.vue
+++ b/src/components/Modals/AddModal.vue
@@ -131,7 +131,11 @@ export default {
             skip_checking: false,
             fileInputRules: [
                 v => {
-                    const result = v.every(f => f.type === 'application/x-bittorrent' )
+                    const result = v.every(f => {
+                        console.log(f)
+                        if (f.type.length !== 0) return f.type === 'application/x-bittorrent'
+                        else return /^.*\.torrent$/.test(f.name)
+                    })
                     return result ? result : 'One or more files is not a valid torrent'
                 }            
             ],
```

That being said, I don't know why yours would work and mine wouldn't since we're downloading the same torrent. Web stuff is way out of my domain 😅

**Comment by WDaan** [comment]
That might be the case! I'm using chrome both on Linux and Windows.

If you'd like, you can create a pull request with your fix (so it counts as your contribution)

**Comment by jef** [comment]
I tried that as well on both machines! Pretty weird behavior. I haven't tested on my macOS, but it's quite strange...
