### ISSUE TITLE
Use Vuetorrent to connect to remote servers

### ISSUE THREAD

**Issue by LenKiMo** [WDaan/VueTorrent#661]
Due to performance issues with the download server (assumed to be Server A), I need to deploy Vuetorrent from another server (assumed to be Server B) and connect to qBittrorrent on Server A.

When uploading Vuetorrent on Server B and accessing it, I was asked to enter my username and password. But it seems that the project does not provide this default username and password.

I would like to know if there is a username and password that will allow me to install and access Vuetorrrent on a server that does not have qbittorrent installed, and if I can manage downloads from Server A remotely from Server B.

**Comment by WDaan** [comment]
VueTorrent is build to be a WebUI for QBittorrent. 

So you're question is, how would I operate a QBittorrent instance A from another instance B? 

Only way you could kind off make this happen is attach VueTorrent to something like Nginx and proxy all api calls to instance A.

Either way, this doesn't seem to be an issue with Vuetorrent itself. 

This can become an issue or a section on the wiki perhaps. (If we come up with a working solution)
