### ISSUE TITLE
Dark theme background color black after 1.3.0

### ISSUE THREAD

**Issue by MBR-0001** [WDaan/VueTorrent#662]
I upgraded from 1.2.0 to 1.3.0 and now the background is black

|Before|Now|
|----------|------|
|![242081102678851597](https://user-images.githubusercontent.com/55142207/219861779-8fb56599-47dc-4ad0-8a58-5978234a5c63.png)|![242080238098579468](https://user-images.githubusercontent.com/55142207/219861973-0cb84bb8-f5b8-44a3-8927-18fb3f73fe4b.png)|

It appears that `--v-background-base` css var was not defined before, now it is `#000000`

idk if this was intentional or not but it seems like a bug to me :monocle_face:

**Comment by WDaan** [comment]
Heh! That's weird indeed. 
Not sure what went wrong there but should be an easy fix.
