### ISSUE TITLE
[bug] Peer list queried successfully but not showing up in the UI.

### ISSUE THREAD

**Issue by yohaoquan** [WDaan/VueTorrent#668]
Hi. Great work on the UI! I loved using it thus far and ventured on a bug today. 

![Screenshot 2023-02-20 022922](https://user-images.githubusercontent.com/16907613/220040823-83266708-ce5a-479b-a7b1-69f3cd293ac8.png)

I can see from network requests that qbittorrent is correctly returning a list of peers along with their information back to the browser but it is not showing up in the UI. There was no error in the console either.

I am using [hotio's qbittorrent](https://hotio.dev/containers/qbittorrent/) docker image, with UI Version 1.3.1 and qBittorrent version 4.5.1.

I tried using my own copy of UI package downloaded from GitHub and it is the same. Any ideas?

Cheers!

**Comment by WDaan** [comment]
I believe this was solved in #660?

Just not released yet. Perhaps we should do that first
