### ISSUE TITLE
Feature request: see torrent content before downloading

### ISSUE THREAD

**Issue by marcusique** [WDaan/VueTorrent#671]
**What:** It would be great to have the ability to see and select content before starting the download.
**Why:** It would save users a couple of clicks.
**Notes:** Perhaps the files should't be automatically pre-fetched. Could be a button to show torrent content when needed to prevent [this](https://github.com/WDaan/VueTorrent/issues/304).

**Comment by Larsluph** [comment]
This is impossible to make using a WebUI. However, the feature is available using the native app (on a local machine ofc)
