### ISSUE TITLE
Feature Request: Home Assistant integration

### ISSUE THREAD

**Issue by bobloadmire** [WDaan/VueTorrent#678]
I have an offsite integration I would like to control via Home Assistant, would be cool to make this an add-on. Also have you ever considered NZBGet management as well?

**Comment by RoboMagus** [comment]
For this to integrate with HomeAssistant you'll want to integrate with qBittorrent which is the actual application. VueTorrent is mainly an alternative UI on top of it.

If you want it as an addon, [here's a link](https://community.home-assistant.io/t/home-assistant-addon-qbittorrent-supports-openvpn-smb-mounts) to a forum page with all details required. The addon even supports alternative UI's of which VueTorrent is one 😉 .

**Comment by RoboMagus** [comment]
The fact still stands that this is just an alternative UI, installed on top of qBittorrent. You cannot have this, without its base application. Separately installing it won't work.

If all you want is to display the webpage of VueTorrent inside the HomeAssistant environment you're looking for `panel_custom`.

**Comment by bobloadmire** [comment]
Oh got it, I thought it was a standalone web server that you just linked to
the standard web interface of QBT.

**Comment by WDaan** [comment]
Thx for the explanation @RoboMagus, I don't know why people keep forgetting that 😅
