### ISSUE TITLE
Feature Request: Compact View

### ISSUE THREAD

**Issue by akballow** [WDaan/VueTorrent#680]
Is it possible to please implement a toggle where we can switch the list view from the current view to a compact view where the height of each torrent is shrunk to one line so that more torrents can be seen at once. This view is good for desktops where horizontal space is more present then the mobile. Thank you for looking.

**Comment by WDaan** [comment]
Closed in favour of #157

**Comment by realindiahotel** [comment]
> Closed in favour of #157

It seems that #157 is from some years ago.

I do like the datatable shown in that issue, but where is it?
