### ISSUE TITLE
Option to hide / remove shutdown button from UI

### ISSUE THREAD

**Issue by RoboMagus** [WDaan/VueTorrent#684]
After updating I found the addition of the shutdown button.
There will probably a large group of users for which shutting down the client is not desired option to expose.

I'd love for there to be an option to remove this button from the UI, as was also suggested by @brezinajn in #641.

It's a good option, but an _opt-out_ would be nice.

**Comment by brezinajn** [comment]
You're right. In my use case I don't want to kill the client ever and if that ever happens I need to restart the docker container. So even with a good UX there is a danger, that any of my users just kills the client for everybody and I'd need yo manually intervene.
