### ISSUE TITLE
Individual content percentage does not automatically update [1.5.0]

### ISSUE THREAD

**Issue by DjordjeMandic** [WDaan/VueTorrent#696]
![chrome_whKhwKLfO0](https://user-images.githubusercontent.com/6750655/222959694-eddedbb6-584d-4a3a-8279-5754ce8c5973.png)

Shouldnt this be automatically updated? It does update when i press F5 to reload whole page but it does not update as im looking at it. It does update also if i switch between tabs in torrent detail

**Comment by Larsluph** [comment]
Related to #359, it's made that way to prevent performance issues with large torrents as we need to reload the whole content tree to update that data.
