### ISSUE TITLE
[Bug] Torrent  Info Tracker: Delete does not delete

### ISSUE THREAD

**Issue by tmknight** [WDaan/VueTorrent#697]
Attempting to delete a tracker from an active (downloading) torrent does not delete and results in all trackers being selected.

No issues adding trackers.

First observed in v1.4.0

Observed in:

- Chrome for PC 110.0.5481.178 
- Chrome for Android 110.0.5481.154

Version: 1.5.0
QBT: 4.5.2

**Comment by Larsluph** [comment]
Got a 400 when trying to delete a torrent, should be like #667
