### ISSUE TITLE
New fields are not added unless you reset your settings

### ISSUE THREAD

**Issue by Osyx** [WDaan/VueTorrent#698]
When updating to 1.4.0 I noticed that no matter how hard I looked, I couldn't find the Tracker field. 
Turns out that it was because it didn't exist for me, in order to get the field I had to reset my settings, and I could then choose to display the field if I wanted. While resetting, I also found out that there were quite a few other fields that I had missed out on before this.

Expected:
A new field is added, it shows up as deselected for users who had a previous version under Settings > VueTorrent > Desktop Card.
Current: 
A new field is added, it is missing from Settings > VueTorrent > Desktop Card for previous users unless they reset their settings.

**Comment by Osyx** [comment]
When updating to 1.5.0 it seems my fields were reset instead 😅

**Comment by WDaan** [comment]
Known issue, since the beginning. It's due to the way settings are stored as an object into localstorage in a rather naive way. Not yet sure how to better support this behaviour yet.

There might be other issues open about this.

**Comment by Larsluph** [comment]
> When updating to 1.5.0 it seems my fields were reset instead
That's normal, we changed the naming of that property to prevent confusion with the other attributes.

If you want to keep your settings, you'll have to export your settings and merge your settings manually for now.

**Comment by Osyx** [comment]
> Known issue, since the beginning. It's due to the way settings are stored as an object into localstorage in a rather naive way. Not yet sure how to better support this behaviour yet.
> 
> There might be other issues open about this.

Ah I see. I didn't find any other issue so I'll leave this open, but feel free to close if you know/see one.

> > When updating to 1.5.0 it seems my fields were reset instead
> 
> That's normal, we changed the naming of that property to prevent confusion with the mobile card attributes.
> 
> If you want to keep your settings, you'll have to export your settings and merge them manually for now.

Ah makes sense, thanks!
