### ISSUE TITLE
Renaming content causes the "item wanted" check mark to be deselected.

### ISSUE THREAD

**Issue by StevenAlexander44** [WDaan/VueTorrent#703]
When renaming a file/folder, after pressing the "save" button, then changing Vue tabs (eg. go to Info, then back to content), then the renamed file/folder is no longer checked as wanted.

Tested on Mobile and Desktop Chromium with no extensions enabled.

**Comment by Larsluph** [comment]
That's interesting, thanks for noticing it
FYI it's just a visual bug, if you close and reopen the torrent detail it will show the correct status
