### ISSUE TITLE
Checkbox status not cleared after action

### ISSUE THREAD

**Issue by kdbruin** [WDaan/VueTorrent#704]
I have added a whole bunch of magnet links in paused mode and when I filter on all paused torrents I can select a few to start downloading. These are removed from the paused view but when I now select (using the checkbox, not the context menu) another torrent and e.g. remove it using the global delete button, it will also remove the torrents just started.

To prevent this I need to clear the filter and uncheck any torrents still selected.

This is with version 1.0.1 according to the settings page. Will check if it still exists with the latest version.

**Comment by kdbruin** [comment]
Just check with the latest code and it is still happening.

**Comment by Larsluph** [comment]
Duplicate of #427

**Comment by kdbruin** [comment]
Did a search on checkbox but not selected so didn’t catch this. Will close this issue.
