### ISSUE TITLE
Can't show country icons

### ISSUE THREAD

**Issue by LWF666** [WDaan/VueTorrent#707]
When I download torrent, User iformations can't show country icons, like this picture:

![image](https://user-images.githubusercontent.com/44828065/224916612-76db15f7-8e3c-40d7-bdbf-eabb21a5fbf5.png)

I am in China, maybe I need to change a CDN of icons, but I don't know how to to, I wan't your help! please

**Comment by k4lu-0p** [comment]
can you try with a VPN ?

**Comment by Larsluph** [comment]
URL for flag is found here in code
https://github.com/WDaan/VueTorrent/blob/master/src/helpers.js#L50

You can also check devtools to find flags requests

**Comment by LWF666** [comment]
Thanks, I don't have a VPN to use, So I want to change CDN of icons, But I don't use this qBittorrent 
 theme now, I will try to change `helpers.js` after!
