### ISSUE TITLE
Empty rows on mobile

### ISSUE THREAD

**Issue by reyqn** [WDaan/VueTorrent#716]
Since updating to 1.5.1, on Firefox mobile, the rows displaying torrents don't show any text (actions still work on each row). The rows are showing everything as expected on desktop layout.

![Screenshot_20230319-113957_Firefox_Nightly](https://user-images.githubusercontent.com/12498695/226169906-61be9cd4-7667-4ab7-8e3a-6c63912a9b5d.jpg)

**Comment by Larsluph** [comment]
Problem comes from the migration of some components in the Desktop and mobile card, resetting your settings will resolve the issue

**Comment by Larsluph** [comment]
Linked to #698

**Comment by reyqn** [comment]
Thanks!
