### ISSUE TITLE
Upload/Download Speed Missing: v1.5.1

### ISSUE THREAD

**Issue by tmknight** [WDaan/VueTorrent#717]
I see the "place holders" in properties, however, it appears the values may have been miscoded:
![image](https://user-images.githubusercontent.com/548588/226171156-c475d9d1-c7b9-4c1f-b52c-fd5d709fc2bf.png)

**Comment by Larsluph** [comment]
We changed the name in the newest release to prevent confusion with other names, you need to reset your settings to fix the issue
Linked to #698

**Comment by tmknight** [comment]
Got; resolved.
