### ISSUE TITLE
No icon for Apple devices

### ISSUE THREAD

**Issue by agneevX** [WDaan/VueTorrent#72]
The href link for `apple-touch-icon` is incorrect in the release branch.

**Comment by agneevX** [comment]
@WDaan this is not an enhancement but a bug.

**Comment by WDaan** [comment]
I don't have an apple device at my disposal, maybe someone else can take a look at this issue. :slightly_smiling_face:

**Comment by agneevX** [comment]
Well I did. As I mentioned, the href link in index.html needs to be corrected.

**Comment by WDaan** [comment]
There is no reason to be rude....

I can't just edit the index.html in the 'latest-release'-branch because it is auto generated.
I will try renaming the picture. If you would be so kind to test it out

**Comment by WDaan** [comment]
Closed due to inactivity

**Comment by agneevX** [comment]
Lol what?

**Comment by WDaan** [comment]
3 weeks ago, I asked if you could test wether it worked or not.
I haven't  gotten a reply, so I assumed it was no longer an issue.

What do you expect from me??? I work on this for fun on my free time

**Comment by Asgardsurfer** [comment]
WDaan, Thanks for your continued great work on this project. Just to let you know that on an iOS device the icon shows up perfectly on the desktop￼.

**Comment by WDaan** [comment]
Awesome! Thanks for letting me know

**Comment by agneevX** [comment]
The correct icon is showing up, however it needs a white background and some padding. I can chalk up a PR, if you want?

**Comment by WDaan** [comment]
Yes! That would be great? 🙂
