### ISSUE TITLE
Not visible torrents list

### ISSUE THREAD

**Issue by lyaschuchenko** [WDaan/VueTorrent#725]
Just put screenshot here. Version 1.5.1
![Screenshot_2023-03-20-23-51-53-786_com android chrome](https://user-images.githubusercontent.com/15934644/226473792-644a3218-3e88-4c8e-a1d6-1f39a2fc7906.jpg)

**Comment by Larsluph** [comment]
Duplicate of #723

**Comment by lyaschuchenko** [comment]
yes, solution help.
