### ISSUE TITLE
Mobile mode 1.5.2

### ISSUE THREAD

**Issue by mercu01** [WDaan/VueTorrent#729]
Mobile mode error:
![Screenshot_2023-03-21-16-01-27-510_org mozilla firefox](https://user-images.githubusercontent.com/9451876/226648754-98b5ab26-7de9-4661-a399-49747fb5be93.jpg)
Version:
![Screenshot_2023-03-21-16-04-11-610_org mozilla firefox](https://user-images.githubusercontent.com/9451876/226648763-7dcaa96d-4cf1-49ea-84e0-3a39f65c5e3a.jpg)
Config, all checked in molbile card 

Thanks

**Comment by SinTan1729** [comment]
@WDaan This issue is still happening in the latest release 1.5.2 although the older issues are marked as completed.

**Comment by Larsluph** [comment]
You have to reset your settings to see the torrent on mobile card

**Comment by SinTan1729** [comment]
@Larsluph That's very annoying, but it worked. Thanks.

**Comment by mercu01** [comment]
@WDaan Sorry for the duplicity of issue. Thank you all for your help @SinTan1729 @Larsluph

**Comment by Larsluph** [comment]
> That's very annoying
Yes we know, I'm thinking of improving the settings system to include some kind of migration system to prevent that

**Comment by mercu01** [comment]
> > That's very annoying
> 
> Yes we know, I'm thinking of improving the settings system to include some kind of migration system to prevent that

I don't know how it works behind it. And if you perform a migration takes a long time to develop it. An alternative, if you can detect the problem, would be to directly reset the settings so as not to fall into the bug. Best regards

**Comment by Larsluph** [comment]
We currently don't have any way of knowing if the version has changed but that can be fixed pretty quickly, I'll think about that
