### ISSUE TITLE
Vue3 migration

### ISSUE THREAD

**Issue by WDaan** [WDaan/VueTorrent#734]
## Description

Now that Vuetify V3 has been released, we can get started on migrating the project to Vue's latest and greatest.
I suggest we keep this issue to track all parts/components related to the migration

## Components
- Navbar
- Modals
- Desktop/Mobile Card
- Dashboard
- Login
- Settings
- Theming stuff?
- Vuex => migrate to Pinia?
- ....

This issue will be updated as we continue the process. Completed items (or subitems) will be added under the correct section with a checkbox to show that they're completed.

**Comment by LeaderbotX400** [comment]
> I think it may be a good idea to create a branch to merge everything into it before merging the whole to master. Not sure if Vue 2 and 3 can cohabitate, merging to master will trigger build on nightly and block some users

Vue three has some excellent backwards comparability and most of the same features of vue 2 should still be present. There is also the `@vue/compat` which brings back anything that vue 3 dropped

**Comment by WDaan** [comment]
That's a good idea, but I vaguely remember Vue having a package to support both at the same time. Not sure how well that works though.

**Comment by LeaderbotX400** [comment]
> That's a good idea, but I vaguely remember Vue having a package to support both at the same time. Not sure how well that works though.

that would either be `vue-demi` or `@vue/compat`
