### ISSUE TITLE
Arrow direction wrong / unintuitive in sorting?

### ISSUE THREAD

**Issue by tedzhu** [WDaan/VueTorrent#739]
If you want to sort the items with big numbers on top and small ones on the bottom, in qBittorrent (and I believe other places) it's a downward arrow, and vice versa. However, in VueTorrent, it's the other way around.

**Comment by Larsluph** [comment]
The arrow only represents if the order is reversed or not, the unintuitive direction can't be changed as qBittorrent sorts some in ascending order and some in descending
