### ISSUE TITLE
Can't show torrent download and upload speed

### ISSUE THREAD

**Issue by seeson** [WDaan/VueTorrent#743]
Can't show single file's download&upload speed, only global option.
![image](https://user-images.githubusercontent.com/12587456/228185876-cd327d50-c6b0-4a0f-aada-0bc44341816e.png)
![image](https://user-images.githubusercontent.com/12587456/228185940-968e8b1e-bd23-435e-ab0a-42b1df98f201.png)

**Comment by Larsluph** [comment]
Duplicate of #738
