### ISSUE TITLE
[bug] while filter actived, sorting will behave strange

### ISSUE THREAD

**Issue by flashlab** [WDaan/VueTorrent#746]
I found two problem while using the search filter function:

1. Non ASCII torrent title can't be sort properly, such as the first few character is Chinese, the list will be disordered.
2. if the search filter actived(the input box is writtened), the sort action is not working

**Comment by Larsluph** [comment]
1. Except for `globalSpeed` and `globalVolume`, it's qbittorrent that sorts the torrents.
2. If a filter is enabled, we use the lib `quick-score` to filter them and it sorts the array by relevance.

**Comment by flashlab** [comment]
@Larsluph Thanks for your reply, as the second issue, does it mean we can't sort the filtered list?

**Comment by Larsluph** [comment]
It may work with the 2 global properties but yeah that's it
