### ISSUE TITLE
[Feature Request] Support for Sorting by / Viewing / Modifying Priority

### ISSUE THREAD

**Issue by HeySteets** [WDaan/VueTorrent#75]
Hi there! I was checking out some alternative WebUI themes for qBittorrent, and I found VueTorrent. It's gorgeous and easily the most beautiful of the WebUIs out there, but it is lacking in one notable area - priority support. While you can sort by priority in the menu, you are unable to alter or view the number of a torrent.

Are there any plans to add modifying / viewing the priority of individual torrents to VueTorrent?

Thank you!

**Comment by WDaan** [comment]
Thanks I'm glad you like it!

I'll add it to the list! It would be a nice feature to have indeed.

For the next few weeks I'm a little occupied, but I'll try to add it as soon as I can 😄
