### ISSUE TITLE
8500+ torrents and webui is very slow.

### ISSUE THREAD

**Issue by beyondmeat** [WDaan/VueTorrent#753]
I have 8500+ torrents and vuetorrent is very slow even when only 200 are showing using filters.
' Selecting a few torrents and doing something like delete takes about 5m for the confirmation dialog to show up, then takes a long time to delete them. The native webui is faster than this.

using linuxserver/qbittorrent:latest (pulled and updated nightly) w/ vuetorrent 1.5.3.

**Comment by WDaan** [comment]
Why was this closed?

It's possible this UI is slower than the original, there's a lot of added visual fluff that isn't that good on performance.

Perhaps there are a few quick wins out there we could do.

**Comment by beyondmeat** [comment]
It's due to the usage of sync/maindata - seems to be a workaround in comments. https://github.com/qbittorrent/qBittorrent/issues/10999

**Comment by Larsluph** [comment]
The funny part is that I don't think these calls are necessary 😅. To get the list of torrents we already call /torrents/info which we use to filter / sort the torrents list

**Comment by Larsluph** [comment]
I can confirm that

https://github.com/WDaan/VueTorrent/blob/237de79e3392ac12f2f84e21c30a89c036413118/src/store/mutations.ts#L55-L78

**Comment by Larsluph** [comment]
As the issue states, the /sync/maindata route is causing performance issues with long response time when there's a lot of torrents

**Comment by Larsluph** [comment]
The obly problem is that some info is only accessible using that route (for example the free space on disk)

**Comment by Larsluph** [comment]
And to get back to the error thrown above, it has nothing to do with that, it's linked to a recent migration that broke some components in the torrent DesktopCard, you have to reset your settigns to fix it unfortunately.

**Comment by Larsluph** [comment]
This has been fixed with 30beddaab425348d020e762bab49b3399f86b9be I think. @WDaan

**Comment by popcrop2** [comment]
Not at 8500+ but close to 1k and noticed significant lag around 200. Running linuxserver/qbittorrent:libtorrentv1 in docker container. 

qbittorrent: release-5.0.3_v1.2.20-ls63
VueTorrent: 2.20.0

Let me know any logs that can be posted to help

**Comment by Larsluph** [comment]
Infinite scroll is known to cause performance issues with large amount of torrents, I already tried improving this, but property personalisation makes it very hard to be consistent, at least for list and grid layouts.

**Comment by popcrop2** [comment]
Yep! Lowering infinite scroll to 100 helped instantly. Thank you :)
