### ISSUE TITLE
[Feature] Plugin lyrics extension

### ISSUE THREAD

**Issue by lyaschuchenko** [WDaan/VueTorrent#754]
I think what do not have describe that. All users want and wait this function

**Comment by LeaderbotX400** [comment]
what?

**Comment by lyaschuchenko** [comment]
> It's not super clear for me either. Can you perhaps add a link to what you're refering too?

I mean what it maybe similar as in YT Music

**Comment by LeaderbotX400** [comment]
> I mean what it maybe similar as in YT Music, or a separate plugin

So, this is a qbittorrent issue and not a vuetorrent issue?

**Comment by lyaschuchenko** [comment]
O no. I send issue to wrong topics
