### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by TimucinPusat** [WDaan/VueTorrent#755]
till this everything OK:) But I don't know how to do this
Point your alternate WebUI location to the vuetorrent folder in qBittorrent settings

how to point what does pointing mean? Could someone tell this as if telling a dummy.

**Comment by WDaan** [comment]
In QBittorrent WebUI settings, you can fill in a path. This path should be the path to the Vuetorrent folder.

**Comment by TimucinPusat** [comment]
Well I found the place on qbittorrent and filled it. Then what? What to do and what will happen?

**Comment by Larsluph** [comment]
At the bottom, click on "Save". It should reload the page with VueTorrent!

**Comment by TimucinPusat** [comment]
I did but nothing happened. is there any video explanation for this? 

https://imgur.com/a/LMtvOZf

**Comment by TimucinPusat** [comment]
OK man I encountered this video and thanks to the publisher I got it and I achieved. Thank you.  https://www.youtube.com/watch?v=WW5MCQRZwHU

**Comment by TimucinPusat** [comment]
but I haven't learned how to see this page from my phone while using mobile network:(

**Comment by Larsluph** [comment]
Basically you have 2 way of doing so, setup a VPN server on your computer/server hosting qbittorrent or opening your port through your router configuration

**Comment by TimucinPusat** [comment]
thanks you. this is difficult for me. instead I installed team viewer. so I control not only qbit but also whole pc.

**Comment by Larsluph** [comment]
That also works 😄
