### ISSUE TITLE
Comment field support

### ISSUE THREAD

**Issue by netvl** [WDaan/VueTorrent#76]
In the default web UI, in the torrent info box, there is the "Comment" field which is often a URL to the tracker (this is determined by the tracker, but where it is implemented, it is very convenient):
![image](https://user-images.githubusercontent.com/280456/101345306-b375cd80-383b-11eb-82e0-2e2e246eb22f.png)

Sadly, this field is not visible in VueTorrent. Is it possible to add it to the client? Thank you very much!

**Comment by netvl** [comment]
Thank you!

**Comment by WDaan** [comment]
Don't thank me yet 😅 the torrents I usually test with didn't have any comments or anything.
The comment & tracker field will now be shown if there is one... but I haven't actually seen it working yet

**Comment by Aleksman4o** [comment]
Comment is still not shown in INFO tab, althouth it is present in standart interface
