### ISSUE TITLE
RSS downloader

### ISSUE THREAD

**Issue by MrThanlon** [WDaan/VueTorrent#768]

**Comment by WDaan** [comment]
Can we get a little more details please?
Is there an issue with what's currently implemented? Would you like to see other features?
Without a proper description, I'll just close this one.

**Comment by MrThanlon** [comment]
> Can we get a little more details please?
> Is there an issue with what's currently implemented? Would you like to see other features?
> Without a proper description, I'll just close this one.

<img width="849" alt="image" src="https://user-images.githubusercontent.com/22488270/232224367-e15007ab-f1d3-4a51-9377-2ca5e207b85c.png">

**Comment by MrThanlon** [comment]
vuetorrent does not implement rss downloader

**Comment by Larsluph** [comment]
Checkout the rules tab of the RSS settings page, it should correspond
