### ISSUE TITLE
[Feature Request] - Add "uploaded" and "session upload" & speed in titlebar 

### ISSUE THREAD

**Issue by Larryadd** [WDaan/VueTorrent#77]
Hi WDaan,

First of all, thx for that great interface for qbittorrent, best looking one I've seen.
I miss 2 features from the original interface.
Is it possible to add the the equivalent of the 2 columns "uploaded" and "session upload" in the vuetorrent dashboard options ?

Also, the option speed in titlebar is a good feature to have if it's possible.

Thanks for all your work.

**Comment by WDaan** [comment]
Thanks for the kind words! 

What do you mean with 'speed in the titlebar'? Can you show me an example?

I will look into it as soon as I can!

**Comment by Larryadd** [comment]
Hi,

I mean that : 
![image](https://user-images.githubusercontent.com/7392502/101833699-a9a0e280-3b39-11eb-989c-7f1cbc0f37e4.png)

I don't know how to explain sorry.

**Comment by WDaan** [comment]
No more explanation needed!
I will look into it! But be patient 😅
