### ISSUE TITLE
[Feature request] Default sort mode

### ISSUE THREAD

**Issue by Riven-Spell** [WDaan/VueTorrent#773]
When managing my torrents, I prefer to view things in most recently added sort mode, and change from there when I'm interested in other metrics.

I'd like an option in settings to default to a certain sort mode upon login.

**Comment by Larsluph** [comment]
I'm not sure to understand the problem here, you can already sort by most recently added torrents 🤔

**Comment by Riven-Spell** [comment]
> Plus this setting is persistent so the sort options should be kept between sessions
Odd; has been a little unreliable for me, so nvm
