### ISSUE TITLE
Cannot see any active torrents on safari mobile after version 1.5

### ISSUE THREAD

**Issue by donnarth** [WDaan/VueTorrent#774]
I only see a number of torrents. I can select them but no torrent info (name, seeding info, etc) shows up. I tried all of the current versions but rolled back to 1.5 as I use mobile often. Any recommendations?

**Comment by Larsluph** [comment]
Try to reset the settings / local storage, it's a known bug

**Comment by donnarth** [comment]
I had tried that and it did not work. I deleted the bookmark and recreated it and that worked.
Thanks for the help!
