### ISSUE TITLE
WebUI Progress Bar CSS

### ISSUE THREAD

**Issue by kooliokevin** [WDaan/VueTorrent#785]
I'm trying to customize the CSS and am unable to locate where I can update the progress bar colors.

The is my goal. I can achieve it by editing the screen's backend "v-progress-linear__background" and "v-progress-linear__determinate" fields to "torrent-metadata"
![image](https://user-images.githubusercontent.com/36769191/234966531-cc06fee7-c9d4-48d0-a96a-7d084d02f99c.png)

This is the default, where it uses the "torrent-stalled" variable here.
![image](https://user-images.githubusercontent.com/36769191/234966625-85034bf2-e99a-4e1d-a8df-5d8caaafc696.png)

Where the heck can I find the CSS file to update this? I've dug everywhere thru the VueTorrent CSS files and have been able to get the other aspects of the UI to my liking, except for this progress bar.

**Comment by Larsluph** [comment]
All the colors we use for this are stored in the `src/plugins/vuetify.ts` file. Good luck manipulating these!

**Comment by kooliokevin** [comment]
Fantastic, thank you! Hmm I'm somewhat new to Github, I have no idea what to do with this .TS file haha

**Comment by Larsluph** [comment]
Well I don't know what to say, it's just a Typescript file, you can find in the repo 😅

**Comment by kooliokevin** [comment]
I've just been working on what's in here: 
![image](https://user-images.githubusercontent.com/36769191/234971937-2d8670bd-1743-4a5d-a140-bd15ff3f4e9c.png)

I don't see any TS files in here so I'll have to learn how to implement it

**Comment by Larsluph** [comment]
Oh yeah, you're in one of the release branch, you'll have to checkout the master to see the source and not the obfuscated production version.

**Comment by WDaan** [comment]
Yeah the published version won't tell you much.

You'll have to make the changes on the main branch and than rebuild it. 

You should be able to follow the readme.

**Comment by kooliokevin** [comment]
Appreciate the tips. I've cloned yours and adjusted the colors, but am having trouble now with exporting the final package of the WebUI files needed.. I'll keep digging.

**Comment by WDaan** [comment]
You need to run npm install && nom run build. The artifacts you seek will be in the Vuetorrent folder.

**Comment by kooliokevin** [comment]
Thank you WDaan, I've been able to get it now and my color layout is where I want it. Fantastic work on this, by the way.
