### ISSUE TITLE
Blue block on top of ratio in Mobile view

### ISSUE THREAD

**Issue by SinTan1729** [WDaan/VueTorrent#786]
![Screenshot_20230427_195811_Vivaldi Browser](https://user-images.githubusercontent.com/35728385/235029590-c06f751d-d3e0-4dde-94f3-2e10587cffb9.jpg)
You can see on the screenshot above that there's a blue block on top of the ratio in Mobile view. It's there in light mode too. Does not get fixed on a settings reset.

It's not there on the desktop, though.

**Comment by WDaan** [comment]
Fixed in #782
