### ISSUE TITLE
[feature request] More robust torrent search debounce

### ISSUE THREAD

**Issue by flashlab** [WDaan/VueTorrent#787]
Currently the search field got 300ms debounce time. In some situation, the period is not quite enough, especially when using mobile phone.

https://github.com/WDaan/VueTorrent/blob/6745c91a3ca20476bdc97127d506d182bb899560/src/views/Dashboard.vue#L269-L276

Is it possible to make a switch to enable slower debounce time? It will be useful when large amount of torrents meet slow internet speed. Thanks.

**Comment by WDaan** [comment]
Just increasing the denounce time might not be the solution you need. 

Maybe we just need to rework the search altogether as mentioned in #540?
