### ISSUE TITLE
Tags filter doesn't work

### ISSUE THREAD

**Issue by oilervoss** [WDaan/VueTorrent#788]
Filters "Status" and "Categories" are working but "Tags" aren't in any way.

I'm using `qbittorrent-nox` because it's a headless server. Vue have been updated using `git pull`

- Ubuntu 20.04.6 LTS
- Linux rapidseedbox.com 5.4.0 # 1 SMP Tue Jan 25 12:49:12 MSK 2022 x86_64 x86_64 x86_64 GNU/Linux
- Vue 1.5.6
- qBittorrent 4.3.9

```
apt show qbittorrent-nox

Package: qbittorrent-nox
Version: 1:4.3.9.99~202110311443-7435-01519b5e7~ubuntu20.04.1
Priority: optional
Section: net
Source: qbittorrent
Maintainer: sledgehammer999 <hammered999@gmail.com>
Installed-Size: 7646 kB
Depends: libc6 (>= 2.29), libgcc-s1 (>= 3.0), libqt5core5a (>= 5.12.2), libqt5network5 (>= 5.9.0), libqt5xml5 (>= 5.9.0), libssl1.1 (>= 1.1.0), libstdc++6 (>= 5.2), libtorrent-rasterbar10 (>= 1.2.14+git20211025.eb4bbfd49c), zlib1g (>= 1:1.2.0)
Suggests: qbittorrent-dbg
Download-Size: 5882 kB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/qbittorrent-team/qbittorrent-stable/ubuntu focal/main amd64 Packages
```

**Comment by Larsluph** [comment]
It's working for me, can you send the "info" request to see if the tags is sent to the qbit API ?

**Comment by oilervoss** [comment]
I could find it.
All filters "ALL" (normal behavior as expected):
`http://localhost:8899/api/v2/torrents/info?sort=added_on&reverse=false`
Category as "Movies" (normal behavior as expected):
`http://localhost:8899/api/v2/torrents/info?sort=added_on&reverse=false&category=Movies`
Tag as "Games" (null behavior while category and state keep working as expected):
`http://localhost:8899/api/v2/torrents/info?sort=added_on&reverse=false&tag=Games`

I'm running qbittorrent in a headless remote server. I'm using a SSH tunnel to access it hence the `localhost`

**Comment by Larsluph** [comment]
Just dug into that and the "tag" filter we use has been added in the 4.4.0, so try to update your qBittorrent to make it work!

Source:
https://github.com/qbittorrent/qBittorrent/commit/9bfc74a1bcf1420ea0393ffbafe5057cae4f37e4
