### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by falk-h** [WDaan/VueTorrent#79]
Hi! I made an [AUR package](https://aur.archlinux.org/packages/qbittorrent-vuetorrent-bin/) for Arch users. Maybe the package could be mentioned in the README?

**Comment by WDaan** [comment]
Sure! How would you propose?

FYI: this project no longer uses ExpressJs...so feel free to remove it from the title

**Comment by WDaan** [comment]
Closed due to inactivity
