### ISSUE TITLE
[Feature-request]

### ISSUE THREAD

**Issue by muellerjoel** [WDaan/VueTorrent#792]
Hi!

First great work! 
It would be nice to download or play media files of the torrent in the browser...

Cheers
Joël

**Comment by Larsluph** [comment]
Hi! Thanks a lot for using this WebUI, unfortunately what you're asking isn't possible or would require additional setup on top of qbittorrent (like setting up a ftp / sftp server) to be able to read the content of the downloaded torrents and this kind of features is out of scope for a WebUI.

**Comment by WDaan** [comment]
Thanks for answering this @Larsluph 

Lots of people seem to forget that this is just a WebUI, we have no access to your actual hard drive or anything else. We can only show what QBit is able to expose using its API.
