### ISSUE TITLE
Broken UI

### ISSUE THREAD

**Issue by lyaschuchenko** [WDaan/VueTorrent#806]
See this bug
![image](https://github.com/WDaan/VueTorrent/assets/15934644/4b2792e0-948a-434d-9ffb-c5e758115c48)
word "Ratio" in Ukrainian 

this
![image](https://github.com/WDaan/VueTorrent/assets/15934644/9d626c38-f2c5-4a7e-bd84-9c1fbf77027d)
please fix capitalisation

**Comment by lyaschuchenko** [comment]
bug still here

**Comment by Larsluph** [comment]
Can you please describe what's the problem here ?

**Comment by lyaschuchenko** [comment]
> Can you please describe what's the problem here ?

Same as on screenshot. Nothing change

**Comment by Larsluph** [comment]
Ok but I don't speak Ukrainian so I don't know what seems to be the issue here if it hasn't been already fixed 🤔

**Comment by lyaschuchenko** [comment]
> Ok but I don't speak Ukrainian so I don't know what seems to be the issue here if it hasn't been already fixed 🤔

In Ukrainian letter sign capital:
A) First word in sentence
2) Proper name (i.e. name, name of city or street and simultaneous)

**Comment by lyaschuchenko** [comment]
And as I show on first screenshot, word Ratio (Співвідношення)  doesn't fit in bar, maybe have sense increase width of bar?

**Comment by Larsluph** [comment]
Capitalisation should be fixed now but for the overflow I tried using v-col as everywhere else but that didn't change much. I tried resizing the columns but the unit overflows and moves to a newline so not good as well. @WDaan if you have an idea on how to design it, I'll take your suggestions 😄

**Comment by lyaschuchenko** [comment]
I think , you need try move to right numeric column (where written 6.04 on screenshot)

**Comment by lyaschuchenko** [comment]
Ok. Previous bug was fixed. But have new one
![Screenshot_2023-06-01-06-37-17-001_com android chrome-edit](https://github.com/WDaan/VueTorrent/assets/15934644/dcf9903e-ba2e-4900-ac75-ca90339da246)
