### ISSUE TITLE
Some text invisible in some pages of “Settings”

### ISSUE THREAD

**Issue by antenna2008** [WDaan/VueTorrent#810]
![IMG_6653](https://github.com/WDaan/VueTorrent/assets/22744518/bb72630d-45e9-4b7f-b72d-ec99283ed44d)

separation line -----------------------------------------------------------------------------------------------------------------------

![IMG_6655](https://github.com/WDaan/VueTorrent/assets/22744518/1797b012-690e-4bca-b802-3d9ea16ab500)

separation line -----------------------------------------------------------------------------------------------------------------------

![IMG_6656](https://github.com/WDaan/VueTorrent/assets/22744518/2571fa83-1a94-4198-b46e-c32ea8128fea)

separation line -----------------------------------------------------------------------------------------------------------------------

![IMG_6657](https://github.com/WDaan/VueTorrent/assets/22744518/90bed651-d7d9-41b3-a9f9-15715f185c6d)

separation line -----------------------------------------------------------------------------------------------------------------------

![IMG_6658](https://github.com/WDaan/VueTorrent/assets/22744518/9bf728b7-f51f-41b1-ae16-e60651562c82)

separation line -----------------------------------------------------------------------------------------------------------------------

![IMG_6659](https://github.com/WDaan/VueTorrent/assets/22744518/53344537-0920-4877-80fa-33c12b295aca)

**Comment by Larsluph** [comment]
Can you check with the inspector (F12) is the text missing or colored white?

**Comment by antenna2008** [comment]
colored white


When mouse select some white colored item, the text display black.

![Screenshot 2023-05-11 150137](https://github.com/WDaan/VueTorrent/assets/22744518/20d72f70-9ce0-4d8a-967d-3cf58a2919f8)

**Comment by Larsluph** [comment]
Ok that's a weird behaviour, I might take a look at that later 😉

**Comment by Larsluph** [comment]
Found the culprit @WDaan 😜
![image](https://github.com/WDaan/VueTorrent/assets/22910497/2fdd8fbf-9a98-449a-b2f5-d48036490d41)
