### ISSUE TITLE
Cant toggle progress bar mobile

### ISSUE THREAD

**Issue by nickelslol** [WDaan/VueTorrent#821]
Hey

How come when i deselect progress on the mobile card tab the progress bar is still visible?

**Comment by Larsluph** [comment]
The progress bar can't be disabled, that's normal.
However, I noticed that mobile card settings don't apply correctly. I'll check tomorrow to see how is it possible.

**Comment by nickelslol** [comment]
Thank you for the reply. I have set it to not display on non-busy torrents as the information is not needed. It looks great on desktop, but mobile devices would benefit from removing redundant information on a small screen

**Comment by Larsluph** [comment]
Ok I'm just dumb 😅 mobile card does apply correctly, I looked for changes in a done card while changing busy settings 🤦 BUT i took advantage of this to add the possibility to remove the progress bar 😄.
And @WDaan I finally added something to prevent issues about the settings reset thing.
