### ISSUE TITLE
Settings message after update. 

### ISSUE THREAD

**Issue by THEVAN3D** [WDaan/VueTorrent#824]
I'm using the qBittorrent docker container with this UI on UNRAID and after the last update I am getting this message: "Old version of settings detected, reset them for the best experience!" 

What do I do?

![image](https://github.com/WDaan/VueTorrent/assets/7791316/02d6c99e-b0f2-4b00-9974-b34c328fc6fd)

**Comment by Larsluph** [comment]
Reset your settings as said in the toast, there's a button in the VueTorrent settings page

**Comment by THEVAN3D** [comment]
> Reset your settings as said in the toast, there's a button in the VueTorrent settings page

that fixed it. but also resetted the UI elements back to default. had to rearrange elements manually again. hope it wont happen again. thanks for the solution.

**Comment by Larsluph** [comment]
Yep, unfortunately with the way we store information we can't migrate stuff so until we switch to Vue3 that's the only way to make it work

**Comment by CJRomix** [comment]
> > Reset your settings as said in the toast, there's a button in the VueTorrent settings page
> 
> that fixed it. but also resetted the UI elements back to default. had to rearrange elements manually again. hope it wont happen again. thanks for the solution.

I still haven't found the magic "Reset button"... And if I do find it and reset the settings, I'll lose all my "Categories", "Tags" settings and all the loaded paths!?

**Comment by Larsluph** [comment]
When we say "reset settings", we are only talking about VueTorrent's WebUI settings.
The only settings you'll lose are all those under the "VueTorrent" tab.

If you want to keep them, you can set them after reset or merge JSON configs from the export / import settings.

**Comment by Larsluph** [comment]
> I still haven't found the magic "Reset button"...
Look at the bottom of the VueTorrent settings page, it's the only red button.

**Comment by CJRomix** [comment]
> > I still haven't found the magic "Reset button"...
> 
> Look at the bottom of the VueTorrent settings page, it's the only red button.

ThanX! Im dumb simply scroll down :))
