### ISSUE TITLE
[Feature request] RSS Downloader rules creator in real-time

### ISSUE THREAD

**Issue by valujin** [WDaan/VueTorrent#833]
It would be nice to be able to see in real-time matching entities for selected feeds when creating/editing the rule for RSS Downloader. It works the same way on desktop GUI. This feature is very convenient as it allows to check if your rule is correct (especially while using regex).

**Comment by Larsluph** [comment]
This feature already exists but is in fact separated, I think it may be possible to merge both of them together for better UX.
