### ISSUE TITLE
ver 1.5.8 import settings doesn't work 

### ISSUE THREAD

**Issue by billkewl** [WDaan/VueTorrent#837]
Just upgraded vuetorrent to 1.5.8 latest version and reset all settings according to toast message.

When I tried to export the new settings to another client, I got invalid json error.

Here's the console error log
`instancepath: "/webuiSettings/busyMobileCardProperties"keyword: "maxItems"message: "must NOT have more than 13 items"`

It seems that the new mobile card property wasn't taken into consideration of max amount of mobile properties?

**Comment by Larsluph** [comment]
Already fixed with #828
It will be in the coming update (1.5.9)

**Comment by WDaan** [comment]
Want me to cut a release early @Larsluph ?

**Comment by Larsluph** [comment]
You can yeah
