### ISSUE TITLE
Right click context menu not working in Edge

### ISSUE THREAD

**Issue by mehapps** [WDaan/VueTorrent#842]
Using edge for mac, on Safari when right-clicking the context menu shows up (saying delete, show info etc) but on Edge it simply shows the normal right click menu. Has anyone seen this or know a fix? Thanks!

**Comment by mehapps** [comment]
Interesting... also not working on Chrome for Mac

**Comment by Larsluph** [comment]
Oh so it might be related to mac instead of edge 🤔

**Comment by WDaan** [comment]
I don't know what's different on your end but I can confirm that the rightclick menu is working in Edge, Safari and Chrome on my MacBook.

**Comment by Larsluph** [comment]
@mehapps Do you have any kind of warning / errors in your console (Press F12 > Console) when you try to right click on a torrent card ?

**Comment by mehapps** [comment]
> @mehapps Do you have any kind of warning / errors in your console (Press F12 > Console) when you try to right click on a torrent card ?

I get this error
Uncaught TypeError: event.cancelBubble is not a function
    at HTMLDocument.bringBackDefault (new_rightclick.js:87:31)
bringBackDefault @ new_rightclick.js:87

**Comment by Larsluph** [comment]
Hum, that's weird. Do you have any extensions / plugins installed in your browser that may interfere with the right click event ?

**Comment by mehapps** [comment]
I feel so dumb. I had an "Allow Right-Click" extension. Disabling it fixed the issue. Thanks so much! (Closing since it's fixed)
