### ISSUE TITLE
Unacceptable file type, only regular file is allowed.

### ISSUE THREAD

**Issue by FatSandwich** [WDaan/VueTorrent#85]
I'm on a MacBook

**Comment by WDaan** [comment]
Please check out this issue... [#10]

You should download the release.zip & point your alternate webui location to the 'vuetorrent' folder inside the extracted release.zip

**Comment by dobryc** [comment]
I have exact same issue, checked out #10, but no luck. I have QB installed on my Debian server, working webUI on subdomain torrent.mysite.com, which is driven by nginx and proxy_pass to qbit webUI port (8112). Sometimes VueTorrent webUI works (when I restart qbit and go to my torrent.mysite.com, but only in that instance of browser), If I use another browser, or another device, I get same as title error.

**Comment by WDaan** [comment]
Have you checked out [#90], is your QBittorent up to date?
Otherwise this is a whole other kind of issue.

Could it be related to your proxy? 
Does it work when going straight to http://ip:port?

**Comment by dobryc** [comment]
@WDaan Thanks for pointing! 
Trying to build fresh Qbit now. Let you know if this helps.

**Comment by dobryc** [comment]
@WDaan Yes, building a fresh QBittorrent fixed problem

**Comment by WDaan** [comment]
Great! Glad to hear 😀
