### ISSUE TITLE
[Feature Request] Option to view speeds as Mbps instead of MB/s

### ISSUE THREAD

**Issue by Mavyre** [WDaan/VueTorrent#857]
It could be great to have an option in the settings to switch the units of download and upload speeds. For instance, nzb360 on mobile, which connects to qBittorrent, has this option available.

**Comment by Mavyre** [comment]
Yup that's what I mean!

**Comment by Larsluph** [comment]
Should we do it only for speed or for every data unit of the UI ?

**Comment by Mavyre** [comment]
Only for speeds imo. I didn't see any other software show sizes as bits
instead of Bytes. However, speeds are often switchable, as ISP shows bits
per second.
