### ISSUE TITLE
Search function does not return any more than 100 items

### ISSUE THREAD

**Issue by lukemattle** [WDaan/VueTorrent#859]
When using the 'Search torrents' function in VueTorrent it will never return more than 100 items but in qBittorent it returns 1000+

**Comment by Larsluph** [comment]
That may be a limitation of the data table component 🤔. We'll need to check that, thanks for the feedback!

**Comment by itschasa** [comment]
any updates on this issue being resolved? am having the same issue

**Comment by itschasa** [comment]
pls fix

**Comment by itschasa** [comment]
Is there any ETA to this being fixed? This is the only reason I'm not using VueTorrent.

**Comment by Larsluph** [comment]
I just check and it think I know what's causing the problem.
I've ran a search intent and we limit the number of results returned in one page, but when search is completed and the last chunk contains more than 100 items, it just stops instead of getting all the results.
I can see to fix that today.

**Comment by itschasa** [comment]
Sounds great, thanks for the quick reply!

**Comment by lukemattle** [comment]
Sounds good, look forward to the fix!
