### ISSUE TITLE
can't select words on Vuetorrent webui

### ISSUE THREAD

**Issue by Yumega** [WDaan/VueTorrent#866]
can't select any words on Vuetorrent to copy, how to enable to copy words on it

**Comment by Larsluph** [comment]
Can you be more precise?
Do you mean that you want to select text coming from the interface like labels and hints?

**Comment by Yumega** [comment]
> Can you be more precise? Do you mean that you want to select text coming from the interface like labels and hints?

Yes, I can't selet the text on the interface

**Comment by Larsluph** [comment]
> Yes, I can't selet the text on the interface

AFAIK it's not possible to select text outside of input fields, why would you need that? Is it really necessary?

**Comment by WDaan** [comment]
Also there is the ability to copy the hash etc from the right-click menu

**Comment by Larsluph** [comment]
In that case it may be possible to import/export qBit settings on top of the existing import/export feature for VueTorrent settings

**Comment by Larsluph** [comment]
@WDaan maybe close it as this is intended ?

**Comment by goremykin** [comment]
The same with save path. Are there any technical difficulties due to which this restriction was added?
