### ISSUE TITLE
Default Date Format

### ISSUE THREAD

**Issue by Marcio2536** [WDaan/VueTorrent#872]
The default date format for VueTorrent is DD/MM/YYYY. However, the international standard (ISO 8601) of date formating is YYYY/MM/DD. Please change the default one in VueTorrent to YYYY/MM/DD format. Thanks.

**Comment by WDaan** [comment]
You should be able to set your default in settings 😄 

Anyone else feel we should make this change? please upvote

**Comment by Marcio2536** [comment]
Yes, but the fact that this date format still isn't the default format makes the whole thing strange. The DD/MM/YYYY and MM/DD/YYYY often make confusions.
