### ISSUE TITLE
Autostarting torrents doesnt work

### ISSUE THREAD

**Issue by ticklemyIP** [WDaan/VueTorrent#890]
I'm on the latest qBittorrent version and a recent Vue version (will check later) and when auto-start is disabled by default and I add multiple torrents (with category) then enable autostart, the torrents do not autostart.

**Comment by Larsluph** [comment]
> auto-start is disabled by default

What do you mean by auto-start? Can you provide more details?

**Comment by ticklemyIP** [comment]
There is a setting "Do not start the download automatically". Users could override this by clicking "Start torrent" in the new torrent dialogue. This doesn't work.
