### ISSUE TITLE
Add default sort type toggle

### ISSUE THREAD

**Issue by ticklemyIP** [WDaan/VueTorrent#892]
Allow to set a default sort type. Because Vuetorrent UI is not array based (as the default WebUI) but a list, the column sort doesnt work. But a default toggle would. It could be built into the current sort drop down as a form of a checkmark next to every entry. Selecting this checkmark will make that sort type default. Or alternatively a regular settings toggle would work.

**Comment by Larsluph** [comment]
The selected sort type is saved inside the local storage of your browser. So this settings should be saved between sessions, except if you use a browser that cleans its data between restart.
