### ISSUE TITLE
Add compact view

### ISSUE THREAD

**Issue by ticklemyIP** [WDaan/VueTorrent#896]
The torrent entries are really bloated currently in my opinion and turing off certain elements doesnt always work because (as I have observed) they do not wrap to the next row but stay in their designated (2nd) row. And most of these elements are crucial, like the added on date. (I don't think this can even be turned off.)

The solution would be imo. a compact view mode where unnecessary elements are removed ("Torrent name" "Progress" text etc.) or moved in one row to use empty space. Some of these texts could be turned into icons (applies to current view as well) to save more space. Progress bar could be used as the whole torrent entry. The possibilities are endless and I wouldn't mind designing a basic UI sketch (graphically) for both modes if theres a demand, feel free to ask.

**Comment by Larsluph** [comment]
Duplicate of #157

But if you have designs in mind, we'll be glad to hear your suggestions!

**Comment by ticklemyIP** [comment]
Cool, I'll put something together when I'll have the time. :)
