### ISSUE TITLE
macOS Safari favicon issue

### ISSUE THREAD

**Issue by billkewl** [WDaan/VueTorrent#897]
Hi.

I host a file sharing web and qBittorrent on different ports of a same domain.
In this case, Safari of macOS will display both page's favicons in black.

Looking into the html file, I found 
`<link rel="mask-icon" href="./favicon.ico" color="#000" />`
and somehow this will mess up Safari favicon display.
after commenting this line, favicon of both sites are correctly displayed.

c.f.
https://www.leereamsnyder.com/blog/favicons-in-2021

Could you fix this for macOS Safari users?

Thanks.

**Comment by Larsluph** [comment]
Used another version for 2023 and thanks for the feedback! 😄
