### ISSUE TITLE
Problem with older versions of qBittorrent?

### ISSUE THREAD

**Issue by Flashbin** [WDaan/VueTorrent#90]
I was searching for alternate WebUI's for qBittorrent and found this, so I installed it. At first it worked, with a few minor problems, but it worked. Then I tried to access it with my phone and got "Unacceptable file type, only regular file is allowed.". Next time I refreshed the page on my PC I got the error there too. Since then I wasn't able to get it to work (yes I've seen #10).

So my assumption is that the newest version of VueTorrent doesn't like older version of qBittorrent (I'm on Debian 10, qBittorrent 4.1.5)?

**Comment by WDaan** [comment]
I tried it with qbit version 4 and 4.1 & I couldn't get it to work.
Lowest supported version is 4.2

I would suggest you upgrade, if possible
