### ISSUE TITLE
Search torrent regression

### ISSUE THREAD

**Issue by Anteus** [WDaan/VueTorrent#902]
* Can't trigger Search with enter button.

* The search filter doesn't filter on each term separately but only as full string 

Filter: term1 term2
Only exact match on "term1 term2"
Doesn't match: term1 random term2

**Comment by Larsluph** [comment]
yep the search feature isn't great and the api is kinda weird to work with. I agree that it can be improved A LOT.

**Comment by Anteus** [comment]
Yeah it's kinda weird. I think I had it working before with this. I'll see if I can make it work with the new version.

https://github.com/WDaan/VueTorrent/pull/478/commits/5d849ee2cf8e67bc5a43639b5ca0945546bf4311
