### ISSUE TITLE
Javascript error on delete multiple files

### ISSUE THREAD

**Issue by ZiperRom1** [WDaan/VueTorrent#91]
Hello, I cannot delete multiple files (without disk file removal).

A javascript error occured in console on the `delete`button click.

**Web browser** *Firefox 84.0.1 (64 bits)*
**OS** *Windows 10 familial 19041.685*
**VueTorrent** *0.4.7*

![VueTorrent_bug](https://user-images.githubusercontent.com/10369248/103486260-d2488f00-4dfc-11eb-99e7-2017cb8b8e37.PNG)

Seems like the `t is undefined` refers to something in the above functions

**qbit.js**

```js
  deleteTorrents(hashes, deleteFiles) {
    if (!hashes.length) return
    
    return this.torrentAction('delete', hashes, { deleteFiles })
  }
```

**ConfirmDeleteModal.vue**

```js
deleteWithoutFiles() {
      qbit.deleteTorrents(this.selected_torrents, false)
      this.close()
    }
```

**Comment by WDaan** [comment]
Thanks for the detailed explanation!

Exams start soon, so I'll look into it when I find the time! 🙂
