### ISSUE TITLE
Long-press context menu broken on PWA

### ISSUE THREAD

**Issue by oyrei** [WDaan/VueTorrent#911]
I am an iOS user, and after logging into the WebUI using a browser on iOS, there is a feature to add the webpage to the home screen, making it similar to a regular app. However, I am facing an issue where, when I need to perform actions on torrent tasks, I need to long-press to bring up a menu. In the case of the WebUI added to the home screen as I mentioned earlier, the long-press menu disappears immediately, preventing proper operation. I hope the author can look into this issue. Thank you very much.

**Comment by oyrei** [comment]
It means installing as a PWA application.

**Comment by WDaan** [comment]
Confusing title. So the issue you're having is with the context menu? That it behaves differently on the PWA?

I think there's an issue for this. As a workaround in the meantime, you can use 2-finger tap to achieve the same result.

**Comment by guslma** [comment]
I have the same problem

**Comment by oyrei** [comment]
Hello, may I ask if this bug can be resolved? The menu will be interrupted on iOS's PWA application, making it difficult to operate. Thank you very much!

**Comment by pgpillar** [comment]
@WDaan dude thanks so much, myself and 10 other people I know who use this UI have been complaining about this for SO long. I came to see if it was fixed and my luck. Installing the new version now.

@oyrei I should have posted this when I first encountered it years ago, but I am thankful you did. Thank you!

**Comment by A54DH** [comment]
@WDaan should this be merged with #536? Seems like it's the same issue.

Although I'm not a developer by any stretch of the imagination, I was thinking that an approach to resolve this issue could be to show the context menu on swipe rather than 'right-click' on mobile devices. Would that work?

**Comment by WDaan** [comment]
Yes it's the same issue, I wrote the implementation for this an hour of 2 ago for the vue3 rewrite. Currently it seems fine and not as buggy as the vue2 implantation (even though the code is pretty much the same)


Maybe you could move to the new version? (Keep in mind, not everything is working perfectly just yet...)

**Comment by simonbcn** [comment]
I have tried the `nightly-release-vue3` version because I also have the same problem and it works fine.
