### ISSUE TITLE
[Feature Request] Batch renaming

### ISSUE THREAD

**Issue by yunyuyuan** [WDaan/VueTorrent#914]
Hello!I think this feature can be useful(see [https://github.com/qbittorrent/qBittorrent/pull/18287](https://github.com/qbittorrent/qBittorrent/pull/18287)),Do you plan to implement it?I would like to put some time in Vuetorrent and open a PR🖐️

**Comment by yunyuyuan** [comment]
Duplicate https://github.com/WDaan/VueTorrent/issues/895

**Comment by Larsluph** [comment]
Of course you're more than welcome to help us by opening a PR yourself !
