### ISSUE TITLE
Double tags in context menu

### ISSUE THREAD

**Issue by hypnosu** [WDaan/VueTorrent#939]
I have this issue with Safari on macOS Ventura, where the tags somehow appear twice in context menu. qBittorrent runs on FreeBSD.

https://www.imagebam.com/view/MEMJZA1

**Comment by Larsluph** [comment]
Quick fix: Replace this with a call to the `/torrents/tags` endpoint
https://github.com/WDaan/VueTorrent/blob/3d3b1bf4d847bf2c7ffc86e6fe6fcc3a286261e2/src/store/mutations.ts#L64

I think what happens here is that the update is duplicated somehow. As we only do a diff based on this response, if we call it twice, it will duplicate tags.
