### ISSUE TITLE
[Feature Request] Watch Folder

### ISSUE THREAD

**Issue by mivadebe** [WDaan/VueTorrent#96]
First of all, I love the interface! Have been using it for a couple of weeks now. 
One thing I was missing is the settings for defining the monitored folders / watch folders. Would be great if that could be added.

**Comment by WDaan** [comment]
Thanks for the kind words!

I've been trying to add it because it seemed like a very trivial thing to do ... but I can't get it to work. (by using their API)
I tried to change the monitored folder from the default WebUI and it doesn't seem to work either :slightly_frowning_face: 

Has that ever worked for you?

**Comment by mivadebe** [comment]
Hi

It works for me, but only when i add multiple folders. Seems like it doesnt
get the first one somehow. Add the same folder twice and it will work.
Though, in the config file it shows a strange path..

Keep up the nice work!

Gr
Michel

**Comment by WDaan** [comment]
![image](https://user-images.githubusercontent.com/25707052/104121152-8afe5900-533c-11eb-8fc4-2b651ba26b78.png)

Still doesn't seem to do anything :sweat_smile:

**Comment by mivadebe** [comment]
Hi,

See below my settings & docker image I use.


[image: image.png]

I use the following docker image with OPENVPN included:

docker-compose:

# QBITTORRENT
  qbittorrent-openvpn:
    container_name: qbittorrent-openvpn
*    image: guillaumedsde/alpine-qbittorrent-openvpn:latest*
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
*      - "/media/downloads:/downloads"*
      - "${DOCKERDIR}/qbittorrent/config:/config"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - OPENVPN_PROVIDER=###
      - OPENVPN_USERNAME=###
      - OPENVPN_PASSWORD=###
      - OPENVPN_CONFIG=###
      - LAN=192.168.1.0/24
    ports:
      - "8080:8080"
#      - "9117:9117" # jackett
#      - "7878:7878" # radarr
#      - "8989:8989" # sonarr


Hopefully that helps:)

**Comment by WDaan** [comment]
Thanks! I got it to work on the default WebUI, however their API is super weird for this.
Haven't quite gotten it to work yet
