### ISSUE TITLE
Long press the color differentiation of the selected task after the seed task is selected

### ISSUE THREAD

**Issue by oyrei** [WDaan/VueTorrent#962]
When I long-press a seed task, I sometimes forget which task I long-pressed because the order of the tasks keeps changing. Could it be optimized so that when I long-press a task and a menu pops up, the color of that task becomes different from the others? This would make it easier to distinguish which task is selected. Thank you.

**Comment by oyrei** [comment]
Similarly, when using the right mouse button to open a menu in a desktop browser, tasks should also have color differentiation.

**Comment by Larsluph** [comment]
You mean like when you click on delete on a torrent ? The torrent card in the background becomes selected and "lights up" ?

**Comment by oyrei** [comment]
yes！you're right
