### ISSUE TITLE
Torrent Detail scrolls also torrents list table that located below

### ISSUE THREAD

**Issue by IevgenSobko** [WDaan/VueTorrent#97]
Torrent Detail scrolls also torrents list table that located below
![Peek 2021-01-09 12-53](https://user-images.githubusercontent.com/14232100/104089724-c8e67900-5279-11eb-88d2-bb367691a305.gif)

**Comment by WDaan** [comment]
In both Chrome & Firefox, I can't seem to reproduce this :neutral_face:

**Comment by IevgenSobko** [comment]
Sry, it was my fault forget to verify without any extensions.
Seems one of my extensions affected how UI works.
