### ISSUE TITLE
Weird selected list item state on mobile

### ISSUE THREAD

**Issue by agneevX** [WDaan/VueTorrent#98]
VueTorrent has a rather weird behavior on touch devices.

When a torrent is not selected:

<img src="https://user-images.githubusercontent.com/19761269/104090930-0e1da180-52a0-11eb-8471-1e9116c91e61.png" width="280">

When a torrent is selected:

<img src="https://user-images.githubusercontent.com/19761269/104090949-24c3f880-52a0-11eb-8503-6ba1d0c6dc86.png" width="280">

When a torrent is de-selected by tapping on the free area above:
<img src="https://user-images.githubusercontent.com/19761269/104090972-58068780-52a0-11eb-8d87-2cad1ed7e062.png" width="280">

Note how the color of the last image looks different than the other states. 

Can you modify this behavior so that there are two states - selected and unselected?

**Comment by WDaan** [comment]
Yes I've known about it for a while... I think it's some default behavior of the Vuetify framework that I would need to override.

I will have to look into it or remove the tap to select behavior all together as there is a 'select mode' now.
