### ISSUE TITLE
Search results per page setting is reset when closing and re-opening the search page.

### ISSUE THREAD

**Issue by GRobecchi** [WDaan/VueTorrent#987]

**Comment by Larsluph** [comment]
Duplicates of #982

**Comment by WDaan** [comment]
Please check for existing issues when creating new ones

**Comment by GRobecchi** [comment]
Apologies, I will make sure to do so in the future.

**Comment by GRobecchi** [comment]
Actually, on further inspection, this is _not_ the same topic.

This is specifically with regards to the "results per page" setting, not the actual results.

When opening a new search tab, the amount of results shown setting at the bottom is set to the default 10, which can be annoying especially on screens with little or no real estate.

**Comment by Larsluph** [comment]
Ok now I understand the slight difference. Anyway, I'm working on an improvement to prevent having tabs independent from each other to fix the issue mentioned above. I will include yours as well 😉
