### ISSUE TITLE
[Bug] Sidebar does not update when main screen isn't on screen

### ISSUE THREAD

**Issue by lukemattle** [WDaan/VueTorrent#995]
The sidebar (which contains the speed graph etc) does not update when the main screen is not in use. 
For example, it won't be updated when you are looking at the details of a specific torrent.
By main screen, I mean the first screen you see after logging in, with all your torrents on

**Comment by Larsluph** [comment]
This is not a bug, it's intended. Not sure why we did it, but it can be changed easily.
@WDaan what do you think?
